-- -*- mode: lua; encoding: windows-1251 -*-

cheat_list = nil
gameIsOn = false
local particles = {}
local anoms = nil

function start_menu(self)
	if game_options.Spawner==false then return end
	gameIsOn = (level.present() and db.actor and db.actor:alive())
	if self.naxac_dlg == nil then
		self.naxac_dlg = cheat_main.ui_cheat_general()
		self.naxac_dlg:InitControls(20,20,self)
		self:AttachChild(self.naxac_dlg)
		self.naxac_dlg:Show(true)
	else
		local shown = self.naxac_dlg:IsShown()
		self.naxac_dlg:Show(shown==false)
	end
end

class "ui_cheat_general" (CUIScriptWnd)

function ui_cheat_general:__init() super() end

function ui_cheat_general:__finalize() end

function ui_cheat_general:InitControls(x, y, handler)
	self:Init(x, y, 391,130)
	self:SetAutoDelete(true)
	
	local back = CUIFrameWindow()
	back:SetAutoDelete(true)
	back:Init("ui_icons_PDA_dialog_frame",0, 0, 391,130)
	self:AttachChild(back)
	
	local con = get_console()
	
	self.show_spawn =		function( wnd )
								ui_cheat_soc.start_menu( wnd )
							end
	self.show_teleport =	function( wnd )
								naxac_teleport.start_menu( wnd )
							end
	self.show_mapspot =		function( wnd )
								add_item_spot.start_menu( wnd )
							end
	self.on_GodMode =	function( wnd )
							local mode = con:get_bool("g_god")
							con:execute("g_god "..(mode==true and "off" or "on"))
						end
	self.on_UnlimAmmo =	function( wnd )
							local mode = con:get_bool("g_unlimitedammo")
							con:execute("g_unlimitedammo "..(mode==true and "off" or "on"))
						end
	self.show_restr =	function( wnd )
							wnd:OnButton_return_game()
							cheat_main.show_restrictors()
						end
	self.show_anom =	function( wnd )
							wnd:OnButton_return_game()
							cheat_main.show_anomalies()
						end
	self.on_peace = 	function( wnd )
							wnd:OnButton_return_game()
							cheat_main.armistice()
						end
	
	local st = CUIStatic()
	st:SetAutoDelete(true)
	st:Init(15,7,80,20)
	st:SetText("Cheat Addon for «Cumulative Pack-2» by naxac ©")
	st:SetTextColor(255,255,127,150)
	back:AttachChild(st)
	
	local btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 10, 30, 117, 29)
	btn:SetText("Спавн-меню")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-3)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_show_spawn")
	handler:AddCallbackEx("btn_show_spawn", ui_events.BUTTON_CLICKED, self.show_spawn)
	
	btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 137, 30, 117, 29)
	btn:SetText("Телепортатор")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-3)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_teleport")
	handler:AddCallbackEx("btn_teleport", ui_events.BUTTON_CLICKED, self.show_teleport)
	btn:Enable(gameIsOn)
	
	btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 264, 30, 117, 29)
	btn:SetText("Поиск предметов")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-2)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_mapspot")
	handler:AddCallbackEx("btn_mapspot", ui_events.BUTTON_CLICKED, self.show_mapspot)
	btn:Enable(gameIsOn)
	
	btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 10, 70, 117, 29)
	btn:SetText(#particles==0 and "Показать рестрикторы" or "Скрыть рестрикторы")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-3)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_showrestr")
	handler:AddCallbackEx("btn_showrestr", ui_events.BUTTON_CLICKED, self.show_restr)
	btn:Enable(gameIsOn)
	
	btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 137, 70, 117, 29)
	btn:SetText(anoms==nil and "Отметить аномалии" or "Убрать метки")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-3)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_showanom")
	handler:AddCallbackEx("btn_showanom", ui_events.BUTTON_CLICKED, self.show_anom)
	btn:Enable(gameIsOn)
	
	btn = CUI3tButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_button_ordinary", 264, 70, 117, 29)
	btn:SetText("Перемирие")
	btn:SetTextAlign(CGameFont.alCenter)
	btn:SetTextY(-3)
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_peace")
	handler:AddCallbackEx("btn_peace", ui_events.BUTTON_CLICKED, self.on_peace)
	btn:Enable(gameIsOn)
	
	btn = CUICheckButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_checker",20,105,150,20)
	btn:SetText("Режим \"God mode\"")
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_godmode")
	handler:AddCallbackEx("btn_godmode", ui_events.BUTTON_CLICKED, self.on_GodMode)
	btn:SetCheck(con:get_bool("g_god"))
	
	btn = CUICheckButton()
	btn:SetAutoDelete(true)
	btn:Init("ui_checker",190,105,150,20)
	btn:SetText("Безлимитный боезапас")
	btn:SetTextColor(255,216,186,140)
	back:AttachChild(btn)
	handler:Register(btn, "btn_unlim_ammo")
	handler:AddCallbackEx("btn_unlim_ammo", ui_events.BUTTON_CLICKED, self.on_UnlimAmmo)
	btn:SetCheck(con:get_bool("g_unlimitedammo"))
end

function show_restrictors()
	if _G.show_restrictors_cheat then
		for k, v in pairs(particles) do
			if v.particle:playing() then
				v.particle:stop_deffered()
				level.map_remove_object_spot(v.id, "red_location_1")
			end
		end
		particles = {}
		amk.send_tip("Отображение рестрикторов %c[255,255,0,0]отключено")
		_G.show_restrictors_cheat = nil
		xr_s.unsubscribe("update", cheat_main.particle_update)
	else
		local obj, p
		for i=1,65534 do
			-- показываем только заспавненные скриптом рестрикторы
			obj = level.object_by_id(i)
			if obj and obj:clsid() == clsid.script_restr then
				if obj:name() == obj:section()..i then
					p = particles_object("ghoul\\anomal-04-blue-field")
					p:play_at_pos(obj:position())
					table.insert(particles, {particle=p,pos=obj:position(),id=obj:id()})
					level.map_add_object_spot(obj:id(), "red_location_1", obj:name())
				end
			end
		end
		if #particles>0 then
			_G.show_restrictors_cheat = true
			amk.send_tip("Отображение рестрикторов ("..tostring(#particles).." шт) %c[255,0,255,0]включено")
			xr_s.subscribe("update", cheat_main.particle_update)
		else
			amk.send_tip("Скриптовых рестрикторов не найдено")
		end
	end
end

function particle_update()
	for i,v in pairs(particles) do
		if alife():object(v.id)==nil then
			v.particle:stop_deffered()
		--	level.map_remove_object_spot(v.id, "red_location_1")
			particles[i] = nil
			if #particles==0 then
				xr_s.unsubscribe("update", cheat_main.particle_update)
				_G.show_restrictors_cheat=nil
			end
		else
			if not v.particle:playing() then
				v.particle:play_at_pos(v.pos)
			end
		end
	end
end

function show_anomalies()
	if anoms==nil then
		anoms = {}
		local obj
		for i=1,65534 do
			obj = level.object_by_id(i)
			if obj and amk_anoms.is_anomaly(obj:clsid()) then
				level.map_add_object_spot(obj:id(), 'red_location_1', obj:name())
				table.insert(anoms, obj:id())
			end
		end
		amk.send_tip("Метки на аномалии установлены.")
	else
		for k,v in pairs(anoms) do
			level.map_remove_object_spot(v, 'red_location_1')
		end
		anoms = nil
		amk.send_tip("Метки с аномалий удалены.")
	end
end

function armistice()
	local ini = ini_file("creatures\\game_relations.ltx")
	local result, comm, rel
	for i=1, ini:line_count("communities_relations")-1 do
		result, comm, rel = ini:r_line("communities_relations",i,"","")
		rel = tonumber( string.match(rel, "^%s*([%d%-]+)") )
		if rel and rel>=0 then
			relation_registry.set_community_goodwill(comm, 0, math.max(500, rel))
		end
	end
end

function transfer_box_items(box_from, box_to)
	log1("start")
	local box1 = alife():object("m_inventory_box27942")
	local box2 = alife():object("m_inventory_box21922")	--level_prefix_inventory_box_0003
	if box1 and box2 then
		log1("alife objects found")
		local lBox1 = level.object_by_id(box1.id)
		local lBox2 = level.object_by_id(box2.id)
		if lBox1 and lBox2 then
			log1("boxes is online")
			local cnt = lBox1:inv_box_count()
			if cnt>0 then
				log1("transfer start : count "..cnt)
				local itm
				for i=0,cnt-1 do
					itm = lBox1:object_from_inv_box(i)
					lBox1:transfer_item(itm, lBox2)
				end
				amk.send_tip("Перемещено "..tostring(cnt).." предметов.")
			end
		end
	end
end

