-- -*- mode: lua; encoding: windows-1251 -*-
local check_tbl = {}
local point_drop={
    {x=-240, y=-7, z=300},
    {x=-250, y=-5, z=294},
	{x=55, y=18, z=157},
    {x=67, y=22, z=154},
	{x=7, y=-1, z=115},
    {x=12, y=1, z=125},
	{x=35, y=60, z=30}, 
	{x=17, y=50, z=35},
	{x=376, y=-1, z=15},
	{x=393, y=2, z=65},
	{x=80, y=8, z=-16},
	{x=88, y=12, z=-24},
	{x=7, y=3, z=11},
	{x=15, y=7, z=19},
	{x=-126, y=19, z=-28},
	{x=-134, y=23, z=-36}
	}

--check_tbl['grenade_flash'] = function(obj)
--	bind_grenade.actor_drop(obj)
--end

check_tbl['player'] = function(item)
	player_ogg.lose_item(item)
end
check_tbl['sak_resiver_yantar'] = function(obj)
	local actor = db.actor
	local lname = level.name()
	if lname=="l07_military"
		and actor:has_info("yan_scientist_teleport_01_start")
		and amk.check_npc_in_box(actor, point_drop[1],point_drop[2])~=false
	then
		actor:give_info_portion("yan_scientist_teleport_01_done")
		amk.spawn_item("m_sak_resiver_yantar",vector():set(-244.62,-5.98,299.94),1797,89408)
		amk.remove_item(obj)
	elseif lname=="l01_escape"
		and actor:has_info("yan_scientist_teleport_02_start")
		and amk.check_npc_in_box(actor, point_drop[3],point_drop[4])~=false
	then
		actor:give_info_portion("yan_scientist_teleport_02_done")
		amk.remove_item(obj)
		amk.spawn_item("m_sak_resiver_yantar",vector():set(62.99,29.23,154.39),97,359827)
	elseif lname=="l11_pripyat"
		and actor:has_info("yan_scientist_teleport_03_start")
		and amk.check_npc_in_box(actor, point_drop[5],point_drop[6])~=false
	then
		actor:give_info_portion("yan_scientist_teleport_03_done")
		amk.remove_item(obj)
		amk.spawn_item("m_sak_resiver_yantar",vector():set(9.47,0.32,119.13),2166,113785)
	elseif lname=="l12_stancia"
		and actor:has_info("life_heart_sahar_start")
		and amk.check_npc_in_box(actor, point_drop[9],point_drop[10])~=false
	then
		actor:give_info_portion("life_heart_sahar_have")
		amk.remove_item(obj)
		amk.spawn_item("m_sak_resiver_yantar",vector():set(387.51,0.16,31.10),2384,168953)
	end
end
check_tbl['poison_gaz_ballon'] = function(obj)
	local actor = db.actor
	if level.name()~="l08u_brainlab"
		or not actor:has_info("ohota_suker_start")
	then return end
	if amk.check_npc_in_box(actor, point_drop[11],point_drop[12])~=false then
		actor:give_info_portion("ohota_suker_have1")
		amk.remove_item(obj)
		alife():create("m_poison_gaz_ballon",vector():set(84.25,10.17,-20.63),6077,1544)
	elseif amk.check_npc_in_box(actor, point_drop[13],point_drop[14])~=false then
		actor:give_info_portion("ohota_suker_have2")
		amk.remove_item(obj)
		alife():create("m_poison_gaz_ballon",vector():set(11.52,5.59,15.10),4459,1537)
	elseif amk.check_npc_in_box(actor, point_drop[15],point_drop[16])~=false then
		actor:give_info_portion("ohota_suker_have3")
		amk.remove_item(obj)
		alife():create("m_poison_gaz_ballon",vector():set(-130.45,21.56,-32.76),3,1529)
	end
end
check_tbl['af_gold_fish'] = function(obj)
	if level.name()~="l12u_sarcofag" then return end
	if db.actor:has_info("strelok_pda_have")
		and amk.check_npc_in_box(db.actor, point_drop[7],point_drop[8])~=false
	then
		amk_mod.af_flash(obj)
		sak.get_sarcofag_stancia()
	end
end
check_tbl['af_life_heart'] = function(obj)
	if db.actor:has_info("life_heart_final") then
		sak.deadman_to_life(obj)
	end
end
check_tbl['af_hl'] = function(obj)
	sak.deadman_to_life(obj)
end
check_tbl['glushitel'] = function(obj)
	if db.actor:has_info("borman_glushitel_restr") then
		db.actor:give_info_portion("borman_glushitel_have")
	end
end
check_tbl['nebo_clear'] = function(obj)
	if db.actor:has_info("nebo_kurier_del") then
		braad_test.del_lim()
		local sobj = alife():object(obj:id())
		if sobj then alife():release(sobj) end
	end
end
-- snp
check_tbl['snp_skull'] = function(obj)
	if level.name()~="av_peshera" then return end
	if has_alife_info("snp_almaz2") and
		not has_alife_info("snp_almaz_skull_droped") and
		db.actor:position():distance_to(vector():set(174.08480834961,55.11833190918,386.01168823242)) < 2
	then
		db.actor:give_info_portion("snp_almaz_skull_droped")
		level.start_stop_menu(level.main_input_receiver(), true)
		amk.remove_item(obj)
		level.add_pp_effector("teleport.ppe", 1626, false)
		sak.out_item_all("snp_skull")
		amk.start_timer("run", 10, "snp_spawn.almaz_done()")
	end
end
check_tbl['af_zvezda_proroka'] = function(obj)
	if has_alife_info("snp_proper7012_done")
		and not has_alife_info("snp_fenrir_resurrected")
	then
		snp.fenrir_recurrection()
	end
end

check_tbl['bullion_gild'] = function(obj)
	if db.actor:character_community() == "freedom" then
		db.actor:set_character_community ("stalker", 0, 0)
	end
end

check_tbl['amk_metka'] = function (item) amk_mod.check_beacon_drop(item) end
check_tbl['af_black_hole'] = function (item) anom_remover.on_item_drop() end
-- arc_radiation
check_tbl['lekar_kalmyak'] = function (item)
	arc_radiation.change_inv_radiation(-0.008)
end
check_tbl['mushroom'] = function (item)
	arc_radiation.change_inv_radiation(-0.001)
end
check_tbl['case_nebo'] = function (item)
	arc_radiation.change_inv_radiation(-0.003)
	xr_s.unsubscribe("update", arc_radiation.spawn_telepatic)
end

check_tbl['zamok'] = function (item)
	if _G["biznes_remove_special_item"]==nil then
		zamok.add(item)
	end
end


function check(item)
	local sect = item:section()
	if check_tbl[sect] then
		check_tbl[sect](item)
	end
end
