local artefacts = {
	-- оригинал
	["af_medusa"] = { info = {"encyclopedy_zone_artifact_af-medusa", "esc_shustryi_medusa_start", "info_artmod_medusa_galant"}, lvl = 1, power = 0.2, hType = "strike" },
	["af_cristall_flower"] = { info = {"encyclopedy_zone_artifact_af-cristall-flower", "info_artmod_cristall_flower_mincer", "info_artmod_cristall_flower_galant"}, lvl = 2, power = 0.3, hType = "strike" },
	["af_night_star"] = { info = {"encyclopedy_zone_artifact_af-night-star", "info_artmod_night_star_zharka", "info_artmod_night_star_gravi_zone", "kvest_art_started"}, lvl = 3, power = 0.4, hType = "strike" },
	["af_vyvert"] = { info = {"encyclopedy_zone_artifact_af-vyvert", "info_artmod_vyvert_buzz"}, lvl = 1, power = 0.2, hType = "radiation" },
	["af_gravi"] = { info = {"encyclopedy_zone_artifact_af-gravi", "info_artmod_gravi_zharka"}, lvl = 2, power = 0.3, hType = "radiation" },
	["af_gold_fish"] = { info = {"encyclopedy_zone_artifact_af-gold-fish", "info_artmod_gold_fish_galant", "info_artmod_night_star_buzz", "kostya_art_start"}, lvl = 3, power = 0.5, hType = "radiation" },
	["af_drops"] = { info = {"encyclopedy_zone_artifact_af-drops", "info_artmod_drops_mincer"}, lvl = 1, power = 0.2, hType = "burn" },
	["af_fireball"] = { info = {"encyclopedy_zone_artifact_af-fireball", "info_artmod_fireball_galant", "info_artmod_fireball_buzz"}, lvl = 2, power = 0.3, hType = "burn" },
	["af_cristall"] = { info = {"encyclopedy_zone_artifact_af-cristall", "info_artmod_cristall_buzz", "info_artmod_cristall_mosquito_bald"}, lvl = 3, power = 0.4, hType = "burn" },
	["af_blood"] = { info = {"encyclopedy_zone_artifact_af-blood", "info_artmod_blood_mincer"}, lvl = 1, power = 0.2, hType = "wound" },
	["af_mincer_meat"] = { info = {"encyclopedy_zone_artifact_af-mincer-meat", "info_artmod_mincer_meat_mosquito_bald"}, lvl = 2, power = 0.3, hType = "wound" },
	["af_soul"] = { info = {"encyclopedy_zone_artifact_af-soul", "info_artmod_electra_moonlight_galant", "info_artmod_soul_gravi_zone"}, lvl = 3, power = 0.4, hType = "wound" },
	["af_electra_sparkler"] = { info = {"encyclopedy_zone_artifact_af-electra-sparkler", "info_artmod_electra_sparkler_mosquito_bald"}, lvl = 1, power = 0.2, hType = "shock" },
	["af_electra_flash"] = { info = {"encyclopedy_zone_artifact_af-electra-flash", "info_artmod_electra_flash_zharka", "info_artmod_electra_flash_gravi_zone"}, lvl = 2, power = 0.3, hType = "shock" },
	["af_electra_moonlight"] = { info = {"encyclopedy_zone_artifact_af-electra-moonlight", "info_artmod_electra_moonlight_zharka", "info_artmod_electra_moonlight_mincer"}, lvl = 3, power = 0.4, hType = "shock" },
	["af_ameba_slime"] = { info = {"encyclopedy_zone_artifact_af-ameba-slime", "info_artmod_ameba_slime_zharka", "info_artmod_ameba_slime_gravi_zone"}, lvl = 1, power = 0.2, hType = "chemical_burn" },
	["af_ameba_slug"] = { info = {"encyclopedy_zone_artifact_af-ameba-slug", "info_artmod_ameba_slug_mosquito_bald", "info_artmod_ameba_slug_gravi_zone"}, lvl = 2, power = 0.3, hType = "chemical_burn" },
	["af_ameba_mica"] = { info = {"encyclopedy_zone_artifact_af-ameba-mica", "info_artmod_ameba_mica_galant", "info_artmod_ameba_slug_mincer"}, lvl = 3, power = 0.4, hType = "chemical_burn" },
	["af_dummy_spring"] = { info = {"encyclopedy_zone_artifact_af-dummy-spring", "info_artmod_dummy_spring_galant"}, lvl = 3, power = 0.4, hType = "explosion" },
	["af_dummy_dummy"] = { info = {"encyclopedy_zone_artifact_af-dummy-dummy", "info_artmod_dummy_dummy_mosquito_bald"}, lvl = 3, power = 0.4, hType = "explosion" },
	["af_dummy_battery"] = { info = {"encyclopedy_zone_artifact_af-dummy-battery", "info_artmod_dummy_battery_zharka"}, lvl = 3, power = 0.4, hType = "shock" },
	["af_dummy_pellicle"] = { info = {"encyclopedy_zone_artifact_af-dummy-pellicle", "info_artmod_dummy_pellicle_gravi_zone"}, lvl = 3, power = 0.4, hType = "chemical_burn" },
	["af_dummy_glassbeads"] = { info = {"encyclopedy_zone_artifact_af-dummy-glassbeads", "info_artmod_dummy_glassbeads_mincer"}, lvl = 3, power = 0.4, hType = "radiation" },
	["af_rusty_thorn"] = { info = {"encyclopedy_zone_artifact_af-rusty-thorn", "info_artmod_rusty_thorn_buzz"}, lvl = 1, power = 0.2, hType = "telepatic" },
	["af_rusty_kristall"] = { info = {"encyclopedy_zone_artifact_af-rusty-kristall", "info_artmod_rusty_kristall_buzz", "info_artmod_rusty_kristall_mincer"}, lvl = 2, power = 0.3, hType = "telepatic" },
	["af_rusty_sea-urchin"] = { info = {"encyclopedy_zone_artifact_af-rusty-sea-urchin", "info_artmod_rusty_sea-urchin_mosquito_bald"}, lvl = 3, power = 0.4, hType = "telepatic" },
	["af_fuzz_kolobok"] = { info = {"encyclopedy_zone_artifact_af-fuzz-kolobok", "info_artmod_fuzz_kolobok_buzz"}, lvl = 3, power = 0.5, hType = "telepatic" },
	-- солянка
	["af_dummy_spring_red"] = { info = {"info_red_spring"}, lvl = 4, power = 0.5, hType = "explosion" },
	["af_dummy_battery_red"] = { info = {"info_red_battery"}, lvl = 4, power = 0.5, hType = "shock" },
	["af_dummy_pellicle_red"] = { info = {"info_red_pellicle"}, lvl = 4, power = 0.5, hType = "chemical_burn" },
	["af_medusa_green"] = { info = {"strelok_pda2_start"}, lvl = 4, power = 0.6, hType = "strike" },
	["af_vyvert_green"] = { info = {"bar_dolg_base_guard_art_start"}, lvl = 5, power = 0.6 },
	["af_blood_green"] = { info = {"yan_kruglov_green_art_done"}, lvl = 5, power = 0.6, hType = "wound" },
	["art_acumm"] = { lvl = 1, power = 0.2, hType = "shock" },
	["af_buliz"] = { lvl = 1, power = 0.0, hType = "radiation" },
	["af_spirit_1"] = { info = {"info_amk_recipt_soul_drops"}, lvl = 4, power = 0.6, hType = "telepatic" },
	["af_spirit_2"] = { info = {"info_amk_recipt_soul_fire"}, lvl = 5, power = 0.6, hType = "burn" },
	["af_spirit_3"] = { info = {"info_amk_recipt_soul_cristal"}, lvl = 6, power = 0.6, hType = "wound" },
	["af_spirit_4"] = { info = {"info_amk_recipt_soul_bengal"}, lvl = 7, power = 0.7, hType = "wound" },
	["af_cry_1"] = { info = {"info_amk_recipt_tears_electra", "zvezdochet_talk1_start"}, lvl = 4, power = 0.6, hType = "shock" },
	["af_cry_2"] = { info = {"info_amk_recipt_tears_fire"}, lvl = 5, power = 0.6, hType = "burn" },
	["af_cry_3"] = { info = {"info_amk_recipt_tears_chimaera"}, lvl = 6, power = 0.6, hType = "wound" },
	["af_cry_4"] = { info = {"spatial_subway_doc"}, lvl = 7, power = 0.7 },
	["af_babka_1"] = { info = {"info_amk_recipt_grandmother_glassbeards"}, lvl = 4, power = 0.6, hType = "radiation" },
	["af_babka_2"] = { info = {"info_amk_recipt_pra_grandmother_glassbeards"}, lvl = 5, power = 0.6, hType = "radiation" },
	["af_babka_3"] = { info = {"info_amk_recipt_burer_grandmother_glassbeards"}, lvl = 6, power = 0.6, hType = "radiation" },
	["af_babka_4"] = { info = {"info_artmod_probabka_burera"}, lvl = 7, power = 0.7, hType = "radiation" },
	["af_pudd_1"] = { info = {"info_amk_recipt_dummy_fire"}, lvl = 4, power = 0.6, hType = "burn" },
	["af_pudd_2"] = { info = {"info_amk_recipt_dummy_bright"}, lvl = 5, power = 0.6, hType = "strike" },
	["af_pudd_3"] = { info = {"info_amk_recipt_dummy_moon"}, lvl = 6, power = 0.6, hType = "wound" },
	["af_pudd_4"] = { info = {"info_amk_recipt_dummy_puding"}, lvl = 7, power = 0.7, hType = "fire_wound" },
	["af_dik_1"] = { info = {"info_amk_recipt_dikoobraz"}, lvl = 4, power = 0.6, hType = "telepatic" },
	["af_dik_2"] = { info = {"info_amk_recipt_electra_dikoobraz"}, lvl = 5, power = 0.6, hType = "shock" },
	["af_dik_3"] = { info = {"info_amk_recipt_sopl_dikoobraz"}, lvl = 6, power = 0.6, hType = "chemical_burn" },
	["af_dik_4"] = { info = {"info_amk_recipt_stone_dikoobraz"}, lvl = 7, power = 0.7, hType = "strike" },
	["af_kol_1"] = { info = {"info_amk_recipt_steel_kolobok"}, lvl = 4, power = 0.6, hType = "fire_wound" },
	["af_kol_2"] = { info = {"info_amk_recipt_titan_kolobok"}, lvl = 5, power = 0.6, hType = "explosion" },
	["af_kol_3"] = { info = {"info_amk_recipt_almaz_kolobok"}, lvl = 6, power = 0.6, hType = "wound" },
	["af_kol_4"] = { info = {"info_amk_recipt_giant_small_brother"}, lvl = 7, power = 0.7, hType = "strike" },
	["af_armor_1"] = { info = {"info_amk_recipt_shkura"}, lvl = 4, power = 0.6, hType = "telepatic" },
	["af_armor_2"] = { info = {"info_amk_recipt_cheshya"}, lvl = 5, power = 0.6, hType = "telepatic" },
	["af_armor_3"] = { info = {"info_amk_recipt_pancir"}, lvl = 6, power = 0.6, hType = "telepatic" },
	["af_armor_4"] = { info = {"info_amk_recipt_controller_skalp"}, lvl = 7, power = 0.7, hType = "telepatic" },
	["af_simbion"] = { info = {"info_amk_recipt_simbion"}, lvl = 5, power = 0.7, hType = "radiation" },
	["af_arhara_globus"] = { info = {"info_artmod_globus"}, lvl = 6, power = 0.5, hType = "strike" },
	["af_caterpillar"] = { info = {"info_artmod_gusenica"}, lvl = 5, power = 0.5, hType = "radiation" },
	["artifact_electro_crystal_thorn"] = { info = {"shax_kniga_naity_start"}, lvl = 5, power = 0.5, hType = "chemical_burn" },
	-- оп-2
	["af_electra_green"] = { info = {"izumrud_recept_start"}, lvl = 5, power = 0.3, hType = "chemical_burn" },
	["af_power"] = { lvl = 4, power = 0.6, hType = "shock" },
	["af_power_1"] = { info = {"info_amk_recipt_power_1"}, lvl = 5, power = 0.6, hType = "shock" },
	["af_power_2"] = { info = {"info_amk_recipt_power_2"}, lvl = 6, power = 0.6, hType = "shock" },
	["af_power_3"] = { info = {"info_amk_recipt_power_3"}, lvl = 7, power = 0.6, hType = "shock" },
	["af_idol_monolita"] = { info = {"snp_almaz3"}, lvl = 7, power = 0.9, hType = "radiation" },
	["af_art_fenrira"] = { lvl = 7, power = 0.9, hType = "wound" },
	["af_zvezda_proroka"] = { info = {"snpt_jupiter3_have1"}, lvl = 7, power = 1.5, hType = "telepatic" },
	["af_gelion"] = { lvl = 7, power = 1.6, hType = "strike" },
	["af_fobos"] = { lvl = 7, power = 0.8, hType = "explosion" },
	["af_encelad"] = { lvl = 7, power = 0.6, hType = "chemical_burn" },
	["af_serpantin"] = { lvl = 7, power = 0.7, hType = "telepatic" },
	["af_ahill_piata"] = { lvl = 7, power = 0.9, hType = "telepatic" },
	["af_control"] = { info = {"fli_chaes_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_oasis_heart"] = { info = {"fli_chaes_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_elf"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_vata"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_diablo"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_gnilec"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_compas"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_ice"] = { info = {"fli_done"}, lvl = 5, power = 0.7, hType = "telepatic" },
	["af_katushka"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_kamen"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_baloon"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_medium"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_fire"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_kaply"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_lava"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_fenix"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_yantarnik"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_goldgravi"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_shipovnik"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_sunlight"] = { info = {"fli_done"}, lvl = 6, power = 0.8, hType = "telepatic" },
	["af_protomedusa"] = { info = {"fli_done"}, lvl = 6, power = 0.7, hType = "telepatic" },
	["af_inferno"] = { info = {"sidor_stvol_start"}, lvl = 7, power = 0.6, hType = "chemical_burn" },
	["af_kokon"] = { lvl = 6, power = 0.4, hType = "chemical_burn" },
	["af_prisoska"] = { lvl = 6, power = 0.3, hType = "chemical_burn" },
	["af_sandstown"] = { lvl = 6, power = 0.4, hType = "chemical_burn" },
	["af_pylesos"] = { lvl = 6, power = 0.3, hType = "chemical_burn" },
	["af_glass"] = { lvl = 6, power = 0.2, hType = "chemical_burn" },
	["af_fontan"] = { lvl = 6, power = 0.5, hType = "chemical_burn" },
	["af_fallen_angel"] = { lvl = 6, power = 0.3, hType = "chemical_burn" },
	["af_pero"] = { lvl = 5, power = 0.1, hType = "chemical_burn" },
	["af_vinograd"] = { lvl = 6, power = 0.4, hType = "chemical_burn" },
	["af_kletka"] = { lvl = 6, power = 0.5, hType = "chemical_burn" },
	["af_mayak"] = { lvl = 6, power = 0.3, hType = "chemical_burn" },
	["af_parazit"] = { lvl = 6, power = 0.3, hType = "chemical_burn" },
	["af_propeller"] = { lvl = 6, power = 0.4, hType = "chemical_burn" },
	["af_kvazar"] = { lvl = 6, power = 0.5, hType = "chemical_burn" },
	["af_black_hole"] = { lvl = 6, power = 0.1, hType = "chemical_burn" },
	["af_provoloka"] = { info = {"volna_sak_start"}, lvl = 6, power = 0.6, hType = "chemical_burn" },
	["af_eye_voron"] = { info = {"voron_kostya"}, lvl = 6, power = 0.5, hType = "telepatic" },
	["af_black_angel"] = { lvl = 7, power = 1.5, hType = "telepatic" },
	["af_phantom"] = { lvl = 6, power = 0.5, hType = "wound" },
	["af_serafim"] = { lvl = 5, power = 0.2, hType = "shock" },
	["af_kristal_zp"] = { lvl = 6, power = 0.5, hType = "telepatic" },
	["af_kristal_blue"] = { lvl = 6, power = 0.5, hType = "wound" },
	["af_repei"] = { lvl = 5, power = 0.2, hType = "shock" },
	["af_dummy_indilian"] = { lvl = 6, power = 0.5, hType = "radiation" },
	["af_dummy_djoker"] = { lvl = 6, power = 0.5, hType = "telepatic" },
	["af_dummy_coal"] = { lvl = 5, power = 0.4, hType = "wound" },
	["af_dummy_seashell"] = { lvl = 6, power = 0.3, hType = "telepatic" },
	["af_dummy_mushroom"] = { lvl = 6, power = 0.4, hType = "radiation" },
	["af_dummy_dumbbell"] = { lvl = 6, power = 0.5, hType = "strike" },
	["af_dummy_vertyshka"] = { lvl = 6, power = 0.4, hType = "shock" },
	["af_dummy_star_monolith"] = { lvl = 7, power = 0.7, hType = "telepatic" },
	["af_dummy_quill"] = { lvl = 4, power = 0.2, hType = "wound" },
	["af_dummy_wool"] = { lvl = 5, power = 0.3, hType = "burn" },
	["af_dummy_bonanza"] = { lvl = 6, power = 0.4, hType = "chemical_burn" },
	["af_dummy_mercury_ball"] = { lvl = 6, power = 0.5, hType = "shock" },
	["af_dummy_bezi"] = { lvl = 5, power = 0.2, hType = "chemical_burn" },
	["af_dummy_glow"] = { lvl = 5, power = 0.3, hType = "burn" },
	["af_dummy_node"] = { lvl = 6, power = 0.4, hType = "strike" },
	["af_kosi"] = { lvl = 7, power = 0.5, hType = "telepatic" },
	["af_siyanie"] = { lvl = 6, power = 0.6, hType = "telepatic" },
	["af_klever"] = { lvl = 5, power = 0.4, hType = "telepatic" },
	["af_giperbola"] = { lvl = 6, power = 0.6, hType = "telepatic" },
	["af_braslet"] = { lvl = 6, power = 0.6, hType = "telepatic" },
	["af_bol_prizrak"] = { lvl = 5, power = 0.5, hType = "telepatic" },
	["af_pakost"] = { lvl = 4, power = 0.8, hType = "telepatic" },
	["af_shkatulka"] = { lvl = 6, power = 0.6, hType = "telepatic" },
	-- Квестовые артефакты
	["kostya_af_gold_fish"] = { parent = "af_gold_fish" },
	["amk_af_night_star"] = { parent = "af_night_star" },
	["gold_art"] = { info = {"gold_art_start"}, lvl = 6, power = 0.5, hType = "telepatic" },
	["af_life_heart"] = { info = {"life_heart_final"}, lvl = 7, power = 1.0, hType = "telepatic" },
	["af_part_monolit"] = { info = {"shaxter_fonar_dost_done"}, lvl = 7, power = 1.3, hType = "telepatic" },
	["af_hl"] = { parent = "af_life_heart" },
	["af_rusty_sea-urchin1"] = { parent = "af_rusty_sea-urchin" },
	["af_alive_water"] = { info = {"info_sugar_poll"}, lvl = 7, power = 0.7, hType = "telepatic" },
	["af_black_mark"] = { info = {"info_narration_oldman"}, lvl = 6, power = 1.5, hType = "telepatic" },
	["af_part_monolit1"] = { parent =  "af_part_monolit" },
	["af_part_monolit2"] = { parent =  "af_part_monolit" },
	["af_water_flower"] = { lvl = 5, power = 0.7, hType = "wound" },
	["af_water_flower1"] = { parent =  "af_water_flower" },
	["af_spiral"] = { info = {"polt_art_done"}, lvl = 4, power = 0.4, hType = "explosion" },
	["af_kamen_udachy"] = { info = {"mozno_varit"}, lvl = 7, power = 1.2, hType = "telepatic" },
	["af_kamen_udachy2"] = { parent = "af_kamen_udachy" },
	["af_kamen_udachy3"] = { parent = "af_kamen_udachy" }
}

-- для каждого вида перчаток коэфициент пропуска силы поражения, которая останется от изначальной
local perchatki_propusk = {
	["wpn_fist_c1"]		= 0.7, -- ПРОРЕЗИННЫЕ
	["wpn_fist_c2"]		= 0.5, -- УСОВЕРШЕНСТВОВАННЫЕ
	["wpn_fist_c3"]		= 0.3, -- МОДЕРНИЗИРОВАННЫЕ
	["wpn_fist_c4"]		= 0.0  -- УНИКАЛЬНЫЕ
}

-- секции научных броников
local scient = {
	["merc_scientific_outfit"]		= 0.5,	-- Научный костюм наёмников и его модификации
	["scientific_outfit"]			= 0.5,	-- Научный костюм НЕЙТРАЛЬНОГО СТАЛКЕРА и его модификации
	["dolg_scientific_outfit"]		= 0.3,	-- Научный костюм ДОЛГА и его модификации
	["freedom_scientific_outfit"]	= 0.2,	-- Научный костюм Свободы и его модификации
	["monolit_scientific_outfit"]	= 0.2,	-- Научный костюм Монолита и его модификации
	["nebo_scientific_outfit"]		= 0.0,	--НАУЧНЫЙ КОСТЮМ ЧИСТОГО НЕБА и его модификации
	["protection_outfit"]			= 0.0,	-- Комбинезон ССП-99М "Вега" и его модификации
	["ecolog_outfit"]				= 0.0,	-- ОБЫЧНЫЙ КОСТЮМ УЧЕННОГО и его модификации
    ["nano_outfit"]					= 0.0,
    ["nano_suit"]					= 0.0,
    ["exo_knight_outfit"]			= 0.0,
    ["exo_doktor_outfit"]			= 0.0,
-- Akill begin
    ["gagarin_outfit"]				= 0.0,	-- Бронекостюм Гагарин
	["gagarin_outfit_m1"]			= 0.0,	-- Мод. Гагарин
	["voshod_outfit"]				= 0.0,	-- Бронекостюм Восход
-- Akill end
    ["seva_scient_outfit"]			= 0.0,
    ["exo_scientist_outfit"]		= 0.0   
}

local id2art = {}
local info2art = {}
local art2child = {}

function init()
	for s, t in pairs(artefacts) do
		t.known = false
	
		if t.parent == nil then
			table.insert(id2art, s)
		else
			if art2child[t.parent] == nil then
				art2child[t.parent] = {}
			end
			table.insert( art2child[t.parent], s )
		end
	
		if t.info then
			for i, v in ipairs(t.info) do
				if info2art[v] == nil then
					info2art[v] = {}
				end
				table.insert( info2art[v], s )
			end
		end
	end
	table.sort( id2art, function(s1, s2) return s1 < s2 end )
end
-----------------------------------------------------------------------------------------------
local cant_hit = true

function hit_by_art(obj)
	if _G["biznes_remove_special_item"] or cant_hit then return end
	if has_alife_info("peshera_go") then return end

	local s = obj:section()
	if artefacts[s] and level.main_input_receiver() == nil then
		local propusk = 1

		local perchatki = db.actor:item_in_slot( inventory_slots.KNIFE )
		if perchatki then
			propusk = perchatki_propusk[perchatki:section()] or 1
		end

		local outf = db.actor:item_in_slot( inventory_slots.OUTFIT )
		if outf then
			propusk = propusk * ( scient[outf:section()] or 1)
		end

		local p = propusk * get_art_power(s)
		if p > 0 then
			local h = hit()
			h.draftsman = db.actor
			h.direction = vector():set(0,0,0)
			h.impulse = 0.3
			h.type = hit[ artefacts[s].hType or "shock" ]
			h.power = p

			local cameffs ={"hit_front","hit_back","hit_front_left","hit_back_left","hit_front_right","hit_back_right"}
			level.add_cam_effector("camera_effects\\"..table.random(cameffs)..".anm", 999, false, "")
			db.actor:hit(h)
		end
	end
end

function on_slot(item)
	local sect = item:section()
	if perchatki_propusk[sect] then
		local outf = db.actor:item_in_slot( inventory_slots.OUTFIT )
		if outf and scient[outf:section()]~=nil then
			db.actor:move_to_ruck(item)
		end
	elseif scient[sect] then
		local knife = db.actor:item_in_slot( inventory_slots.KNIFE )
		if knife and perchatki_propusk[knife:section()] then
			db.actor:move_to_ruck(knife)
		end
	end
end

function first_update()
	cant_hit = false
end
-----------------------------------------------------------------------------------------------
function is_known_art(section)
	local t = artefacts[section]
	if t == nil then return true end
	if has_alife_info("peshera_go") then return true end
	return t.known
end

function add_art_info(art)
	local t = artefacts[art]
	if not t then return end

	if t.known == true then return end

	t.known = true
	if art2child[art] then
		for i, v in ipairs( art2child[art] ) do
			artefacts[v].known = true
		end
	end

	local task_texture, task_rect = get_texture_info("ui_iconsTotal_locations", "ui_iconsTotal_locations")
	local news_text = "%c[255,160,160,160]Получена информация об артефакте:\\n"..
		"%c[255,255,255,0]"..game.translate_string( get_inv_name(art) )
	db.actor:give_game_news(news_text, task_texture, task_rect, 0, 5000)
	if db.actor:is_talking() then
		local icon = GetIconParams(art)
		db.actor:give_talk_message(news_text, "ui\\ui_icon_equipment", Frect():set(icon.x, icon.y, icon.w, icon.h), "iconed_icon_item")
	end	
end

function get_art_name(section, need_level)
	if is_known_art(section) then
		return get_inv_name(section)
	end

	if need_level then
		return "unknown_art_"..tostring( artefacts[section].lvl )
	end

	return "unknown_art"
end
-----------------------------------------------------------------------------------------------
function get_art_power(section)
	local t = artefacts[section]
	return t.power or (t.parent and artefacts[t.parent].power) or 0
end
-----------------------------------------------------------------------------------------------
function on_info(info_id)
	local t = info2art[info_id]
	if t then
		for i, art in ipairs(t) do
			this.add_art_info(art)
		end
	end
end

function load(reader)
	if reader:r_eof() then
		this.first_run()
		return
	end

	local n = reader:r_u8()
	if n == 0 then return end

	local id
	for i = 1, n do
		id = reader:r_u8()
		if id ~= 0 and id2art[id]  then
			artefacts[ id2art[id] ].known = true
		end
	end
end
-- сохранять будем всю таблицу, чтобы можно было ее изменять
function save(packet)
	packet:w_u8(#id2art)
	for i, s in ipairs(id2art) do
		if artefacts[s].known then
			packet:w_u8(i)
		else
			packet:w_u8(0)
		end
	end
end

function first_run()
	for info, tbl in pairs(info2art) do
		if has_alife_info(info) then
			for i, art in ipairs(tbl) do
				local t = artefacts[art]
				if not t.known then
					t.known = true
					log("~ add known artefact [%s], info [%s]", art, info)
					if art2child[art] then
						for i, v in ipairs( art2child[art] ) do
							artefacts[v].known = true
						end
					end
				end
			end
		end
	end
end
-----------------------------------------------------------------------------------------------
local trader2level = {
	["sidor"]		= { lvl = 7, pay = 0.20 },
	["barman"]		= { lvl = 7, pay = 0.15 },
	["sakharov"]	= { lvl = 7, pay = 0.10 },
	["scryaga"]		= { lvl = 5, pay = 0.22 },
	["sak"]			= { lvl = 6, pay = 0.12 },
	["doctor"]		= { lvl = 7, pay = 0.07 }
}

local phr_it = {
	{
		ask			= "Вот, смотри, вроде на артефакт похоже.",
		know		= "Да, это артефакт, называется %s. Доставай КПК и записывай описание.",
		dont_know	= "Похоже вроде... В первый раз такое вижу. Может, ещё что есть?"
	}, {
		ask			= "Вот, какую-то штуковину нашел, на булыжник похожа...",
		know		= "Эта штуковина называется %s. Давай свой КПК, скопирую тебе информацию по артефакту.",
		dont_know	= "Мда, занятная штуковина, но я не знаю, что это такое. Спроси у кого-нибудь другого, %s."
	}, {
		ask			= "Вот это, вроде как артефакт.",
		know		= "Да, это аномальное образование называют %s. Запиши себе, %s.",
		dont_know	= "Вроде, ага, только вот что за артефакт - мне неизвестно к сожалению."
	}, {
		ask			= "Глянь-ка на эту вещицу, не артефакт ли?",
		know		= "Артефакт. А зовут его %s. Добавил все данные о нём в твой КПК.",
		dont_know	= "А кто ж его знает, вроде похоже на артефакт. У кого-нибудь другого спроси, %s, я её впервые вижу..."
	}, {
		ask			= "А вот это, случаем, не артефакт?",
		know		= "Это %s, %s. Найдёшь ещё - приноси, дам хорошую цену. Не забудь записать описание, а тот так найдёшь ещё и выкинешь.",
		dont_know	= "Не знаю, %s, не встречал такого..."
	}, {
		ask			= "Вот такой арт видел когда-нибудь?",
		know		= "Конечно видел. Этот артефакт называется %s. Скопировал тебе инфу про него.",
		dont_know	= "Нет, %s, не видел. Интересная штуковина, покажи кому-нибудь другому, может, знают что-то про него."
	}
}

function init_known_art_dialog( dlg, trader )
	local p = "known_art_"..trader
	local actor_name = db.actor:character_name()

	local phr = dlg:AddPhrase( p.."_0", "0", "", -10000 )
	local phrase_script

	phr = dlg:AddPhrase( p.."_1", "1", "0", -10000 )
	phrase_script = phr:GetPhraseScript()
	phrase_script:AddHasInfo("art_hunter_about_pay_info")

	local pay = trader2level[trader].pay
	phr = dlg:AddPhrase( "Тут такое дело, "..actor_name..". Любая информация денег стоит, согласен? Много не возьму, "..
		string.format("%d", pay*100).."% от стоимости артефакта, по которому нужна информация. Согласен?", "11", "0", -10000 )
	phrase_script = phr:GetPhraseScript()
	phrase_script:AddDontHasInfo("art_hunter_about_pay_info")

	phr = dlg:AddPhrase( "known_art_pay_12", "12", "11", -10000 )

	phr = dlg:AddPhrase( "known_art_pay_13", "13", "12", -10000 )
	phrase_script = phr:GetPhraseScript()
	phrase_script:AddGiveInfo("art_hunter_about_pay_info")

	phr = dlg:AddPhrase( "known_art_pay_111", "111", "11", -10000 )
	phrase_script = phr:GetPhraseScript()
	phrase_script:AddAction("dialogs.break_dialog")

	local text = ""
	local translate = game.translate_string
	local lvl = trader2level[trader].lvl
	local f = false
	local phr_id
	for i, sect in ipairs(id2art) do
		local tt = table.random(phr_it)
		phr_id = tostring( 1000+i )
		phr = dlg:AddPhrase( tt.ask, phr_id, "1", -10000 )
		phrase_script = phr:GetPhraseScript()
		phrase_script:AddPrecondition("artefact_hunter.precondition_unknown_art")
		phrase_script:AddAction("artefact_hunter.show_art_icon")

		phr = dlg:AddPhrase( "", phr_id, "13", 0 )

		if lvl >= artefacts[sect].lvl then
			text = string.format( tt.know, translate( sys_ini:r_string( sect, "inv_name" ) ), actor_name )
			f = true
		else
			text = string.format( tt.dont_know, actor_name )
			f = false
		end
		phr = dlg:AddPhrase( text, tostring(2000+i), phr_id, -10000 )
		if f then
			phrase_script = phr:GetPhraseScript()
			phrase_script:AddAction("artefact_hunter.trader_add_art_info")
		end
	end

	phr = dlg:AddPhrase( p.."_2", "2", "1", -10000 )
	phr = dlg:AddPhrase( "",      "2", "13", 0 )
end

function show_art_icon(first_speaker, second_speaker, dialog_id, phrase_id)
	local art = id2art[ tonumber(phrase_id) - 1000 ]
	local icon = GetIconParams(art)
	db.actor:give_talk_message("", "ui\\ui_icon_equipment", Frect():set(icon.x, icon.y, icon.w, icon.h), "iconed_icon_item")
end
function precondition_unknown_art(first_speaker, second_speaker, dialog_id, prev_phrase_id, phrase_id)
	local art = id2art[ tonumber(phrase_id) - 1000 ]
	local obj = db.actor:object( art )
	if not obj then
		if art2child[art] then
			for i, v in ipairs( art2child[art] ) do
				obj = db.actor:object(v)
				if obj then break end
			end
		end
	end

	if obj then
		return artefacts[art].known == false
			and db.actor:money() >= obj:cost()*trader2level[ string.match(dialog_id, "^[^_]+") ].pay
	end

	return false
end

function trader_add_art_info(first_speaker, second_speaker, dialog_id, phrase_id)
	local art = id2art[ tonumber(phrase_id) - 2000 ]

	local cost = sys_ini:r_float(art, "cost")
	local pay = cost * trader2level[ string.match(dialog_id, "^[^_]+") ].pay
	dialogs.relocate_money(first_speaker, pay, "out")

	this.add_art_info(art)
end
	
function has_unknown_arts()
	local sect
	local res = false
	db.actor:iterate_inventory(function (dummy, item)
		sect = item:section()
		if artefacts[sect] and not artefacts[sect].known then
			res = true
		end
	end,
	nil)
	return res
end


function init_sidor_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "sidor" )
end
function init_barman_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "barman" )
end
function init_sakharov_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "sakharov" )
end
function init_scryaga_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "scryaga" )
end
function init_sak_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "sak" )
end
function init_doctor_known_art_dialog( dlg )
	init_known_art_dialog( dlg, "doctor" )
end

-----------------------------------------------------------------------------------------------
function attach()
	this.init()
	xr_s.subscribe("info", this.on_info)
	xr_s.subscribe("item_to_slot", this.on_slot)
	xr_s.subscribe("item_take", this.hit_by_art)
	xr_s.subscribe("first_update", this.first_update)
end
