-- -*- mode: lua; encoding: windows-1251 -*-
function ggg()
end

-- Всё перенесено в all.spawn
function repair()
end

function after_credits()
	-- не знаю, зачем это, но пусть будет
	if not db.gameover_credits_started then return end
	db.gameover_credits_started = nil

	if not has_alife_info("snp_rings_done") then
		get_console():execute("main_menu on")
		get_console():execute("disconnect")
		return
	end

	if not has_alife_info("naxac_freeplay_start") then
		db.actor:give_info_portion("naxac_freeplay_start")
		
		local not_del = {
			["bolt"] = true,
			["wpn_binoc"] = true,
			["device_pda"] = true,
			['netpacket_pda'] = true,
			["device_torch"] = true
		}
		local sim = alife()
		local obj
		db.actor:iterate_inventory(function(actor, item)
			obj = sim:object(item:id())
			if obj and not_del[item:section()] == nil then
				sim:release(obj, true)
			end
		end,
		db.actor)
		
		db.actor:give_money(1000-db.actor:money())
		
		level.disable_input()
		start_small_timer(2000, this.tele_to_escape)
	end
end
function tele_to_escape()
	u3_utils.savegame("Финал")
	start_small_timer(3000, function () spawn_level_changer.jumpTo("exit_ao2") end)
end

function treasure_sysh_spawn()
	local items = {
		['ammo_gauss'] = 1,
		['sysh_document'] = 1,
		['antirad'] = 4,
		['medkit_scientic'] = 2,
		['af_kol_4'] = 1
	}
	local hint = "%c[255,238,155,23]Тайник Сыча\\n%c[default]На флешке Сыча была информация о схроне в лаборатории X-10, надо бы его проверить."
	naxac_test.create_treasure( vector():set(-1.9939445257187,-34.253723144531,27.17742729187),
		4256, 2777, items, "treasure", hint)
end

function lc_question_add()
	-- Припять - ЧАЭС
	local obj = alife():object("exit_to_stancia_01")
	if obj then
		local t = { silent_mode = 0 }
		netpk:modify(obj, t, netpk.fState)
	end
end

function restore_anoms()
	if has_alife_info("snpt_vp1_have") then
		alife():create("zone_ozero",vector():set(58.848209381104,1.0079244375229,367.44982910156),276095,3760)
	end
	for i = 15606, 15618, 1 do
		alife():create(i)
	end
--	local t = {723,726,740,745,746,747,749,750,751,754,755,773}
--	for i,v in ipairs(t) do alife():create(v) end
end

function add_spot_lc()
	local obj = alife():story_object(130029)
	level.map_add_object_spot_ser(obj.id, "level_changer2", "В Восточную Припять")
end

function rewrite_restr_logic( obj_name, logic )
	local obj = alife():object( obj_name )
	if obj then
		local cd = logic and "[logic]\ncfg = "..logic or ""
		netpk:modify( obj, {custom_data =	cd}, netpk.fState )
		local rest = level.object_by_id( obj.id )
		if rest then
			local st = db.storage[rest:id()]
			st = {}
			xr_logic.initialize_obj( rest, st, false, db.actor, modules.stype_restrictor, (logic or "scripts\\dummy.ltx") )
		end
	end
end

function create_treasure( pos, lv, gv, items, mapspot, hint )
	local sim = alife()
	local ruck = sim:create( "m_inventory_box", pos, lv, gv )

	local id = ruck.id
	for sect, n in pairs(items) do
		for i = 1, n do
			sim:create(sect, pos, lv, gv, id)
		end
	end

	local t = netpk:get( ruck, netpk.fState )
	t.custom_data  = "[logic]\n".."cfg = scripts\\new_inventory_box.ltx"
	t.object_flags = bit_and( t.object_flags, bit_not(197) )
	netpk:set( ruck, t )

	if mapspot then
		level.map_add_object_spot_ser( id, mapspot, (hint or "Тайник") )
	end
end

