-- -*- mode: lua; encoding: windows-1251 -*-
----------------------------------------------------------------------------------------------------------------------
--	Выдача информации сталкерам.
--	автор: Диденко Руслан (Stohe)
--	TODO: 
----------------------------------------------------------------------------------------------------------------------
local function table_add(tbl, src)
	for i, v in ipairs(src) do
		tbl[#tbl+1] = v
	end
end

local info_by_community = {}
info_by_community.default = {	"encyclopedy_zone_artifact_af-medusa",
					"encyclopedy_zone_artifact_af-cristall-flower",
					"encyclopedy_zone_artifact_af-night-star",
					"encyclopedy_zone_artifact_af-vyvert",
					"encyclopedy_zone_artifact_af-gravi",
					"encyclopedy_zone_artifact_af-gold-fish",
					"encyclopedy_zone_artifact_af-blood",
					"encyclopedy_zone_artifact_af-mincer-meat",
					"encyclopedy_zone_artifact_af-soul",
					"encyclopedy_zone_artifact_af-drops",
					"encyclopedy_zone_artifact_af-fireball",
					"encyclopedy_zone_artifact_af-cristall",
					"encyclopedy_zone_artifact_af-electra-sparkler",
					"encyclopedy_zone_artifact_af-electra-flash",
					"encyclopedy_zone_artifact_af-electra-moonlight",
					"encyclopedy_zone_artifact_af-rusty-thorn",
					"encyclopedy_zone_artifact_af-rusty-kristall",
					"encyclopedy_zone_artifact_af-rusty-sea-urchin",
					"encyclopedy_zone_artifact_af-fuzz-kolobok",
					"encyclopedy_zone_artifact_af-ameba-slime",
					"encyclopedy_zone_artifact_af-ameba-slug",
					"encyclopedy_zone_artifact_af-ameba-mica",
					"encyclopedy_zone_artifact_af-dummy-glassbeads",
					"encyclopedy_zone_artifact_af-dummy-pellicle",
					"encyclopedy_zone_artifact_af-dummy-battery",
					"encyclopedy_zone_artifact_af-dummy-dummy",
					"encyclopedy_zone_artifact_af-dummy-spring",
					"encyclopedy_zone_zone-story_story-2006",
					"encyclopedy_zone_zone-story_story-2008",
					"encyclopedy_zone_zone-story_story-2010",
					"encyclopedy_zone_zone-story_story-raid",
					"encyclopedy_zone_anomalies_bald",
					"encyclopedy_zone_anomalies_gravi",
					"encyclopedy_zone_anomalies_meat",
					"encyclopedy_zone_anomalies_zharka",
					"encyclopedy_zone_anomalies_electra",
					"encyclopedy_zone_anomalies_fuzz",
					"encyclopedy_zone_anomalies_radioactive",
					"encyclopedy_zone_anomalies_ameba",
					-- new
					"encyclopedy_zone_anomalies_lift",
					"encyclopedy_zone_anomalies_monolit",
					"encyclopedy_zone_anomalies_zhar",
					"encyclopedy_zone_anomalies_smallrain",
					"encyclopedy_zone_anomalies_sphere",
					"encyclopedy_zone_anomalies_zavesa",
					"encyclopedy_zone_anomalies_fountain",
					"encyclopedy_zone_anomalies_xvatalka",
					"encyclopedy_zone_anomalies_zvezda",
					"encyclopedy_zone_anomalies_smoke",
					"encyclopedy_zone_anomalies_emi",
					"encyclopedy_zone_anomalies_smallrain1",
					"encyclopedy_zone_anomalies_pulsar",
					--<<
					"encyclopedy_zone_locations_escape",
					"encyclopedy_zone_locations_garbage",
					"encyclopedy_zone_locations_agroprom",
					"encyclopedy_zone_locations_darkdolina",
					"encyclopedy_zone_locations_bar",
					"encyclopedy_zone_locations_rostok",
					"encyclopedy_zone_locations_yantar",
					"encyclopedy_zone_locations_military-loc",
					"encyclopedy_zone_locations_radar",
					"encyclopedy_zone_locations_pripiat",
					"encyclopedy_zone_locations_stancia",
					"encyclopedy_mutant_crow_general",
					"encyclopedy_mutant_rat_general",
					"encyclopedy_mutant_flesh_general",
					"encyclopedy_mutant_blind_general",
					"encyclopedy_mutant_cat_general",
					"encyclopedy_mutant_tushkano",
					"encyclopedy_mutant_boar_general",
					"encyclopedy_mutant_pseudodog_general",
					"encyclopedy_mutant_bloodsucker_general",
					"encyclopedy_mutant_fracture_general",
					"encyclopedy_mutant_chimera_general",
					"encyclopedy_mutant_burer_general",
					"encyclopedy_mutant_zombie_general",
					"encyclopedy_mutant_zombieg_general",
					"encyclopedy_mutant_pseudogiant_general",
					"encyclopedy_mutant_poltergeist_general",
					"encyclopedy_mutant_controller_general",
					"encyclopedy_mutant_snork_general",
					-- new
					"encyclopedy_mutant_poltergeistp",
					"encyclopedy_mutant_krovosos_albinos",
					"encyclopedy_mutant_fracture_karlik",
					"encyclopedy_mutant_zanoza",
					"encyclopedy_mutant_molerat",
					"encyclopedy_mutant_vypolzen",
					"encyclopedy_mutant_vypolzen_red",
					"encyclopedy_mutant_monster_bear",
					"encyclopedy_mutant_chimera_new_wolf",
					"encyclopedy_mutant_chimera_new_electro",
					"encyclopedy_mutant_polter_flame",
					"encyclopedy_mutant_chimera_black",
					"encyclopedy_mutant_electro_chimera",
					"encyclopedy_mutant_chimera_red",
					"encyclopedy_mutant_chimera_white",
					"encyclopedy_mutant_fire_chimera",
					"encyclopedy_mutant_controller_flame",
					"encyclopedy_mutant_controller_electro",
					"encyclopedy_mutant_kontroler_act",
					"encyclopedy_mutant_kontroler_5",
					"encyclopedy_mutant_controller_babka",
					"encyclopedy_mutant_pseudodog_grey",
					"encyclopedy_mutant_karlito",
					"encyclopedy_mutant_zomb14",
					"encyclopedy_mutant_zomb13",
					"encyclopedy_mutant_dog_zombie",
					"encyclopedy_mutant_volkodav",
					"encyclopedy_mutant_snork_jumper",
					"encyclopedy_mutant_snork_stronger",
					"encyclopedy_mutant_rotan",
					"encyclopedy_mutant_poltergeist_dd",
					"encyclopedy_mutant_electro_polter",
					"encyclopedy_mutant_polter_xray",
					"encyclopedy_mutant_krovosos_zombie",
					"encyclopedy_mutant_flesh_swamp",
					"encyclopedy_mutant_bloodsucker_child",
					"encyclopedy_mutant_deathclaw",
					"encyclopedy_mutant_bibliotekar_black",
					"encyclopedy_mutant_burer_electro",
					"encyclopedy_mutant_tushkano_strong",
					"encyclopedy_mutant_new_hell",
					"encyclopedy_mutant_oboroten",
					"encyclopedy_mutant_spider",
					"encyclopedy_mutant_kikimora",
					"encyclopedy_mutant_vodyannoy",
					"encyclopedy_mutant_karlik",
					"encyclopedy_mutant_himera_prizrak",
					"encyclopedy_mutant_zombieg",
					"encyclopedy_mutant_black_dog",
					"encyclopedy_mutant_bibliotekar",
					"encyclopedy_mutant_tarakan",
					"encyclopedy_mutant_zombie_babka",
					"encyclopedy_mutant_zombie_skelet",
					--<<
					"encyclopedy_social_military_army",
					"encyclopedy_social_military_milstalkers",
					"encyclopedy_social_scientists_mobile-labs",
					"encyclopedy_social_stalker-clans_duty",
					"encyclopedy_social_stalker-clans_freedom",
					"encyclopedy_social_stalker-clans_monolith",
					"encyclopedy_social_stalker-clans_zomstalkers",
					"encyclopedy_social_stalker-clans_bandits",
					"encyclopedy_social_stalker-clans_killers",
					"encyclopedy_social_stalker-clans_loners" }

info_by_community.stalker = {
	"encyclopedy_zone_artifact_af-caterpillar",
	"stalker_story_10",
	"stalker_story_14"
}
table_add( info_by_community.stalker, info_by_community.default )

info_by_community.monolith = {
	"stalker_story_16",
	"stalker_story_17",
	"stalker_story_18",
	"stalker_story_19",
	"stalker_story_20",
	"stalker_story_21",
	"stalker_story_22",
	"stalker_story_23",
	"stalker_story_25",
	"stalker_story_26",
	"stalker_story_27",
	"stalker_story_28",
	"stalker_story_29"
}
table_add( info_by_community.monolith, info_by_community.default )

info_by_community.military = {
	"stalker_story_10",
	"stalker_story_24"
}
table_add( info_by_community.military, info_by_community.default )

info_by_community.killer = {
	"stalker_story_7"
}
table_add( info_by_community.killer, info_by_community.default )

info_by_community.ecolog = {
	"encyclopedy_zone_artifact_af-caterpillar"
}
table_add( info_by_community.ecolog, info_by_community.default )

info_by_community.dolg = {
	"stalker_story_2",
	"stalker_story_6",
	"stalker_story_10",
	"stalker_story_13"
}
table_add( info_by_community.dolg, info_by_community.default )

info_by_community.freedom = {
	"stalker_story_3",
	"stalker_story_9",
	"stalker_story_10"
}
table_add( info_by_community.freedom, info_by_community.default )

info_by_community.bandit = { "stalker_story_11" }
table_add( info_by_community.bandit, info_by_community.default )

local info_by_rank = {}
info_by_rank.novice = {	"encyclopedy_zone_artifact_af-medusa", 
					"encyclopedy_zone_artifact_af-cristall-flower", 
					"encyclopedy_zone_artifact_af-vyvert", 
					"encyclopedy_zone_artifact_af-gravi", 
					"encyclopedy_zone_artifact_af-blood", 
					"encyclopedy_zone_artifact_af-mincer-meat",
					"encyclopedy_zone_zone-story_story-2006",
					"encyclopedy_zone_anomalies_bald",
					"encyclopedy_zone_anomalies_gravi",
					"encyclopedy_zone_anomalies_meat",
					"encyclopedy_zone_anomalies_electra",
					"encyclopedy_zone_anomalies_radioactive",
					"encyclopedy_zone_anomalies_lift",
					"encyclopedy_zone_anomalies_zhar",
					"encyclopedy_zone_anomalies_smallrain",
					"encyclopedy_zone_anomalies_sphere",
					"encyclopedy_zone_anomalies_zavesa",
					"encyclopedy_zone_anomalies_fountain",
					"encyclopedy_zone_anomalies_xvatalka",
					"encyclopedy_zone_anomalies_pulsar",
					"encyclopedy_zone_locations_escape",
					"encyclopedy_zone_locations_garbage",
					"encyclopedy_mutant_crow_general",
					"encyclopedy_mutant_rat_general",
					"encyclopedy_mutant_flesh_general",
					"encyclopedy_mutant_blind_general",
					"encyclopedy_mutant_cat_general",
					"encyclopedy_mutant_boar_general",
					"encyclopedy_mutant_molerat",
					"encyclopedy_mutant_zomb14",
					"encyclopedy_mutant_zomb13",
					"encyclopedy_mutant_zombie_babka",
					"encyclopedy_social_military_army",
					"encyclopedy_social_stalker-clans_duty",
					"encyclopedy_social_stalker-clans_bandits" }

info_by_rank.stalker = {
					"encyclopedy_zone_artifact_af-night-star",
					"encyclopedy_zone_artifact_af-gold-fish",
					"encyclopedy_zone_artifact_af-soul",
					"encyclopedy_zone_zone-story_story-2008",
					"encyclopedy_zone_anomalies_fuzz",
					"encyclopedy_zone_anomalies_ameba",
					"encyclopedy_zone_anomalies_zvezda",
					"encyclopedy_zone_anomalies_smoke",
					"encyclopedy_zone_locations_agroprom",
					"encyclopedy_zone_locations_darkdolina",
					"encyclopedy_zone_locations_bar",
					"encyclopedy_zone_locations_rostok",
					"encyclopedy_mutant_tushkano",
					"encyclopedy_mutant_pseudodog_general",
					"encyclopedy_mutant_bloodsucker_general",
					"encyclopedy_mutant_burer_general",
					"encyclopedy_mutant_zombie_general",
					"encyclopedy_mutant_zombieg_general",
					"encyclopedy_mutant_fracture_general",
					"encyclopedy_mutant_chimera_general",
					"encyclopedy_mutant_snork_general",
					"encyclopedy_mutant_zanoza",
					"encyclopedy_mutant_electro_chimera",
					"encyclopedy_mutant_chimera_red",
					"encyclopedy_mutant_fire_chimera",
					"encyclopedy_mutant_karlito",
					"encyclopedy_mutant_dog_zombie",
					"encyclopedy_mutant_volkodav",
					"encyclopedy_mutant_snork_jumper",
					"encyclopedy_mutant_snork_stronger",
					"encyclopedy_mutant_krovosos_zombie",
					"encyclopedy_mutant_flesh_swamp",
					"encyclopedy_mutant_zombieg",
					"encyclopedy_mutant_karlik",
					"encyclopedy_mutant_tarakan",
					"encyclopedy_mutant_zombie_skelet",
					"encyclopedy_social_stalker-clans_freedom",
					"encyclopedy_social_stalker-clans_monolith",
					"encyclopedy_social_stalker-clans_killers",
					"encyclopedy_social_stalker-clans_zomstalkers",
					"encyclopedy_social_scientists_mobile-labs",
					"stalker_story_2",
					"stalker_story_3",
					"stalker_story_7",
					"stalker_story_11",
					"stalker_story_12",
					"stalker_story_16",
					"stalker_story_17",
					"stalker_story_18",
					"stalker_story_19",
					"stalker_story_20" }
table_add( info_by_rank.stalker, info_by_rank.novice )

info_by_rank.veteran = {
					"encyclopedy_zone_artifact_af-rusty-thorn",
					"encyclopedy_zone_artifact_af-rusty-kristall",
					"encyclopedy_zone_artifact_af-electra-sparkler",
					"encyclopedy_zone_artifact_af-electra-flash",
					"encyclopedy_zone_artifact_af-electra-moonlight",
					"encyclopedy_zone_artifact_af-ameba-slime",
					"encyclopedy_zone_artifact_af-ameba-slug",
					"encyclopedy_zone_zone-story_story-2010",
					"encyclopedy_zone_zone-story_story-raid",
					"encyclopedy_zone_anomalies_monolit",
					"encyclopedy_zone_anomalies_emi",
					"encyclopedy_zone_anomalies_smallrain1",
					"encyclopedy_zone_locations_military-loc",
					"encyclopedy_zone_locations_yantar",
					"encyclopedy_zone_locations_radar",
					"encyclopedy_mutant_pseudogiant_general",
					"encyclopedy_mutant_poltergeist_general",
					"encyclopedy_mutant_controller_general",
					"encyclopedy_mutant_poltergeistp",
					"encyclopedy_mutant_fracture_karlik",
					"encyclopedy_mutant_vypolzen",
					"encyclopedy_mutant_vypolzen_red",
					"encyclopedy_mutant_polter_flame",
					"encyclopedy_mutant_chimera_black",
					"encyclopedy_mutant_controller_flame",
					"encyclopedy_mutant_controller_electro",
					"encyclopedy_mutant_kontroler_act",
					"encyclopedy_mutant_kontroler_5",
					"encyclopedy_mutant_controller_babka",
					"encyclopedy_mutant_pseudodog_grey",
					"encyclopedy_mutant_bloodsucker_child",
					"encyclopedy_mutant_deathclaw",
					"encyclopedy_mutant_bibliotekar_black",
					"encyclopedy_mutant_burer_electro",
					"encyclopedy_mutant_tushkano_strong",
					"encyclopedy_social_stalker-clans_loners",
					"encyclopedy_social_military_milstalkers",
					"encyclopedy_mutant_kikimora",
					"encyclopedy_mutant_vodyannoy",
					"encyclopedy_mutant_himera_prizrak",
					"encyclopedy_mutant_black_dog",
					"stalker_story_10",
					"stalker_story_13",
					"stalker_story_14",
					"stalker_story_21",
					"stalker_story_22",
					"stalker_story_23",
					"stalker_story_24",
					"stalker_story_25",
					"stalker_story_26",
					"stalker_story_27",
					"stalker_story_28",
					"stalker_story_29" }
table_add( info_by_rank.veteran, info_by_rank.stalker )

info_by_rank.master = {
					"encyclopedy_zone_artifact_af-rusty-sea-urchin",
					"encyclopedy_zone_artifact_af-drops",
					"encyclopedy_zone_artifact_af-fireball",
					"encyclopedy_zone_artifact_af-cristall",
					"encyclopedy_mutant_krovosos_albinos",
					"encyclopedy_mutant_monster_bear",
					"encyclopedy_mutant_chimera_new_wolf",
					"encyclopedy_mutant_chimera_new_electro",
					"encyclopedy_mutant_chimera_white",
					"encyclopedy_mutant_rotan",
					"encyclopedy_mutant_poltergeist_dd",
					"encyclopedy_mutant_electro_polter",
					"encyclopedy_mutant_polter_xray",
					"encyclopedy_mutant_new_hell",
					"encyclopedy_mutant_oboroten",
					"encyclopedy_mutant_spider",
					"encyclopedy_mutant_bibliotekar",
					"encyclopedy_zone_locations_pripiat",
					"encyclopedy_zone_locations_stancia",
					"stalker_story_6",
					"stalker_story_9" }
table_add( info_by_rank.master, info_by_rank.veteran )

info_by_rank.legend = {}
table_add( info_by_rank.legend, info_by_rank.master )

function loadInfo(npc, char_ini)
	local se_obj = alife():object(npc:id())
	if se_obj==nil or se_obj.treasure_processed == true then return end

	-- Загрузка из кастом даты
	if char_ini:section_exist("known_info") then
		local n = char_ini:line_count("known_info")
		local result, id, value = 0,"",""
	
		for i=0,n-1 do
			result, id, value = char_ini:r_line("known_info",i,"","")

			give_npc_info(npc, id)
		end
		return
	end
	
	
	-- Загрузка из генератора.
	local community_info = info_by_community[npc:character_community()] or info_by_community.default
	
	local rank = ranks.get_obj_rank_name(npc)
	local rank_info = info_by_rank[rank]
	if rank_info == nil then
		return
	end

	local tt = {}
	-- оставляем инфопоршны, которые есть и там и там.
	for k,v in pairs(community_info) do
		for kk,vv in pairs(rank_info) do
			if v == vv then
				-- Добавляем в список доступных знаний
				table.insert(tt, v)
				break
			end
		end	
	end
	
	-- одного вполне хватит - чтобы на подольше хватило
	if math.random(100) >= 90 then
		local ii = table.random(tt)
		give_npc_info(npc, ii)
	end
end

function give_npc_info(npc, info)
	-- Даем НПС инфопоршны
	npc:give_info_portion(info)

	-- Проверяем есть ли озвученная история на этот инфопоршн, и если есть
	-- добавляем ее тоже
	if sound_theme.theme[info] ~= nil then
		if db.story_by_id[npc:id()] == nil then
			db.story_by_id[npc:id()] = {}
		end
		
		table.insert(db.story_by_id[npc:id()], info)
	end
end

