-- -*- mode: lua; encoding: windows-1251 -*-
function get_item(obj)
	local obj_sect = obj:section()
	if string.find(obj_sect, "arc_diary_") then
		local n = obj_sect:sub(11)
		if not has_alife_info("kontroler_diary_info_"..n) then
			db.actor:give_info_portion("kontroler_diary_info_"..n)
		else
			amk.send_tip("Совсем не разобрать ничего, выкину-ка я лучше эту бумажку...", db.actor:character_name())
		end
		arc.remove_obj(obj:id())
	end
end
