-- -*- mode: lua; encoding: windows-1251 -*-
function show()
	if not db.debug then
	--	xr_effects.disable_ui()
		db.actor:hide_weapon()
		level.hide_indicators()
		level.add_pp_effector("deadcity_wake_old.ppe", 2001, false)
		game.start_tutorial("intro_dream")
	end
end

function on_stop()
	level.disable_input()
	xr_sound.get_safe_sound_object("ambient\\random\\rnd_respawn"):play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	xr_timers.start_real_timer("run", 3.5, "intro_dream.on_stop2()")
end
function on_stop2()
	level.remove_pp_effector (2001)
	level.add_pp_effector("deadcity_wake_old.ppe", 2001, false)
	xr_timers.start_real_timer("run", 3, "intro_dream.on_stop3()")
end
function on_stop3()
	level.add_cam_effector("camera_effects\\fatigue.anm", 3001, false, "intro_dream.on_stop4")
end
function on_stop4()
	xr_effects.enable_ui()
	amk.send_tip("%c[255,0,255,0]Обнаружен новый сталкер: Меченый. Добавлен в базу данных сети.%c[default]", "ЛОКАЛЬНАЯ СЕТЬ", 0, 15, "questman_death")
end