-- -*- mode: lua; encoding: windows-1251 -*-
local check_tbl = {}
-- level_tasks...
-- escape_tasks
check_tbl['af_blood_tutorial'] = function(item)
	if Actor:dont_has_info("tutorial_artefact_start")
		and Actor:dont_has_info("tutorial_artefact_gain")
	then
		Actor:give_info_portion("tutorial_artefact_gain")
	end
end
check_tbl['esc_wounded_flash'] = function(item)
	if Actor:dont_has_info("tutorial_wounded_give_info") then
		Actor:give_info_portion("tutorial_wounded_give_info")
		Actor:disable_info_portion("esc_trader_direct")
	end
end
check_tbl['quest_case_01'] = function(item)
	if Actor:has_info("escape_blockpost_case") and
		Actor:dont_has_info("escape_blockpost_case_have")
	then
		Actor:give_info_portion("escape_blockpost_case_have")
	end
end
-- agroprom_tasks
check_tbl['gunslinger_flash'] = function(item)
	Actor:give_info_portion("agr_find_ghost_start")
end
-- darkvalley_tasks
check_tbl['dar_document1'] = function(item)
	if Actor:dont_has_info("dar_document1") then
 		Actor:give_info_portion("dar_document1") 
	end
end
check_tbl['dar_document2'] = function(item)
	if Actor:dont_has_info("dar_document2") then
 		Actor:give_info_portion("dar_document2") 
	end
end
check_tbl['dar_document3'] = function(item)
	if Actor:dont_has_info("dar_document3") then
 		Actor:give_info_portion("dar_document3") 
	end
end
check_tbl['dar_document4'] = function(item)
	if Actor:dont_has_info("dar_document4") then
 		Actor:give_info_portion("dar_document4") 
	end
end
check_tbl['dar_document5'] = function(item)
	if Actor:dont_has_info("dar_document5") then
 		Actor:give_info_portion("dar_document5") 
	end
end
-- bar_rostok_tasks
check_tbl['bar_ecolog_flash'] = function(item)
	if not ( Actor:has_info("bar_ecolog_research_normal")
		or Actor:has_info("bar_ecolog_research_corrupted") )
	then
		if Actor:has_info("bar_rescue_research_corruped") then
			Actor:give_info_portion("bar_ecolog_research_corrupted")
		else
			Actor:give_info_portion("bar_ecolog_research_normal")
		end
	end
end
-- yantar_tasks
check_tbl['lab_x16_documents'] = function(item)
	if Actor:dont_has_info("yan_x16_documents_gain") then
		Actor:give_info_portion("yantar_find_ghost_task_end")
		Actor:give_info_portion("yan_x16_documents_gain")
		local npc = AI:story_object(story_ids.yan_ecolog_help)
		if npc then
			netpk:modify(npc, {visual_name = "new\\new_kruglov"})
		end
	end
end
-- pripyat_tasks
check_tbl['decoder'] = function(item)
	if Actor:dont_has_info("pri_monolith_decoder_got") then
		Actor:give_info_portion("pri_monolith_decoder_got")
	end
end
check_tbl['pri_decoder_documents'] = function(item)
	if Actor:dont_has_info("pri_decoder_docs_conclusion_info") then
		Actor:give_info_portion("pri_decoder_docs_conclusion_info")
	end
end


check_tbl['amk_af_night_star'] = function(item)
	if Actor:dont_has_info("test_quest_art_vziat") then
		Actor:give_info_portion("test_quest_art_vziat")
	end
end
check_tbl['amk_zapiska'] = function(item)
	local lname = level.name()
	if lname=="l03_agroprom" then
		sak.add_new_escape_100()
		del_obj_by_id( item:id() )
	elseif lname=="l01_escape" then
		Actor:give_info_portion("info_amk_recipt_shkura")
		del_obj_by_id( item:id() )
	elseif lname=="l04u_labx18" then
		Actor:give_info_portion("info_amk_recipt_simbion")
		del_obj_by_id( item:id() )
	elseif lname=="l08u_brainlab" then
		del_obj_by_id( item:id() )
		local infos = {
			"info_amk_recipt_dummy",
			"info_amk_recipt_dummy_fire",
			"info_amk_recipt_dummy_bright",
			"info_amk_recipt_dummy_moon",
			"info_amk_recipt_dummy_puding"
		}
		for i,inf in ipairs(infos) do
			if Actor:dont_has_info(inf) then
				Actor:give_info_portion(inf)
			end
		end
	end
end
check_tbl['rad_document6'] = function(item)
	local lname = level.name()
	if lname=="l10_radar" then
		sak.add_new_darkvalley_107()
		del_obj_by_id( item:id() )
	elseif lname=="l03_agroprom" then
		Actor:give_info_portion("info_artmod_rusty_thorn_buzz")
		del_obj_by_id( item:id() )
	elseif lname=="l01_escape" then
		Actor:give_info_portion("info_artmod_rusty_kristall_mincer")
		del_obj_by_id( item:id() )
	end
end
check_tbl['sak_document'] = function(item)
	if Actor:has_info("info_way106a") then
		del_obj_by_id( item:id() )
	end
end
check_tbl['snp_pda1'] = function ( obj )
	if Actor:has_info("snp_borov1_start") then return end
	Actor:give_info_portion("snp_borov1_start")
end
check_tbl['snp_pda2'] = function ( obj )
	if Actor:has_info("snpt_kordon1_have") then return end
	Actor:give_info_portion("snpt_kordon1_have")
end
check_tbl['snp_pda3'] = function ( obj )
	if Actor:dont_has_info("snp_almaz0") then 
		snp_spawn.suslov_marsh_sms2()
		Actor:give_info_portion("snp_almaz0")
	end
end
check_tbl['snp_pda4'] = function ( obj )
	if Actor:has_info("snpt_sd4_have") then return end
	Actor:give_info_portion("snpt_sd4_have")
end
check_tbl['snp_pda5'] = function ( obj )
	if Actor:dont_has_info("snpt_pp1_have2") then
		-- Прайм заболел
		local se_obj = snp.object_by_section_offline("bibliofrend_talk_zaton")
		if se_obj then
			AI:release(se_obj, true)
		end
		se_obj = snp.object_by_section_offline("bibliofrend_zaton")
		if se_obj then
			netpk:modify( se_obj,{ visual_name = "monsters\\bibliotekar\\bibliotekar_black" },netpk.fState )
		end
		local sobj = AI:create("bibliofrend_talk_black_zaton",vector():set(124.68988037109,-7.3328924179077,177.81799316406),1180494,3686)
		set_story_id(sobj, story_ids.bibliofrend_talk_black_zaton)
		Actor:give_info_portion("snpt_pp1_have2")
	end
end
check_tbl['snp_pda6'] = function ( obj )
	if Actor:dont_has_info("snp_semetskiy_pda_have") then 
		kostya_dialog.create_teleport("tele_limansk4",vector():set(-11.73425579071,-0.16019485890865,-141.75788879395),19162,2993)
		local text = format_text_pairs(
			game.translate_string("semetsky_trup_nashel"),
			{user_name = user_name()}
		)
		Actor:give_game_news(text, "ui\\ui_iconsTotal", Frect():set(498,47,83,47), 5000, 20000)
		xr_sound.get_safe_sound_object("device\\pda\\pda_tip"):play(Actor, 5, sound_object.s2d)
		Actor:give_info_portion("snp_semetskiy_pda_have")
	end
end
check_tbl['snp_pda7'] = function ( obj )
	if Actor:dont_has_info("snpt_2chaes2_done") then 
		local timeout = 5
		news_manager.send_tip("proper_aes2_sms", timeout, nil, 20000)
		timeout = timeout+8
		news_manager.send_tip("proper_aes2_sms1", timeout, nil, 20000)
		Actor:give_info_portion("snpt_2chaes2_done")
	end
end
check_tbl['snp_pda8'] = function ( obj )
	if Actor:dont_has_info("snpt_mg2_have2") then 
		local timeout = 5
		news_manager.send_tip("brodyaga_zakaz_done", timeout, nil, 20000)
		timeout = timeout+10
		news_manager.send_tip("brodyaga_zakaz_done1", timeout, nil, 20000)
		local se_obj = AI:create("brodaga_zaton",vector():set(122.5481262207,-7.3221473693848,185.99839782715),1176929,3686)
		set_story_id(se_obj, story_ids.brodaga_zaton)
		Actor:give_info_portion("snpt_mg2_have2")
	end
end
check_tbl['snp_pda9'] = function ( obj )
	if Actor:has_info("snpt_cp2_have") then return end
	Actor:give_info_portion("snpt_cp2_have")
end
check_tbl['snp_pda10'] = function ( obj )
	del_obj_by_id( obj:id() )
	kostya_dialog.create_teleport("snp_uagro1_tp1",Actor:position(),Actor:level_vertex_id(),Actor:game_vertex_id())
end
check_tbl['snp_pda11'] = function ( obj )
	del_obj_by_id( obj:id() )
	Actor:give_info_portion("emb17")
end
check_tbl['snp_pda12'] = function ( obj )
	del_obj_by_id( obj:id() )
	Actor:give_info_portion("embt_vp1_done")
end
check_tbl['snp_pda13'] = function ( obj )
	del_obj_by_id( obj:id() )
	news_manager.send_tip("fenrir_lezhka_false", nil, nil, 30000)
end
check_tbl['snp_pda14'] = function ( obj )
	if Actor:has_info("snpt_2chaes3_have") then return end
	Actor:give_info_portion("snpt_2chaes3_have")
end
check_tbl['snp_biopart4'] = function ( obj )
	amk.remove_item_from_inventory_by_name("snp_note30",Actor)
	Actor:give_info_portion("snpt_vp3_done")
	snp_spawn.n_inventory_box_vp6()
end
check_tbl['snp_almaz_note2'] = function ( obj )
	if Actor:dont_has_info("snp_almaz_note2") then
		amk.remove_item_from_inventory_by_name("snp_almaz_note1",Actor)
		AI:create_free("n_inventory_box_almaz3",vector():set(48.840072631836,2.2752776145935,-27.195747375488),162369,2137)
		Actor:give_info_portion("snp_almaz_note2")
	end
end
check_tbl['af_idol_monolita'] = function ( obj )
	if Actor:has_info("snp_almaz3") and Actor:dont_has_info("snp_almaz_done") then 
		xr_sound.get_safe_sound_object([[heart\5]]):stop()
	end
end
check_tbl['snp_note10'] = function ( obj )
	if Actor:dont_has_info("snp_note10_have") then 
		AI:create_free("n_inventory_box_kl1_2",vector():set(-199.62145996094,10.08634185791,-256.50994873047),868,3234)
		Actor:give_info_portion("snp_note10_have")
	end
end
check_tbl['snp_note13'] = function ( obj )
	if Actor:dont_has_info("snp_note13_have") then 
		amk.remove_item_from_inventory_by_name("snp_note12",Actor)
		AI:create_free("n_inventory_box_kl1",vector():set(-116.12890625,27.069087982178,17.880420684814),10076,3240)
		Actor:give_info_portion("snp_note13_have")
	end
end
check_tbl['snp_note20'] = function ( obj )
	if Actor:dont_has_info("snp_note20_have") then 
		AI:create_free("n_inventory_box_cp4_1",vector():set(47.505016326904,8.9497900009155,-104.69525146484),159188,2136)
		Actor:give_info_portion("snp_note20_have")
	end
end
check_tbl['snp_note24'] = function ( obj )
	if Actor:object("snp_note23") then
		amk.remove_item_from_inventory_by_name("snp_note23",Actor)
		del_obj_by_id( obj:id() )
		Actor:give_info_portion("emb0")
	end
end
check_tbl['snp_note23'] = function ( obj )
	if Actor:object("snp_note24") then
		del_obj_by_id( obj:id() )
		amk.remove_item_from_inventory_by_name("snp_note24",Actor)
		Actor:give_info_portion("emb0")
	end
end
check_tbl['snp_plan'] = function ( obj )
	if Actor:has_info("snpt_sd1_have") then return end
	Actor:give_info_portion("snpt_sd1_have")
end
check_tbl['snp_prime_maz_green'] = function ( obj )
	if Actor:has_info("snp_bibliofrend_black1_have1") then return end
	Actor:give_info_portion("snp_bibliofrend_black1_have1")
end
check_tbl['wpn_m4_m1'] = function ( obj )
	if Actor:has_info("snp_bioradar_parts5") and Actor:dont_has_info("snpt_2chaes1_done") then 
		Actor:give_info_portion("snpt_2chaes1_done")
		news_manager.send_tip("fenrir_after_death", 6, nil, 45000)
		start_real_timer("run", 55, "snp.fenrir_gone()")
	end
end
check_tbl['wpn_ognemet'] = function ( obj )
	if not (Actor:has_info("fli_have_3") or Actor:has_info("dimak_toolkit_done")) then
		obj:set_condition(0.01)
	end
end
check_tbl['wpn_vihlop'] = function ( obj )
	if not (Actor:has_info("bar_deactivate_radar_done") or Actor:has_info("izumrud_electra_done")) then
		obj:set_condition(0.01)
	end
end
check_tbl['wpn_vintorez'] = function ( obj )
	if Actor:dont_has_info("escape_meceniy_start") then
		obj:set_condition(0.01)
	end
end
check_tbl['wpn_fn2000_paratrooper'] = function ( obj )
	if Actor:dont_has_info("vasily_chertez_fn") then
		obj:set_condition(0.01)
	end
end
check_tbl['fake_wpn_topor'] = function ( obj )
	if Actor:has_info("krest_topor") then
		Actor:give_info_portion("krest_topor_done")
	end
end
check_tbl['ammo_gravi'] = function ( obj )
	del_obj_by_id( obj:id() )
end
check_tbl['af_sunlight'] = function ( obj )
	if Actor:dont_has_info("fli_done") then return end
	if Actor:has_info("info_amk_recipt_fake") and Actor:dont_has_info("info_amk_recipt_fake_done") then
		news_manager.send_tip("osvedomitel_about_sunlight", 7, nil, 40000)
		Actor:give_info_portion("info_amk_recipt_fake_done")
	end
end
check_tbl['letter'] = function ( obj )
	local sobj = AI:object(obj:id())
	if sobj then
		death_manager.give_letter_info(sobj)
		AI:release(sobj, true)
	end
end
check_tbl['ammo_rpo-a'] = function (item)
	del_obj_by_id( item:id() )
end
check_tbl['mushroom'] = function (item)
	if AI:object(item:id()) == nil then return end

	if not has_timer("mux") then
		start_game_timer("mux", 0, 1, 0)	-- проверяем мухоморы раз в игровой час
		remove_timer("mushroom")
		remove_timer("del_m")
	end
	local t = amk.load_table("mux")
	local id = item:id()
	if t[id] == nil then
		t[id] = amk.game_hours()
		amk.save_table("mux", t)
	end
end
check_tbl['case_nebo'] = function (item)
	xr_s.subscribe("update", arc_radiation.spawn_telepatic)
end
check_tbl["vodka"] = function(item)
	if Actor:dont_has_info("acv_vodka") and inventory.search("vodka", 300) then
		archievements.send_archievement("acv_vodka")
	end
end
-- braad_test
check_tbl['sysh_document'] = function(item)
	if level.name()~="l10u_bunker" then return end
	Actor:give_info_portion("treasure_sysh_have")
	del_obj_by_id( item:id() )
end
check_tbl['sysh_flash'] = function(item)
--	if level.name()~="marsh" then return end
	Actor:give_info_portion("treasure_sysh_start")
	del_obj_by_id( item:id() )
end
check_tbl['voen_document'] = function(item)
	if level.name()~="l01_escape" then return end
	AI:create("snp_kordon1",vector():set(-96.201904296875,-4.6710577011108,-17.629180908203),166215,73)
	Actor:give_info_portion("bandranen_pda_need")
	del_obj_by_id( item:id() )
end
check_tbl['pda_padlikova'] = function(item)
	if level.name()~="jupiter" then return end
	Actor:give_info_portion("jup_zat_info")
	del_obj_by_id( item:id() )
end
check_tbl['blocknot_saharova'] = function(item)
	if level.name()~="jupiter" then return end
	if Actor:dont_has_info("blocknot_saharova_have") then
		Actor:give_info_portion("blocknot_saharova_have") 
		buusty_dialog.upi_mercaushiy_sms2(Actor,obj)
	end
end
check_tbl['bandranen_pda'] = function(item)
	if level.name()~="l02_garbage" then return end
	Actor:give_info_portion("bandranen_pda_est")
	del_obj_by_id( item:id() )
end
check_tbl['fraer_pda'] = function(item)
	if Actor:has_info("bandranen_pda_est") then
		Actor:give_info_portion("prapor_talk_need")
		del_obj_by_id( item:id() )
	end
end
check_tbl['ara_flash'] = function(item)
	if level.name()~="l07_military" then return end
	Actor:give_info_portion("ara_pda_est")
	del_obj_by_id( item:id() )
end
check_tbl['disk_adren'] = function(item)
	if level.name()~="atp_for_test22" then return end
	Actor:give_info_portion("atp_banda_disk_spawn")
	local timeout = 0
	for i = 1, 9 do
		local obj = AI:object("atp_disk_bandit"..i)
		if obj and obj:alive() then
			local snd = xr_sound.get_safe_sound_object([[characters_voice\scenario\arhara_atp\band]]..i)
			snd:play_at_pos(Actor, obj.position, timeout, sound_object.s3d)
			timeout = timeout + snd:length()/1000 + 0.5
		end
	end
end
check_tbl['new_document_sniper'] = function(item)
	Actor:give_info_portion("rebyta_domoy")
end
check_tbl['forest_last_dead_listok'] = function(item)
	if Actor:has_info("forest_psu_perex") then return end
	Actor:give_info_portion("forest_psu_perex")
	arhara_dialog.superzhekan_sms1()
end
check_tbl['klenov_opisalovo'] = function(item)
	if Actor:has_info("posulku_poluchil") then return end
	Actor:give_info_portion("posulku_poluchil")
	arhara_dialog.kl_pos_est_sms()
end
check_tbl['korobka_sigars'] = function(item)
	Actor:give_info_portion("portal_lima_idu")
end
check_tbl['izomorf_kristal'] = function(item)
	if Actor:has_info("superzhekan_est") then return end
	Actor:give_info_portion("superzhekan_est")
	start_real_timer("run", math.random(120, 240), "arhara_dialog.forest_del_pistonu()")
	arhara_dialog.superzhekan_sms()
end
check_tbl['sniper_flash'] = function(item)
	Actor:give_info_portion("prizrak_zver_have")
end
check_tbl['iskra_listok'] = function(item)
	Actor:give_info_portion("tel_dcity_kanaliy")
end
check_tbl['mem_module'] = function(item)
	if Actor:has_info("perexody_otkryty") then return end
	Actor:give_info_portion("perexody_otkryty")
	Actor:give_info_portion("agro_tainik_norman_done")
	arhara_dialog.sms_k_normany1()
	start_real_timer("run", 7, "sak.add_new_dcity()")
	del_obj_by_id(item:id())
end
check_tbl['wa2000_izomorf'] = function(item)
	Actor:give_info_portion("snaiperka_est")
	del_obj_by_id( item:id() )
	--' получим снайперку Черномора
	AI:create("wpn_walther_wa2000", vector():set(0,0,0), 0, 0, 0)
	AI:create_free("chimera_x_ray",vector():set(11.763,0.031,-26.645),44985,1503)
	arhara_dialog.yntar_sms_k_molnii1()
end
check_tbl['5.45x39_izomorf'] = function(item)
	del_obj_by_id( item:id() )
end
check_tbl['5.45x39_izomorf_1'] = function(item)
	del_obj_by_id( item:id() )
end
check_tbl['7.62x54_izomorf'] = function(item)
	del_obj_by_id( item:id() )
end
check_tbl['9x39_izomorf'] = function(item)
	local se_obj = AI:story_object(story_ids.m_teleport_blok_ruchag)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("ruchag_tp_off", nil, nil, 15000)
	end
	if Actor:has_info("kod_vveden_verno") then
		Actor:give_info_portion("dell_blok_tele")
		se_obj = AI:object(item:id())
		if se_obj then AI:release(se_obj, true) end
	end
end
check_tbl['siv_pda'] = function(item)
	if Actor:has_info("ara_pda_est") then
		Actor:give_info_portion("sah_talk_need")
		del_obj_by_id( item:id() )
	end
end
-- akill
check_tbl['akill_mono_note'] = function(item)
	if Actor:dont_has_info("ohota_radar_have") then
		akill.checking_taken_item68(item)
	end
end
check_tbl['container_morkov'] = function(item)
	if Actor:dont_has_info("plov_spawn_container_xvatit") and Actor:object("container_ris") ~= nil then
		akill.checking_taken_item69(item)
	end
end
check_tbl['container_ris'] = function(item)
	if Actor:dont_has_info("plov_spawn_container_xvatit") and Actor:object("container_morkov") ~= nil then
		akill.checking_taken_item69(item)
	end
end
check_tbl['kuznec_note_code'] = function(item)
	if Actor:dont_has_info("taynik_kuznec_bonus") then
		akill.checking_taken_item70(item)
	end
end
check_tbl['secret_prikaz2'] = function(item)
	if Actor:dont_has_info("marsh_razvedchik_start") then
		akill.checking_taken_item71(item)
	end
end
check_tbl['leshyi_zapiska'] = function(item)
	if Actor:dont_has_info("privet_leshyi_have") then
		akill.checking_taken_item74(item)
	end
end
check_tbl['docs_x7'] = function(item)
	if Actor:dont_has_info("taynik_leshyi_start") then
		akill.checking_taken_item75(item)
	end
end
check_tbl['phantom_counter'] = function(item)
	if Actor:dont_has_info("mercenary_dogovor_find") then
		akill.checking_taken_item76(item)
	end
end
check_tbl['chertez_keis'] = function(item)
	if Actor:dont_has_info("keis_oruzeinik_find") then
		akill.checking_taken_item77(item)
	end
end
check_tbl['hostel_teleport'] = function(item)
	if Actor:dont_has_info("pda_zagadka_take") then
		akill.checking_taken_item78()
	end
end
check_tbl['wpn_addon_sil_hostel'] = function(item)
	if Actor:dont_has_info("pda_zagadka_done") then
		akill.checking_taken_item79(item)
	end
end
check_tbl['wpn_winch1887'] = function(item)
	if Actor:has_info("yurik_pomer_plan_have") and Actor:dont_has_info("obrez_den_spawn") then
		akill.checking_taken_item80(item)
	end
end
check_tbl['af_mayak'] = function(item)
	if Actor:dont_has_info("sherstuk_ammo_have") then
		akill.checking_taken_item81(item)
	end
end
check_tbl['wpn_soulcube'] = function(item)
	if Actor:dont_has_info("taynik_cube_have") then
		akill.checking_taken_item82(item)
	end
end
check_tbl['af_provoloka'] = function(item)
	if Actor:dont_has_info("volna_sak_battle") then
		akill.checking_taken_item83(item)
	end
end
check_tbl['golem_pda'] = function(item)
	if Actor:dont_has_info("taynik_golem_start") then
		akill.checking_taken_item84(item)
	end
end
check_tbl['wpn_fot'] = function(item)
	if Actor:dont_has_info("foto_ohota_start") then
		akill.checking_taken_item85(item)
	end
end
check_tbl['signal_box'] = function(item)
	if Actor:dont_has_info("hamster_kuznec4_have") then
		akill.checking_taken_item86(item)
	end
end
check_tbl['icona'] = function(item)
	if Actor:dont_has_info("volna_petrenko_have") then
		akill.checking_taken_item87(item)
	end
end
check_tbl['death_kogot'] = function(obj) chess.kogot_hit(obj) end
check_tbl['kostya_pda'] = function(obj)
	if Actor:dont_has_info("net_teleport1") then
		Actor:set_actor_position(vector():set(-81.920501708984,-1.1038855314255,158.09979248047))
		local snd_obj = xr_sound.get_safe_sound_object([[anomaly\teleport_work_2]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)	
		Actor:give_info_portion("net_teleport1")
	end
end
check_tbl['kostya_pda2'] = function(obj)
	if Actor:dont_has_info("net_teleport2") then
		AI:create_free("amk_zombied_1",vector():set(254.20483398438,-8.3238792419434,-132.53259277344),370220,404)
		AI:create_free("amk_zombied_1",vector():set(253.97369384766,-7.4467711448669,-114.99160766602),370238,405)
		AI:create_free("amk_zombied_1",vector():set(272.40216064453,-8.8167734146118,-134.11990356445),377619,405)
		AI:create_free("amk_zombied_1",vector():set(254.9602355957,-5.4880833625793,-159.25900268555),370505,403)
		AI:create_free("amk_zombied_1",vector():set(231.4001159668,-0.54640311002731,-152.03894042969),359940,404)
		AI:create_free("amk_zombied_1",vector():set(231.60418701172,-1.2352631092072,-158.4441986084),359931,404)
		AI:create_free("m_controller_normal",vector():set(149.56939697266,-1.0081800222397,-177.11776733398),305023,398)
		for i=5,11,1 do
			Actor:give_info_portion("xvatit_spawn"..tostring(i))
		end
		Actor:set_actor_position(vector():set(260.87951660156,-9.5469636917114,-127.85536193848))
		local snd_obj = xr_sound.get_safe_sound_object([[monsters\controller\controller_script_attack_0]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		Actor:give_info_portion("net_teleport2")
	end
end
check_tbl['kostya_pda3'] = function(obj)
	if Actor:dont_has_info("xvatit_restrictor1") then
		local custom = "[logic]\n"..
		"active = sr_idle\n"..
		"[sr_idle]\n"..
		"on_actor_inside = {+kostya_x18_taynik_have} nil %=spawn_krovosos3 =spawn_krovosos4 =spawn_krovosos5 =play_zvuk5%"
		netpk:create_restrictor(
			vector():set(-1.9785075187683,-10.817359924316,19.746885299683),2451,1144,
			custom, 2.5
		)

		custom = "[logic]\n"..
		"active = sr_idle\n"..
		"[sr_idle]\n"..
		"on_actor_inside = {+kostya_x18_taynik_have} nil %=spawn_krovosos6%"
		netpk:create_restrictor(
			vector():set(-0.45858502388,-10.817345619202,-8.19189453125),2676,1134,
			custom, 2.0
		)

		Actor:give_info_portion("xvatit_restrictor1")
		Actor:give_info_portion("xvatit_restrictor2")
	end
end
check_tbl['kostya_pda4'] = function(obj)
	if Actor:dont_has_info("net_teleport4") then
		local custom = "[logic]\n"..
		"active = sr_idle\n"..
		"[sr_idle]\n"..
		"on_actor_inside = {+kostya_yantar_taynik_have} nil %=spawn_teleport31 =spawn_teleport32 =spawn_teleport33 =spawn_teleport34 =spawn_controller =create_sr13%"
		netpk:create_restrictor(
			vector():set(70.543083190918,0.079399138689041,53.515247344971),23064,1527,
			custom, 2.0
		)
		
		Actor:set_actor_position(vector():set(70.543083190918,0.079399138689041,53.515247344971))
		local snd_obj = xr_sound.get_safe_sound_object([[monsters\controller\controller_script_attack_0]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)	
		Actor:give_info_portion("net_teleport4")
		Actor:give_info_portion("xvatit_restrictor3")
	end
end
check_tbl['kostya_pda5'] = function(obj)
	if Actor:dont_has_info("spawn_teleport10") then
		local se_obj = AI:create("m_teleport_10",vector():set(169.78086853027,0.31017819046974,9.5852699279785),392313,584)
		set_story_id( se_obj, story_ids.m_teleport_10 )
		
		se_obj = AI:create("m_teleport_11",vector():set(136.20008850098,4.5723099708557,81.575187683105),369460,572)
		set_story_id( se_obj, story_ids.m_teleport_11 )
		
		Actor:set_actor_position(vector():set(96.954963684082,11.138046264648,191.75315856934))
		Actor:give_info_portion("net_teleport3")
		Actor:give_info_portion("spawn_teleport11")
		Actor:give_info_portion("spawn_teleport10")	
	end
end
check_tbl['kostya_pda6'] = function(obj)
	if Actor:dont_has_info("net_teleport5") then
		AI:create_free("chimera_strong",vector():set(-65.421890258789,-19.060049057007,377.33801269531),246698,1817)
		AI:create_free("chimera_strong",vector():set(-50.651332855225,-20.378976821899,364.74450683594),259563,1816)
		AI:create_free("chimera_strong",vector():set(-79.428909301758,-8.5947561264038,406.9296875),234287,1819)
		AI:create_free("chimera_strong",vector():set(-109.01066589355,-8.2724256515503,332.88485717773),206883,1781)
		Actor:give_info_portion("xvatit_spawn")
		for i=2,4,1 do
			Actor:give_info_portion("xvatit_spawn"..tostring(i))
		end
		
		Actor:set_actor_position(vector():set(-32.972778320313,-20.872562408447,379.255859375))
		Actor:give_info_portion("net_teleport5")
	end
end
check_tbl['kostya_pda7'] = function(obj)
	if Actor:dont_has_info("net_teleport7") then
		AI:create_free("amk_zombied_3",vector():set(430.32708740234,-55.344638824463,-265.75057983398),139238,2106)
		AI:create_free("amk_zombied_3",vector():set(425.45275878906,-55.518825531006,-260.28137207031),136989,2106)
		AI:create_free("amk_zombied_3",vector():set(416.34649658203,-54.163269042969,-257.17822265625),132416,2107)
		AI:create_free("amk_zombied_3",vector():set(393.51791381836,-53.055084228516,-245.65386962891),120402,2103)
		AI:create_free("amk_zombied_3",vector():set(406.46032714844,-51.854610443115,-248.01622009277),127927,2107)
		AI:create_free("amk_zombied_3",vector():set(414.01202392578,-53.197456359863,-252.00633239746),131137,2107)
		AI:create_free("m_controller_normal",vector():set(301.19879150391,-48.37797164917,-167.68395996094),66121,2084)

		for i=12,18,1 do
			Actor:give_info_portion("xvatit_spawn"..tostring(i))
		end

		Actor:set_actor_position(vector():set(412.39315795898,-53.103622436523,-274.568359375))
		Actor:give_info_portion("net_teleport7")
		
		local h = hit()
		h.power = 2.5
		h.direction = vector_rotate_y(Actor:direction(), 90) 
		h.draftsman = Actor
		h.impulse = 100
		h.type = hit.wound
		Actor:hit(h) 
		Actor:give_info_portion("polet")
	end
end
check_tbl['kostya_pda9'] = function(obj)
	if Actor:dont_has_info("net_teleport6") then
		AI:create_free("m_inventory_box12",vector():set(7.7449460029602,-22.623861312866,7.6079015731812),7689,2703)
		Actor:set_actor_position(vector():set(-18.487854003906,-23.518999099731,-20.886423110962))
		Actor:give_info_portion("net_teleport6")
		Actor:give_info_portion("new_inventory12")
	end
end
check_tbl['kostya_documents'] = function(obj)
	if Actor:dont_has_info("spawn_teleport25") then
		AI:create_free("m_inventory_box13",vector():set(-295.2509765625,25.836132049561,-119.17073059082),42457,303)
		
		local se_obj = AI:create("m_teleport_25",vector():set(106.70268249512,1.1635737419128,-137.5118560791),252367,397)
		set_story_id( se_obj, story_ids.m_teleport_25 )

		Actor:give_info_portion("spawn_teleport25")
		Actor:give_info_portion("kostya_documents_have")
	end
end
check_tbl['item_delete1'] = function(obj)
	local se_obj = AI:story_object(story_ids.m_teleport_5)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("teleport_udalen", nil, nil, 20000)
	end
	local obj_id = xr_logic.pstor_retrieve(Actor, "m_teleport_27", -1, true)
	se_obj = AI:object(obj_id)
	if se_obj then AI:release(se_obj, true) end
	del_obj_by_id( obj:id() )
	Actor:give_info_portion("dont_forget_pda")
end

check_tbl['tisku_arhara'] = function(obj)
	if Actor:dont_has_info("xvatit_spawn19") then
		AI:create_free("gigant_normal",vector():set(91.44384765625,-7.7290263175964,-268.84085083008),510295,2824)
		AI:create_free("gigant_normal",vector():set(131.46574401855,-6.2588143348694,-276.92578125),566209,2824)
		AI:create_free("gigant_normal",vector():set(139.18276977539,-5.9207892417908,-318.28570556641),576832,2831)
		AI:create_free("gigant_strong",vector():set(116.39553833008,-5.0737051963806,-335.06665039063),544441,2831)
		AI:create_free("gigant_strong",vector():set(81.120567321777,-5.243540763855,-330.37979125977),494313,2821)
		AI:create_free("gigant_strong",vector():set(74.439407348633,-6.2116746902466,-305.9533996582),485390,2821)
		Actor:give_info_portion("xvatit_spawn19")
	end
end
check_tbl['doc_medal'] = function(obj)
	if Actor:dont_has_info("xvatit_spawn20") then
		AI:create("tank_spawn_zasada",vector():set(102.07215118408,-0.56886887550354,219.97409057617),213216,2163)
		AI:create("monolith_x8_veteran",vector():set(105.6082611084,-0.62651246786118,250.9222869873),216911,2163)
		AI:create("monolith_x8_master",vector():set(117.33411407471,-0.67893779277802,201.55955505371),226710,2163)
		AI:create("tank_spawn_zasada1",vector():set(119.12321472168,3.9994158744812,134.80612182617),227513,2173)
		AI:create("tank_spawn_zasada2",vector():set(160.26086425781,3.9999127388,134.02439880371),249359,2176)
		AI:create("monolith_x8_regular",vector():set(108.85919952393,-0.00026518106460571,156.55084228516),220359,2185)
		AI:create("tank_x003",vector():set(101.38366699219,-0.62753546237946,230.4598236084),212554,2163)
		AI:create("monolith_x8_veteran",vector():set(-36.925113677979,-1.6531541347504,49.351211547852),61567,2165)
		AI:create("monolith_x8_master",vector():set(-61.738639831543,-2.3914077281952,65.415672302246),40534,2165)
		Actor:give_info_portion("xvatit_spawn20") 
	end
end
check_tbl['book_xabarych'] = function(obj)
	if Actor:dont_has_info("xvatit_spawn21") then 
		AI:create_free("esc_soldier_respawn_1",vector():set(-215.29968261719,0.81873428821564,-205.69987487793),17147,2882)
		AI:create_free("esc_soldier_respawn_1",vector():set(-215.29968261719,0.81873428821564,-205.69987487793),17147,2882)
		AI:create_free("esc_soldier_respawn_1",vector():set(-215.29968261719,0.81873428821564,-205.69987487793),17147,2882)
		AI:create_free("esc_soldier_respawn_1",vector():set(-190.48176574707,3.8373117446899,-205.54972839355),36394,2882)
		AI:create_free("esc_soldier_respawn_1",vector():set(-190.48176574707,3.8373117446899,-205.54972839355),36394,2882)
		AI:create_free("esc_soldier_respawn_1",vector():set(-190.48176574707,3.8373117446899,-205.54972839355),36394,2882)
		AI:create_free("agr_soldier_veteran",vector():set(-204.25308227539,0.37479916214943,-224.04116821289),25484,2882)
		AI:create_free("agr_soldier_veteran",vector():set(-204.25308227539,0.37479916214943,-224.04116821289),25484,2882)
		Actor:give_info_portion("xvatit_spawn21") 
	end
end
check_tbl['3d_raziy'] = function(obj)
	if Actor:dont_has_info("xvatit_spawn22") then
		AI:create_free("bloodsucker_strong",vector():set(-296.89874267578,-22.190504074097,286.92123413086),45801,1833)
		AI:create_free("mil_killer_respawn_1",vector():set(-279.85797119141,-22.178747177124,295.20132446289),60066,1832)
		AI:create_free("mil_killer_respawn_2",vector():set(-279.85797119141,-22.178747177124,295.20132446289),60066,1832)
		AI:create_free("mil_killer_respawn_3",vector():set(-279.85797119141,-22.178747177124,295.20132446289),60066,1832)
		AI:create_free("mil_killer_respawn_4",vector():set(-278.49209594727,-22.509449005127,271.50329589844),61170,1832)
		Actor:give_info_portion("xvatit_spawn22")
	end
end
check_tbl['pribor'] = function(obj)
	if Actor:dont_has_info("xvatit_spawn23") then
		news_manager.send_tip("borov_dyra_v_zabore", 3, nil, 15000)
		AI:create_free("volkodav",vector():set(26.224334716797,0.12501075863838,-44.189655303955),206039,1045)
		AI:create_free("volkodav",vector():set(21.418594360352,0.089109361171722,-55.710716247559),200730,1044)
		AI:create_free("volkodav",vector():set(4.0548872947693,0.079111576080322,-58.98025894165),179031,1037)
		AI:create_free("volkodav",vector():set(1.9367613792419,0.080904215574265,-87.617774963379),176461,1035)
		AI:create_free("volkodav",vector():set(29.398971557617,0.062291234731674,-95.921005249023),210251,1039)
		Actor:give_info_portion("xvatit_spawn23")
	end
end
check_tbl['video_kasseta'] = function(obj)
	local se_obj = AI:story_object(story_ids.dt_zone_zvuk_restrictor)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("found_videokasseta", nil, nil, 20000)
	end
end
check_tbl['amul_naemn'] = function(obj)
	if Actor:dont_has_info("pechatka_taken") then
		Actor:set_character_community("killer", 0, 0)
		relation_registry.set_community_goodwill ("killer", Actor:id(), 500)
		Actor:give_info_portion("pechatka_taken")
		news_manager.send_tip("sms_change_name_pili", 7, nil, 15000, nil, "arhara_dialog.pechatka_hero_rename()", 4)
	end
end
check_tbl['kluch_dell_teleport'] = function(obj)
	local se_obj = AI:story_object(story_ids.m_teleport_aver_baza_vxod)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("delete_teleport_baza_vxod", nil, nil, 15000)
	end
end
check_tbl['kluch_dell_teleport1'] = function(obj)
	local se_obj = AI:story_object(story_ids.m_teleport_land_baza_vuxod)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("delete_teleport_baza_vuxod", nil, nil, 15000)
	end
end
check_tbl['kluch_dell_teleport2'] = function(obj)
	news_manager.send_tip("sms_otkl_teleport", nil, nil, 15000)
	del_obj_by_id( obj:id() )
end
check_tbl['kluch_dell_teleport_warlab'] = function(obj)
	local se_obj = AI:story_object(story_ids.m_teleport_warlab_sekret)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("del_teleport_varlab_sekret", 3)
	end
	del_obj_by_id( obj:id() )
end
check_tbl['wpn_pkm_m1'] = function(obj)
	del_obj_by_id( obj:id() )
    amk.spawn_item_in_inv("wpn_pkm")
end
check_tbl['bullion_gild'] = function(obj)
	if Actor:has_info("snp_rings_have") and level.name()~="l05_bar" then
		Actor:set_character_community ("freedom", 0, 0)
	end
end
check_tbl['mini_antenna1'] = function(obj)
	local se_obj = AI:story_object(story_ids.generators_zone_emi1)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("zone_deactivate_sms")
	end
end
check_tbl['mini_antenna2'] = function(obj)
	local se_obj = AI:story_object(story_ids.generators_zone_emi2)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("zone_deactivate_sms")
	end
end
check_tbl['mini_antenna3'] = function(obj)
	local se_obj = AI:story_object(story_ids.generators_zone_emi3)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("zone_deactivate_sms")
	end
end
check_tbl['mini_antenna4'] = function(obj)
	local se_obj = AI:story_object(story_ids.generators_zone_emi4)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("zone_deactivate_sms")
	end
end
check_tbl['mini_antenna5'] = function(obj)
	local se_obj = AI:story_object(story_ids.generators_zone_emi5)
	if se_obj then
		AI:release(se_obj, true)
		news_manager.send_tip("zone_deactivate_sms")
	end
end
check_tbl['kaktus_izomorf'] = function(obj)
	if Actor:dont_has_info("xvatit_uzhe") then
		Actor:set_character_community("stranger", 0, 0)
		relation_registry.set_community_goodwill ("zombied", Actor:id(), 5000)
		Actor:give_info_portion("xvatit_uzhe")
	end
end
check_tbl['streyndzher'] = function(obj)
--	printf ("ACTOR NOW IN stranger COMMUNITY")
	Actor:set_character_community ("stranger", 0, 0)
end
check_tbl['val_zapis_1'] = function(obj)
	if Actor:dont_has_info("coll_tele1_on") then
		valerich_treasures.spawn_next(1)
	end
end
check_tbl['bitvakl_pda'] = function(obj)
	if Actor:dont_has_info("bitvakl_xvatit_spawn") then 
		Actor:give_info_portion("bitvakl_xvatit_spawn")
		-- Звуковое сопровождение
		local snd_obj = xr_sound.get_safe_sound_object([[monsters\controller\controller_script_attack_0]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		
		del_obj_by_id( obj:id() )
		
		braad_test.bitvakl_spawn()
		spawn_restrictor.bitvakl_sr1()
	end
end
check_tbl['anom_egg'] = function(obj)
	if Actor:dont_has_info("taynik_nayti_oz_10_prehave") then
		local txt = volazar_tbl_text["text"]()
		volazar_tbl_text.tips(txt.o.jup_1, 3, 20000)
		Actor:give_info_portion("taynik_nayti_oz_10_prehave")
	end
end
check_tbl['nano_screw'] = function(obj)
	if Actor:has_info("vol_pizdec_tvoritsya") then return end
	if Actor:object("nano_rosin") then
		Actor:give_info_portion("vol_pizdec_tvoritsya")
	end
end
check_tbl['nano_rosin'] = function(obj)
	if Actor:has_info("vol_pizdec_tvoritsya") then return end
	if Actor:object("nano_screw") then
		Actor:give_info_portion("vol_pizdec_tvoritsya")
	end
end

check_tbl['strelok_taynik_pda1'] = function(obj)
	if Actor:has_info("strelok_taynik_pda1_found") then 
		if Actor:dont_has_info("strelok_taynik_stop") then 
			Actor:give_info_portion("strelok_taynik_pda1_have")
			if Actor:dont_has_info("strelok_taynik_pda1_xvatit_spawn") then 
				AI:create_free("s_inventory_box1_2",vector():set(176.28475952148,17.963838577271,40.265209197998),256932,2145)
				AI:create_free("m_controller_normal",vector():set(87.854019165039,-2.5235424041748,86.012077331543),199525,2143) 
				AI:create_free("m_controller_normal_fat",vector():set(87.854019165039,-2.5235424041748,86.012077331543),199525,2143) 
				AI:create_free("m_controller_old",vector():set(160.51348876953,-2.2140634059906,89.546524047852),249284,2177)		
				AI:create_free("m_controller_old_fat",vector():set(160.51348876953,-2.2140634059906,89.546524047852),249284,2177)		
				xr_effects.play_zvuk3()
				Actor:give_info_portion("strelok_taynik_pda1_xvatit_spawn")
			end
		end
	else
		Actor:give_info_portion("strelok_taynik_stop")
	end
end
check_tbl['strelok_taynik_pda1_2'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_pda1_done") then 
		news_manager.send_tip("strelok_taynik_pda1_2_sms", nil, nil, 30000)
		-- Звуковое сопровождение
		local snd_obj = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		kostya_dialog.spawn_s_teleport1_2()
		spawn_restrictor.strelok_taynik_pda1_3_1_sr1()
	end
	del_obj_by_id( obj:id() )
end
check_tbl['strelok_taynik_pda1_3'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_pda1_done") then 
		news_manager.send_tip("strelok_taynik_pda1_3_sms", nil, nil, 30000)
		-- Звуковое сопровождение
		local snd_obj = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		spawn_restrictor.strelok_taynik_pda1_3_2_sr1()
	end
	del_obj_by_id( obj:id() )
end
check_tbl['strelok_taynik_pda1_4'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_pda1_done") then 
		news_manager.send_tip("strelok_taynik_pda1_4_sms", nil, nil, 30000)
		-- Звуковое сопровождение
		local snd_obj = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		kostya_dialog.spawn_s_teleport1_4()
		spawn_restrictor.strelok_taynik_pda1_4_sr1()
	end
	del_obj_by_id( obj:id() )
end
check_tbl['strelok_taynik_pda1_5'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_pda1_done") then 
		news_manager.send_tip("strelok_taynik_pda1_5_sms", nil, nil, 30000)
		braad_test.kor_bar_pri()
		kostya_dialog.delete_teleport("s_teleport1_1")
		kostya_dialog.delete_teleport("s_teleport1_3_1")
		kostya_dialog.delete_teleport("s_teleport1_3_2")
		kostya_dialog.delete_teleport("s_teleport1_4")
	end
	del_obj_by_id( obj:id() )
end
check_tbl['strelok_taynik_pda2_1'] = function(obj)
	if Actor:object("strelok_taynik_pda2_2") and Actor:dont_has_info("strelok_taynik_stop") then
		Actor:give_info_portion("strelok_taynik_pda2_have")
	end
end
check_tbl['strelok_taynik_pda2_2'] = function(obj)
	if Actor:object("strelok_taynik_pda2_1") and Actor:dont_has_info("strelok_taynik_stop") then
		Actor:give_info_portion("strelok_taynik_pda2_have")
	end
end
check_tbl['strelok_taynik_pda30'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_stop") then 
		Actor:give_info_portion("strelok_taynik_pda30_have")
	end
end
check_tbl['strelok_taynik_pda3'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_stop") then 
		if Actor:dont_has_info("strelok_taynik_pda3_have") then 
			AI:create_free("s_inventory_box3_1",vector():set(-99.41,1.37,-171.46),12046,3241)
			AI:create_free("s_inventory_box3_2",vector():set(-155.51449584961,-4.6265954971313,-262.34503173828),5644,3238)
			kostya_dialog.spawn_s_teleport3_2()
			Actor:give_info_portion("strelok_taynik_pda3_have")
		end
	end
end
check_tbl['strelok_taynik_pda3_1'] = function(obj)
	if Actor:object("strelok_taynik_pda3_2") and Actor:dont_has_info("strelok_taynik_stop") then
		if Actor:dont_has_info("strelok_taynik_pda3_12_have") then 
			AI:create_free("s_inventory_box3_3",vector():set(73.26683807373,1.484278678894,241.13470458984),29207,1244)
			Actor:give_info_portion("strelok_taynik_pda3_12_have")
		end
	end
end
check_tbl['strelok_taynik_pda3_2'] = function(obj)
	if Actor:object("strelok_taynik_pda3_1") and Actor:dont_has_info("strelok_taynik_stop") then
		if Actor:dont_has_info("strelok_taynik_pda3_12_have") then 
			AI:create_free("s_inventory_box3_3",vector():set(73.26683807373,1.484278678894,241.13470458984),29207,1244)
			Actor:give_info_portion("strelok_taynik_pda3_12_have")
		end
	end
end
check_tbl['strelok_taynik_pda3_3'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_stop") then 
		if Actor:dont_has_info("strelok_taynik_pda3_3_have") then 
			kostya_dialog.strelok_taynik_pda3_drop()
			Actor:give_info_portion("strelok_taynik_pda3_3_have")
		end
	end
end
check_tbl['strelok_taynik_pda4'] = function(obj)
	if Actor:has_info("strelok_taynik_pda4_found") then 
		if Actor:dont_has_info("strelok_taynik_stop") then 
			if Actor:dont_has_info("strelok_taynik_pda4_have") then 
				kostya_dialog.delete_s_teleport4_1()
				Actor:give_info_portion("strelok_taynik_pda4_have")
			end
		end
	else
		Actor:give_info_portion("strelok_taynik_stop")
	end
end
check_tbl['strelok_taynik_pda5'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_stop") then 
		Actor:give_info_portion("strelok_taynik_pda5_have")
	end
end
check_tbl['strelok_taynik_pda6'] = function(obj)
    if Actor:dont_has_info("strelok_taynik_stop") then 
		Actor:give_info_portion("strelok_taynik_pda6_have")
		if Actor:dont_has_info("strelok_taynik_pda6_xvatit_spawn") then 
			AI:create_free("bloodsucker_strong",vector():set(-194.36819458008,49.02271270752,-535.56390380859),112200,3082)
			AI:create_free("bloodsucker_normal",vector():set(-189.69694519043,47.406341552734,-548.29016113281),117716,3082)
			AI:create_free("bloodsucker_normal",vector():set(-174.30001831055,49.662406921387,-521.21356201172),135088,3089)
			AI:create_free("bloodsucker_normal",vector():set(-170.43768310547,46.646286010742,-550.90631103516),139967,3088)
			xr_effects.play_zvuk3()
			Actor:give_info_portion("strelok_taynik_pda6_xvatit_spawn")
		end
	end
end
check_tbl['strelok_taynik_pda7'] = function(obj)
	if Actor:has_info("strelok_taynik_pda7_found") then 
		if Actor:dont_has_info("strelok_taynik_stop") then 
			if Actor:has_info("strelok_taynik_pda0_done") then 
				news_manager.send_tip("strelok_taynik_pda7_sms1", nil, nil, 50000)
			else
				news_manager.send_tip("strelok_taynik_pda7_sms", nil, nil, 50000)
			end
			Actor:give_info_portion("strelok_taynik_pda7_done")
		end
	else
		Actor:give_info_portion("strelok_taynik_stop")
	end
	if Actor:has_info("strelok_taynik_pda0_done") then 
		bind_mteleport.del_teleport("s_teleport0_1")
	end
	del_obj_by_id( obj:id() )
end
check_tbl['strelok_taynik_pda0'] = function(obj)
	if Actor:dont_has_info("strelok_taynik_stop") then 
		news_manager.send_tip("strelok_taynik_pda0_sms", nil, nil, 30000)
		-- Звуковое сопровождение
		local snd_obj = xr_sound.get_safe_sound_object([[device\pda\pda_tip]])
		snd_obj:play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
		
		kostya_dialog.spawn_s_teleport0_1()
		Actor:give_info_portion("strelok_taynik_pda0_done")
		AI:create_free("amk_kanistra",vector():set(30.90,7.33,-39.75),210337,1045)
		spawn_restrictor.stdt1_sr1()
	end
	del_obj_by_id( obj:id() )
end
check_tbl['stdt_pda1'] = function(obj)
	news_manager.send_tip("stdt_pda1_sms", nil, nil, 30000)
	del_obj_by_id( obj:id() )
end
check_tbl['tm_docs14'] = function(obj)
	Actor:give_info_portion("tm_find_done")
	kostya_dialog.delete_teleport("tm_teleport_4")
	AI:create_free("z_inventory_box15",vector():set(84.50724029541,69.478454589844,-7.1580576896667),6048,2417)
	del_obj_by_id( obj:id() )
end
-- Взносы
local items_vzn = {"vzn_mogila","vzn_platok","vzn_vodka","vzn_prez_zapis","vzn_voen_zapis","vzn_ganteli","vzn_grob","vzn_rover","vzn_pesok","vzn_darwin","vzn_pensia","vzn_noty","vzn_kuvalda"}
for i, v in ipairs(items_vzn) do
	check_tbl[v] = function(obj) Actor:give_info_portion("vzn_have") end
end
check_tbl['vzn_treasure_item'] = function(obj)
	Actor:give_info_portion("vzn_have")
	amk.remove_item_from_inventory_by_name("vzn_treasure_item",Actor)
	amk.spawn_item_in_inv("treasure_item", Actor)
	amk.spawn_item_in_inv("vzn_medal", Actor)
	local wpn = kostya_dialog.vzn_taynik_stvol()
	amk.spawn_item_in_inv(wpn, Actor)
end
check_tbl['vzn_mladen'] = function(obj)
	Actor:give_info_portion("vzn_have")
	-- младенец
	local snd = xr_sound.get_safe_sound_object([[characters_voice\scenario\trader\plach]])
	snd:stop()
	snd:play_no_feedback(Actor, sound_object.s2d, 1.0, vector(), 1.0)
end

check_tbl['af_buliz'] = function(obj)
	if Actor:dont_has_info("acv_buliz") and inventory.search_af("af_buliz", 40) then
		archievements.send_archievement("acv_buliz")
	end
end
check_tbl['mutant_wolf_cocoon'] = function(obj)
	if Actor:dont_has_info("acv_emb") then
		archievements.send_archievement("acv_emb")
	end
end
check_tbl['amulet'] = function(item)
	if Actor:has_info("sidor_amulet_vzyt_start")
		and Actor:dont_has_info("sidor_amulet_vzyt_done")
	then
		Actor:set_character_community("monolith", 0, 0)
	end
end
check_tbl['yad'] = function(item)
	del_obj_by_id( item:id() )
end
check_tbl["rx_attach_bandage"] = function(item)
	del_obj_by_id( item:id() )
end
check_tbl['snp_suriken'] = function (item)
	snp.join_monolith()
end
check_tbl['snp_suriken2'] = check_tbl['snp_suriken']
check_tbl['snp_shield'] = check_tbl['snp_suriken']
check_tbl['snp_sword'] = check_tbl['snp_suriken']

check_tbl["kostya_taynik_pda4"] = function (item)
	if Actor:dont_has_info("kostya_taynik_pda4_xvatit_spawn") then 
		news_manager.send_tip("kostya_taynik_pda4_sms", nil, nil, 30000)
		kostya_dialog.spawn_t_teleport4_1()
		AI:create_free("m_controller_normal",vector():set(293.54354858398,-6.1697669029236,-306.34655761719),1388412,2903) 
		AI:create_free("m_controller_normal",vector():set(293.54354858398,-6.1697669029236,-306.34655761719),1388412,2903) 
		AI:create_free("m_controller_old_fat",vector():set(343.52505493164,-1.7487429380417,-291.03280639648),1481127,2903)		
		AI:create_free("m_controller_normal_fat",vector():set(343.52505493164,-1.7487429380417,-291.03280639648),1481127,2903)		
		Actor:give_info_portion("kostya_taynik_pda4_xvatit_spawn")
	end
end
check_tbl["kostya_taynik_pda8"] = function (item)
	if Actor:dont_has_info("kostya_taynik_pda8_xvatit_spawn") then 
		AI:create_free("m_controller_normal",vector():set(-245.26629638672,-0.0019612908363342,108.61695098877),11654,1358) 
		AI:create_free("m_controller_old_fat",vector():set(-268.68731689453,-0.0014384984970093,67.68074798584),4443,1410) 
		AI:create_free("m_controller_old",vector():set(-208.81796264648,-0.00040912628173828,164.56384277344),25007,1332)		
		Actor:give_info_portion("kostya_taynik_pda8_xvatit_spawn")
	end
end
check_tbl["ktdt_pda1"] = function (item)
	if Actor:has_info("ktdt1_found") then 
		Actor:give_info_portion("ktdt2")
		AI:create_free("x_inventory_box2",vector():set(-0.79496783018112,1.145513176918,10.266807556152),309442,1582)
		kostya_dialog.spawn_x_teleport2()
		kostya_dialog.delete_teleport("x_teleport1")
		del_obj_by_id( item:id() )
	end
end
check_tbl["ktdt_pda2"] = function (item)
	if Actor:has_info("ktdt2_found") then
		aem_manager.manage_money(1000000, "in")
		Actor:give_info_portion("ktdt3")
		kostya_dialog.spawn_x_teleport3()
		del_obj_by_id( item:id() )
	end
end
check_tbl["ktdt_pda3"] = function (item)
	if Actor:has_info("ktdt3_found") then
		news_manager.send_tip("ktdt_pda3_sms", nil, nil, 30000)
		del_obj_by_id( item:id() )
	end
end


check_tbl["amk_metka"] = function (item)
	gps_habar.on_item_take()
end

check_tbl["subway_scaner_doc3"] = function ( item )
	if Actor:has_info( "spatial_subway_start" ) then
		amk.remove_item_from_inventory_by_name( "subway_scaner_doc", Actor )
		amk.remove_item_from_inventory_by_name( "subway_scaner_doc2", Actor )
		del_obj_by_id( item:id() )
	end
end
check_tbl["x_ray_antenna"] = function ( item )
	if level.map_has_object_spot( item:id(), "crlc_big") ~= 0 then
		level.map_remove_object_spot( item:id(),"crlc_big" )
	end
end

function check(item)
	local sect = item:section()
	if check_tbl[sect] then
		check_tbl[sect](item)
	end

	if level.map_has_object_spot(item:id(), "red_location") ~= 0 then
		level.map_remove_object_spot(item:id(), "red_location")
	end

	if sys_ini:line_exist(sect, "radiation_restore_speed") then
		local inv_rad
		if item:is_artefact() then
			inv_rad = item:get_inventory_item_float( artefact_offsets.conditions.radiation_restore_speed )
			if bind_det_arts.is_detected_art(sect) then
				xr_statistic.addArtefact(item:id(), sect)
			end
		else
			inv_rad = sys_ini:r_float(sect, "radiation_restore_speed")
		end

		if inv_rad > 0 then
			arc_radiation.change_inv_radiation(inv_rad)
		end
	end
end

