-- -*- mode: lua; encoding: windows-1251 -*-
local check_item_tbl = {}
check_item_tbl['emb_container'] = function(obj)
	Actor:give_info_portion("emb_container_have")
end
check_item_tbl['emb_note25'] = function(obj)
	Actor:give_info_portion("emb14")
end
check_item_tbl['snp_almaz_note1'] = function(obj)
	local sobj = snp.object_by_section_offline("suslov_marsh")
	if sobj then
		AI:release(sobj, true)
	end
	AI:create_no_ai("snp_almaz_note2",vector():set(30.251602172852,-0.85134720802307,-27.375852584839),139607,2131)
end
check_item_tbl['snp_almaz_note3'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note2",Actor)
	AI:create_no_ai("n_inventory_box_almaz4",vector():set(-7.8711194992065,2.2752339839935,-27.166484832764),92225,2131)
end
check_item_tbl['snp_almaz_note4'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note3",Actor)
	AI:create_no_ai("n_inventory_box_almaz5",vector():set(-33.041538238525,5.4613304138184,-31.517143249512),65385,2132)
end
check_item_tbl['snp_almaz_note5'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note4",Actor)
	AI:create_no_ai("n_inventory_box_almaz6",vector():set(47.762790679932,8.6410655975342,-31.51616859436),156324,2137)
end
check_item_tbl['snp_almaz_note6'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note5",Actor)
	AI:create_no_ai("n_inventory_box_almaz7",vector():set(-18.499711990356,1.4957152605057,-25.481069564819),80006,2160)
end
check_item_tbl['snp_almaz_note7'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note6",Actor)
	AI:create_no_ai("n_inventory_box_almaz8",vector():set(44.441833496094,4.6751842498779,-25.246084213257),157056,2228)
	kostya_dialog.create_teleport("tele_almaz8",vector():set(48.973514556885,5.4608883857727,-17.918466567993),164628,2228)
end
check_item_tbl['snp_almaz_note8'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note7",Actor)
	snp.create_restrictor(vector():set(-136.21276855469,12.617782592773,10.618383407593),3688,2252,2,"snp_spawn.n_inventory_box_almaz9")
	kostya_dialog.delete_teleport("tele_almaz8")
end
check_item_tbl['snp_almaz_note9'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note8",Actor)
	AI:create_no_ai("n_inventory_box_almaz10",vector():set(-208.36692810059,8.6610012054443,42.246055603027),4289,2252)
end
check_item_tbl['snp_almaz_note10'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note9",Actor)
	AI:create_no_ai("n_inventory_box_almaz11",vector():set(-216.12236022949,5.4740557670593,86.903327941895),78,2141)
end
check_item_tbl['snp_almaz_note11'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note10",Actor)
	AI:create_no_ai("n_inventory_box_almaz11a",vector():set(-50.975608825684,3.5477068424225,-289.13818359375),137857,3756)
end
check_item_tbl['snp_almaz_note11a'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note11",Actor)
	AI:create_no_ai("n_inventory_box_almaz12",vector():set(855.42320800781,8.4400463104248,64.832587585449),160821,2604)
end
check_item_tbl['snp_almaz_note12'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note11a",Actor)
	AI:create_no_ai("n_inventory_box_almaz13",vector():set(86.640037536621,59.932830810547,116.73533630371),57849,2566)
end
check_item_tbl['snp_almaz_note13'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_almaz_note12",Actor)
	news_manager.send_tip("snp_almaz_note13_sms", 5, nil, 30000)
end
check_item_tbl['snp_note11'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_note10",Actor)
	AI:create_no_ai("n_inventory_box_kl1_3",vector():set(-133.72560119629,-4.0903553962708,-153.58737182617),4283,3238)
end
check_item_tbl['snp_note12'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_note11",Actor)
	AI:create_no_ai("snp_note13",vector():set(-200.10061645508,-0.75918161869049,-77.472457885742),3782,3238)
end
check_item_tbl['snp_note26'] = function(obj)
	if has_alife_info("snp_tmp1") then
		Actor:give_info_portion("snpt_jupiter2_have")
		amk_mod.spawn_military_tech_pack(AI:create("vehicle_btr",vector():set(-157.93148803711,26.787044525146,-469.19927978516),450749,3714) ,"vehicle_btr", "scripts\\snp\\btr.ltx")
		amk_mod.spawn_military_tech_pack(AI:create("vehicle_btr",vector():set(-116.92964172363,26.800518035889,-467.65985107422),523498,3714) ,"vehicle_btr", "scripts\\snp\\btr.ltx")
	else
		Actor:give_info_portion("snpt_jupiter2_fail")
		news_manager.send_tip("snp_note26_sms_fail", nil, nil, 30000)
	end
	Actor:give_info_portion("snp_tmp_reset")
	Actor:disable_info_portion("snp_tmp_reset")
end
check_item_tbl['snp_note27'] = function(obj)
	Actor:give_info_portion("snpt_jupiter3_have1")
end
check_item_tbl['snp_note29'] = function(obj)
	AI:create_no_ai("n_inventory_box_vp5",vector():set(-111.72229003906,0.99149996042252,-103.54452514648),82836,3759)
end
check_item_tbl['snp_note30'] = function(obj)
	amk.remove_item_from_inventory_by_name("snp_note29",Actor)
	AI:create_no_ai("n_inventory_box_vp6",vector():set(205.22360229492,-25.027803421021,-258.54818725586),419629,3765)
end
check_item_tbl['snp_note45'] = function(obj)
	del_obj_by_id(obj:id())
end
check_item_tbl['af_fobos'] = function(obj)
	if not has_alife_info("snpt_jupiter5_done") then
		Actor:give_info_portion("snpt_jupiter5_done")
		news_manager.send_tip("snpt_jupiter5_done_sms", 3, nil, 30000)
		start_real_timer("run",15,"snp_spawn.snpt_jupiter6_run1()")
	end
end
check_item_tbl['af_kamen_udachy2'] = function(obj)
	if has_alife_info("snp_kamen_udachy_not_found") then
		news_manager.send_tip("snp_kamen_udachy_fail_sms", nil, nil, 50000)
		Actor:give_info_portion("snp_kamen_udachy_fail")
	end
	Actor:give_info_portion("snp_kamen_udachy_have")
end
check_item_tbl['snp_pftp'] = function(obj)
	if not has_alife_info("snp_pftp_have") then
		news_manager.send_tip("snp_pftp_have_sms", nil, "nano", 50000)
		Actor:give_info_portion("snp_pftp_have")
	end
end
check_item_tbl['snp_pda_profi1'] = function(obj)
	del_obj_by_id(obj:id())
	for i=1,20 do
		obj = Actor:object("snp_profi"..tostring(i))
		if obj then
			del_obj_by_id(obj:id())
		end
	end
--	news_manager.send_tip("Файл с найденного ПДА скопирован в раздел \"Журнал\\Данные на КПК.\"", nil, "nano", 10000)
	kostya_dialog.delete_teleport("snp_profi_tp0")
	xr_sound.get_safe_sound_object([[snp\pripyat_1986]]):play_at_pos(Actor, vector():set(0,30,0), 150, sound_object.s3d)
	Actor:give_info_portion("snp_profi_done")
end
check_item_tbl['fli_bomba'] = function() fly_island.worker() end
check_item_tbl['fli_note7'] = function(obj)
	if has_alife_info("fli_have_3") and not has_alife_info("fli_have_4") then
		start_real_timer("fli_teleport_actor", 10, "fli99_tp1")
		Actor:give_info_portion("fli_have_4")
	end
end
check_item_tbl['wpn_crossbow_m1'] = function (item, box)
	if box:section() == "m_inventory_box37"
		and not has_alife_info("uhod_iz_mg_have")
	then
		Actor:give_info_portion("uhod_iz_mg_have")
	end
end
check_item_tbl['grenade_rgd5_new'] = function (item, box)
	if level.main_input_receiver() then
		level.start_stop_menu(level.main_input_receiver(), true)
	end

	amk_particle.amk_particle({
		particle="explosions\\explosion_fuelcan",
		pos=Actor:position(),
		sound=[[weapons\t_rgd5_explosion]]
	})

	local h = hit()
	h.draftsman = Actor
	h.direction = vector():set(0,0,0)
	h:bone("bip01_spine")
	h.type = hit.explosion
	h.power = 1.8
	h.impulse = 500
	Actor:hit(h)

	level.add_pp_effector("amk_shoot.ppe", 2011, false)
	level.add_pp_effector( "agr_u_fade.ppe", 8120804, false ) -- чтоб красивее было

	start_real_timer("run", 1, "braad_test.mina_band3()")
	local obj = snp.object_by_section_offline("prov_ruk")
	if obj then
		AI:release(obj, true)
	end
	braad_test.kalmyak_tele2()
end
check_item_tbl['zamok'] = function (item, box)
	zamok.remove(box, item)
end
check_item_tbl["teleportator"] = function ( item )
	-- нашли телепортатор - переносим в него все имеющиеся телепорты
	start_real_timer( "run", 0.2, "teleport_manager.on_take_teleportator()" )
end



local check_box_tbl = {}
check_box_tbl['n_inventory_box_dt1'] = function()
	Actor:give_info_portion("snpt_dt1_have")
end
check_box_tbl['n_inventory_box_dt2'] = function()
	-- Прайм вылечился
	local se_obj = snp.object_by_section_offline("bibliofrend_talk_black_zaton")
	if se_obj then AI:release(se_obj, true) end
	local se_obj = snp.object_by_section_offline("bibliofrend_zaton")
	if se_obj then
		netpk:modify( se_obj, { visual_name = "monsters\\bibliotekar\\bibliotekar" }, net_packet.fState )
	end
	local obj = AI:create("bibliofrend_talk_zaton",vector():set(124.68988037109,-7.3328924179077,177.81799316406),1180494,3686)
	set_story_id(obj, story_ids.bibliofrend_talk_zaton)
	Actor:give_info_portion("snpt_dt2_have")
end
check_box_tbl['n_inventory_box_dt3'] = function()
	amk.remove_item_from_inventory_by_name("gena_note1",Actor)
	AI:create_no_ai("n_inventory_box_cp11",vector():set(-12.712896537781,-5.1684684944153,193.19522900391),90728,2195)
end
check_box_tbl['n_inventory_box_agro1'] = function()
	if has_alife_info("snpt_agro1_fail") then
		news_manager.send_tip("snpt_agro1_fail_sms", 3, nil, 40000)
	else
		news_manager.send_tip("snpt_agro1_have_sms", 3, nil, 30000)
	end
	Actor:give_info_portion("snpt_agro1_have")
end
check_box_tbl['n_inventory_box_kordon2'] = function()
	AI:create_no_ai("n_inventory_box_kordon2_2",vector():set(65.351554870605,8.6025924682617,39.333652496338),301349,423)
end
check_box_tbl['n_inventory_box_kordon2_2'] = function()
	amk.remove_item_from_inventory_by_name("fli_note15",Actor)
end
check_box_tbl['n_inventory_box_kordon5'] = function()
	Actor:give_info_portion("snpt_kordon2_done")
end
check_box_tbl['n_inventory_box_vp1'] = function()
	local a = Actor
	a:give_info_portion("no_teleport_near_heli_btr")
	local se_obj = snp.object_by_section_offline("snp_pda13")
	if se_obj then
		AI:release(se_obj, true)
	end
	snp.create_restrictor_out(a:position(),a:level_vertex_id(),a:game_vertex_id(),30,"snp.heli_vp1_fail")
	snp_spawn.n_inventory_box_vp1()
end
check_box_tbl['n_inventory_box_vp1_2'] = function()
	AI:create_no_ai("n_inventory_box_vp1_3",vector():set(13.420848846436,15.939820289612,376.03521728516),219643,3760)
end
check_box_tbl['n_inventory_box_vp1_3'] = function()
	amk.remove_item_from_inventory_by_name("snp_note3",Actor)
	snp.create_restrictor(vector():set(81.403007507324,12.320181846619,354.12557983398),302206,3760,1,"snp_spawn.n_inventory_box_vp1_4")
end
check_box_tbl['n_inventory_box_vp1_4'] = function()
	amk.remove_item_from_inventory_by_name("snp_note4",Actor)
	Actor:give_info_portion("snpt_vp2_done")
	news_manager.send_tip("snpt_vp2_done_sms", 3, nil, 20000)
end
check_box_tbl['n_inventory_box_vp7'] = function()
	if not has_alife_info("snpt_kl1_found2") then
		news_manager.send_tip("snpt_kl1_fail_sms", nil, nil, 30000)
		Actor:give_info_portion("snpt_kl1_fail")
	end
	Actor:give_info_portion("snpt_kl1_have2")
	snp.move_ariadna_to_bar()
end
check_box_tbl['n_inventory_box_limansk1'] = function()
	AI:create_no_ai("n_inventory_box_limansk1_2",vector():set(-54.28849029541,4.0246248245239,159.91932678223),9647,3010)
end
check_box_tbl['n_inventory_box_limansk1_2'] = function()
	amk.remove_item_from_inventory_by_name("snp_note5",Actor)
	Actor:give_info_portion("snpt_limansk1_have")
end
check_box_tbl['n_inventory_box_limansk2'] = function()
	AI:create_no_ai("n_inventory_box_limansk2_1",vector():set(83.74320251465,22.1644155263901,91.979831542969),51783,3020)
end
check_box_tbl['n_inventory_box_limansk2_1'] = function()
	amk.remove_item_from_inventory_by_name("snp_note14",Actor)
	snp.create_restrictor(vector():set(78.972717285156,33.845104217529,185.52560424805),51783,3020,1,"snp_spawn.n_inventory_box_limansk2_1")
end
check_box_tbl['n_inventory_box_limansk2_2'] = function()
	Actor:give_info_portion("snpt_limansk2_have")
end
check_box_tbl['n_inventory_box_limansk3'] = function()
	Actor:give_info_portion("snpt_limansk3_done")
	news_manager.send_tip("snpt_limansk3_done_sms", 3, nil, 15000)
end
check_box_tbl['n_inventory_box_limansk4'] = function()
	Actor:give_info_portion("snpt_limansk4_have")
	amk.remove_item_from_inventory_by_name("snp_pda6",Actor)
	snp_spawn.n_inventory_box_limansk4()
end
check_box_tbl['n_inventory_box_limansk10'] = function()
	AI:create_no_ai("n_inventory_box_limansk11",vector():set(8.605899810791,8.113245010376,81.677447509766),21950,2988)
	kostya_dialog.delete_teleport("snp_shadow_tp6")
end
check_box_tbl['n_inventory_box_limansk11'] = function()
	amk.remove_item_from_inventory_by_name("snp_note38",Actor)
end
check_box_tbl['n_inventory_box_limansk12'] = function()
	amk.remove_item_from_inventory_by_name("snp_note46",Actor)
end
check_box_tbl['n_inventory_box_almaz1'] = function()
	amk.remove_item_from_inventory_by_name("snp_pda3",Actor)
end
check_box_tbl['n_inventory_box_almaz14'] = function()
	xr_sound.get_safe_sound_object([[snp\heartbeat100]]):stop()
	amk.remove_item_from_inventory_by_name("snp_almaz_note13",Actor)
	Actor:give_info_portion("snp_almaz1")
	news_manager.send_tip("snp_almaz1_sms", 5, nil, 15000)
	kostya_dialog.create_teleport("tele_almaz_act",vector():set(166.77569580078,43.172966003418,386.25317382813),172634,2987)
	AI:create("zone_monolith_snp",vector():set(174.08480834961,55.11833190918,386.01168823242),172632,2987)
	snp.start_sound()
end
check_box_tbl['n_inventory_box_x101'] = function()
	AI:create_no_ai("n_inventory_box_x101_2",vector():set(-30.335075378418,-11.727508544922,48.893642425537),1960,2744)
end
check_box_tbl['n_inventory_box_x101_2'] = function()
	amk.remove_item_from_inventory_by_name("snp_note6",Actor)
	AI:create_no_ai("n_inventory_box_x101_3",vector():set(-17.047734069824,-9.5494222640991,-34.517933197021),3773,2665)
end
check_box_tbl['n_inventory_box_x101_3'] = function()
	Actor:give_info_portion("snpt_x101_have")
	amk.remove_item_from_inventory_by_name("snp_note7",Actor)
	xr_sound.get_safe_sound_object([[monsters\bloodsucker\bloodsucker_script_attack_0]]):play_no_feedback(Actor, sound_object.s2d, 0, vector(), 1.0)
	AI:create("deathclaw_strong",vector():set(-19.920612335205,-9.5487899780273,-41.595027923584),3546,2665)
end
check_box_tbl['n_inventory_box_x81'] = function()
	kostya_dialog.create_teleport("tele_kl1",vector():set(-126.73837280273,-7.9817929267883,-57.95435333252),8203,3240)
end
check_box_tbl['n_inventory_box_x82'] = function()
	Actor:give_info_portion("snpt_x82_done")
end
check_box_tbl['n_inventory_box_x83'] = function()
	level_changers.create_level_changer("lc_warlab_to_control_monolith")
	snp.create_restrictor(vector():set(16.434181213379,-7.8957762718201,19.228824615479),6993,3211,3,"snp.gena_bum1")
end
check_box_tbl['n_inventory_box_kl1'] = function()
	Actor:give_info_portion("snpt_x81_done")
	amk.remove_item_from_inventory_by_name("snp_note9",Actor)
	amk.remove_item_from_inventory_by_name("snp_note13",Actor)
end
check_box_tbl['n_inventory_box_kl3'] = function()
	if not has_alife_info("snpt_kl1_found1") then
		news_manager.send_tip("snpt_kl1_fail_sms1", nil, nil, 30000)
		Actor:give_info_portion("snpt_kl1_fail")
	end
	Actor:give_info_portion("snpt_kl1_have1")
	snp.move_ariadna_to_bar()
end
check_box_tbl['n_inventory_box_sd2'] = function()
	Actor:give_info_portion("snpt_sd2_have")
end
check_box_tbl['n_inventory_box_cp1'] = function()
	Actor:give_info_portion("snpt_cp1_have")
end
check_box_tbl['n_inventory_box_pp1'] = function()
	Actor:give_info_portion("snpt_pp1_have1")
	snp.create_restrictor(vector():set(14.366353034973,26.801988601685,3.5365107059479),21893,3792,2,"snp_spawn.n_inventory_box_pp1")
	news_manager.send_tip("snpt_pp1_have1_sms", 10, nil, 20000)
end
check_box_tbl['n_inventory_box_td1'] = function()
	if not has_alife_info("snpt_td1_have1") then
		Actor:give_info_portion("snpt_td1_have1")
	else
		Actor:give_info_portion("snpt_td1_have2")
	end
end
check_box_tbl['n_inventory_box_garbage1'] = function () snp_spawn.n_inventory_box_garbage1() end
check_box_tbl['n_inventory_box_garbage2'] = function () snp_spawn.n_inventory_box_garbage2() end
check_box_tbl['n_inventory_box_garbage3_1'] = function ()
	news_manager.send_tip("n_inventory_box_garbage3_1_sms", nil, nil, 10000)
	kostya_dialog.create_teleport("snp_receipt_parts2_tp2",vector():set(69.402984619141,7.087566614151,98.179962158203),239958,370)
end
check_box_tbl['n_inventory_box_garbage3_2'] = function ()
	kostya_dialog.create_teleport("snp_receipt_parts2_tp4",vector():set(36.57763671875,9.8525171279907,235.24243164063),209829,359)
	AI:create_no_ai("n_inventory_box_garbage3_3",vector():set(88.548858642578,14.494812965393,-150.32049560547),255908,412)
end
check_box_tbl['n_inventory_box_garbage3_3'] = function()
	Actor:give_info_portion("snp_receipt_parts2_have")
	amk.remove_item_from_inventory_by_name("snp_note19",Actor)
end
check_box_tbl['n_inventory_box_cp2'] = function()
	AI:create_no_ai("n_inventory_box_cp3",vector():set(209.37040710449,2.7850260734558,87.78483581543),257446,2145)
end
check_box_tbl['n_inventory_box_cp3'] = function()
	Actor:give_info_portion("snp_receipt_parts1_have")
	amk.remove_item_from_inventory_by_name("snp_note17",Actor)
end
check_box_tbl['n_inventory_box_cp11'] = function()
	amk.remove_item_from_inventory_by_name("gena_note2",Actor)
	AI:create_no_ai("n_inventory_box_gen2",vector():set(58.491859436035,32.280834197998,-551.94244384766),404600,3117)
end
check_box_tbl['n_inventory_box_cp4_1'] = function()
	amk.remove_item_from_inventory_by_name("snp_note20",Actor)
	AI:create_no_ai("n_inventory_box_cp4_2",vector():set(47.559024810791,8.9481220245361,-164.22630310059),159135,2136)
end
check_box_tbl['n_inventory_box_cp4_2'] = function()
	amk.remove_item_from_inventory_by_name("snp_note21",Actor)
	kostya_dialog.create_teleport("snp_cp_tp1",vector():set(146.888671875,11.983012199402,116.23860931396),243444,2174)
end
check_box_tbl['n_inventory_box_cp4_3'] = function()
	Actor:give_info_portion("snp_receipt_parts4_have")
	amk.remove_item_from_inventory_by_name("snp_note22",Actor)
end
check_box_tbl['n_inventory_box_x161'] = function()
	Actor:give_info_portion("snp_receipt_parts3_have")
	snp_spawn.n_inventory_box_x161()
	local se_obj = AI:create("lobsang_zaton",vector():set(132.97550964355,-7.3394374847412,189.05435180664),1194666,3686)
	set_story_id(se_obj, story_ids.lobsang_zaton)
end
check_box_tbl['n_inventory_box_jupiter1'] = function()
	Actor:give_info_portion("snp_receipt_parts5_have")
end
check_box_tbl['n_inventory_box_jupiter8'] = function()
	AI:create_no_ai("n_inventory_box_jupiter8_2",vector():set(387.51806640625,15.237261772156,-85.501846313477),1328997,3744)
end
check_box_tbl['n_inventory_box_jupiter8_2'] = function()
	amk.remove_item_from_inventory_by_name("snp_note44",Actor)
	snp_spawn.n_inventory_box_jupiter8_2()
end
check_box_tbl['n_inventory_box_jupiter11'] = function()
	amk.remove_item_from_inventory_by_name("snp_note26",Actor)
end
check_box_tbl['n_inventory_box_2chaes1'] = function()
	snp.create_item_and_restrictor("fenrir_2chaes",vector():set(941.21911621094,13.052788734436,273.22985839844),250079,2642)
	news_manager.send_tip("fenrir_2chaes_sms", 4, nil, 15000)
end	
check_box_tbl['n_inventory_box_2chaes2'] = function()
	news_manager.send_tip("n_inventory_box_2chaes2_sms", 3, nil, 50000)
	kostya_dialog.delete_teleport("fli_block_tp1")
	kostya_dialog.delete_teleport("fli_block_tp2")
end
check_box_tbl['n_inventory_box_as2'] = function()
	local se_obj = AI:create_no_ai("n_inventory_box_dt3",vector():set(-61.349769592285,-0.71912717819214,470.66595458984),20316,1384)
	amk.add_spot_on_map(se_obj.id,"crlc_mdl","st_elza_search_place") 
end
check_box_tbl['n_inventory_box_mg1'] = function()
	AI:create_no_ai("n_inventory_box_limansk12",vector():set(10.524602584839,1.8927528858185,-391.09912109375),30960,3006)
end
check_box_tbl['n_inventory_box_mg2'] = function()
	Actor:give_info_portion("snpt_mg2_have1")
	snp.create_restrictor(vector():set(-74.212478637695,2.7899203300476,64.743927001953),272032,3622,80,"snp_spawn.snpt_mg2_lastday")
end
check_box_tbl['n_inventory_box_bar1'] = function()
	Actor:give_info_portion("snpt_bar1_done")
end
check_box_tbl['n_inventory_box_bar2'] = function()
	Actor:give_info_portion("snpt_bar2_done")
end
check_box_tbl['n_inventory_box_gen2'] = function()
	amk.remove_item_from_inventory_by_name("gena_note3",Actor)
	AI:create_no_ai("n_inventory_box_x83",vector():set(-93.740013122559,-15.946046447754,112.18583679199),1380,3837)
end
check_box_tbl['n_inventory_box_hospital2'] = function()
	kostya_dialog.delete_teleport("fli99_tp3")
end
check_box_tbl['n_inventory_box_warlab1'] = function()
	Actor:give_info_portion("snpt_warlab1_done")
end
check_box_tbl['n_inventory_box_zaton1'] = function()
	AI:create_no_ai("n_inventory_box_zaton1_2",vector():set(-394.79879760742,53.038612365723,-337.77597045898),185627,3664)
end
check_box_tbl['n_inventory_box_zaton1_2'] = function()
	amk.remove_item_from_inventory_by_name("fli_note14",Actor)
end
check_box_tbl['n_inventory_box_zaton3'] = function()
	Actor:give_info_portion("snpt_zaton1_done")
	kostya_dialog.create_teleport("snp_zaton_tp1", Actor:position(), Actor:level_vertex_id(), Actor:game_vertex_id())
end
check_box_tbl['n_inventory_box_zaton5'] = function()
	Actor:give_info_portion("snpt_zaton3_done")
end
check_box_tbl['n_inventory_box_zaton6'] = function()
	Actor:give_info_portion("snpt_zaton4_done")
end
check_box_tbl['n_inventory_box_hospital3'] = function()
	Actor:give_info_portion("snpt_hospital1_done")
end
check_box_tbl['n_inventory_box_x181'] = function()
	Actor:give_info_portion("snpt_x181_done")
end
check_box_tbl['n_inventory_box_x162'] = function()
	Actor:give_info_portion("snpt_x161_done")
	Actor:give_info_portion("snp_video_arhiv_done")
	archievements.acv_task()
	news_manager.send_tip("snp_video_arhiv_done_sms", 10, nil, 30000)
	if not has_alife_info("sidor_delo_done") then
		news_manager.send_tip("snp_video_arhiv_done_sms1", 20, nil, 40000)
	end
	local obj = AI:create("vesker_zaton",vector():set(128.0725402832,-7.3395228385925,189.58338928223),1186465,3686)
	set_story_id(obj, story_ids.vesker_zaton)
end
check_box_tbl['n_inventory_box_yantar1'] = function()
-- snp.x16_17()
	xr_sound.get_safe_sound_object([[script_sound\reactions\dead_enemy\soldier\soldier_dead_enemy_1]]):play(Actor, 2, sound_object.s2d)
	start_real_timer("run",6,"snp.x16_18()")
end
check_box_tbl['n_inventory_box_bum1'] = function()
	amk.remove_item_from_inventory_by_name("gena_note4",Actor)
	kostya_dialog.create_teleport("gena_tp1", Actor:position(), Actor:level_vertex_id(), Actor:game_vertex_id())
	start_real_timer("run", 1, "snp.gena_oso1_start()")
end
check_box_tbl['n_inventory_box_profi1'] = function()
	kostya_dialog.delete_teleport("snp_profi_tp1")
end
check_box_tbl['n_inventory_box_profi2'] = function()
	kostya_dialog.create_teleport("snp_profi_tp2", Actor:position(), Actor:level_vertex_id(), Actor:game_vertex_id())
end
check_box_tbl['n_inventory_box_profi3'] = function()
	kostya_dialog.delete_teleport("snp_profi_tp2")
end
check_box_tbl['n_inventory_box_profi4'] = function()
	kostya_dialog.delete_teleport("snp_profi_tp4")
end
check_box_tbl['n_inventory_box_profi5'] = function()
	kostya_dialog.delete_teleport("snp_profi_tp5_1")
	kostya_dialog.delete_teleport("snp_profi_tp5_2")
end
check_box_tbl['n_inventory_box_profi6'] = function()
	kostya_dialog.delete_teleport("snp_profi_tp6")
end
check_box_tbl['v_inventory_box0'] = function()
	news_manager.send_tip("vol_info_temp_sms", 3, nil, 40000)
	Actor:give_info_portion("vol_info_temp")
	Actor:give_info_portion("vol_fly")
end
check_box_tbl['a_inventory_box24'] = function()
	Actor:give_info_portion("taynik_dimak_have")
end
-- archievements
check_box_tbl['m_inventory_box13'] = function()
	Actor:give_info_portion("acv_sishik1")
	archievements.acv_sishik()
end
check_box_tbl['x_inventory_box3'] = function()
	Actor:give_info_portion("acv_sishik2")
	archievements.acv_sishik()
end
check_box_tbl['y_inventory_box1'] = function()
	Actor:give_info_portion("acv_sishik3")
	archievements.acv_sishik()
end
check_box_tbl['z_inventory_box15'] = function()
	Actor:give_info_portion("acv_sishik4")
	archievements.acv_sishik()
end
check_box_tbl['m_inventory_box_eye_xolod'] = function()
	Actor:give_info_portion("info_dialogue_dead_cold_have")
	local obj = AI:story_object(10021)
	if obj then
		AI:release(obj, true)
	end
	oksana_spawn.spawn_glaz_sniper()
end



function check_treasure_item( item, box )
	local sect = item:section()
	if check_item_tbl[sect] then
		check_item_tbl[sect] ( item, box )
	end
end

function check_treasure( box )
	sect = box:section()
	if check_box_tbl[sect] then
		check_box_tbl[sect] ( box )
	end
	if sect:find("emb_inventory_box") then
		-- эмбрионы невидимые тайники
		emb.worker()
	elseif sect:find("shadow") then
		-- тени
		snp_shadow.worker()
	elseif sect:find("inventory_box_fli") then
		-- острова
		fly_island.final_worker(sect)
	elseif sect:find("n_inventory_box_profi") then
		snp_spawn.all_letters()
	elseif sect:find("s_inventory_box_stealth") then
		Actor:give_info_portion("stealth_find_pda_have"..string.sub(sect,-1))
	end
end
