-- -*- mode: lua; encoding: windows-1251 -*-
-- Достижения
local medicals = {
"suvorotka",
"vodka",
"antirad",
"medkit",
"medkit_army",
"medkit_scientic",
"energy_drink",
"bandage",
"antizombie",
}

local wpns = {
"wpn_akms_m1",
"wpn_kord_m1",
"wpn_fn2000_sniper",
"wpn_vepr12_20",
"wpn_m500_custom",
"wpn_akm_ves_otdaca",
"wpn_akms_m2",
"wpn_aug_a2",
"wpn_fn2000_paratrooper",
"wpn_gauss2b",
"wpn_groza_sn",
"wpn_oicw",
"wpn_sks_cust",
"wpn_val_voron",
"wpn_ks23",
"wpn_sayga12k",
"wpn_ak74u_svd",
"wpn_awp_m1",
"wpn_sg550_sr",
"wpn_vihlop_m1",
"wpn_zastava_m77",
"wpn_20w_vintorez",
"wpn_ak74_m3",
"wpn_ak74_m1",
"wpn_ak104t",
"wpn_aks74_m1",
"wpn_g36_m1",
"wpn_hostel",
"wpn_m4_m1",
"wpn_ognemet",
"wpn_svd_m1",
"wpn_svd_m2",
"wpn_svd_m3",
"wpn_b94_sil",
"wpn_protecta_col",
"wpn_vintorez_m1",
"wpn_walther_wa2000",
"wpn_spas12_m1",
"wpn_groza_m1",
"wpn_dark_gauss",
"wpn_benelli_m3_short",
"wpn_rpkcustom",
"wpn_sw",
"wpn_rpk47_sk1",
"wpn_vepr12_m1",
"wpn_sayga_un",
"wpn_mauser",
}

function acv_halavshic()
	send_archievement("acv_halavshic")
end

function acv_homak()
	send_archievement("acv_homak")
end

function acv_found_myself()
	send_archievement("acv_found_myself")
	naxac.del_aes_flames()
end

function acv_mtv()
	send_archievement("acv_mtv")
end

function acv_kart()
	send_archievement("acv_kart")
end

function acv_kro()
	send_archievement("acv_kro")
end

function acv_ele()
	send_archievement("acv_ele")
end

function acv_gromov()
	send_archievement("acv_gromov")
end

function acv_farm()
	acv_count_event("acv_farm", 30)
end

function acv_coll()
	send_archievement("acv_coll")
end

function acv_profi()
	send_archievement("acv_profi")
end

function acv_volna()
	send_archievement("acv_volna")
end

function acv_shax()
	send_archievement("acv_shax")
end

function acv_sos()
	if has_alife_info("acv_sos") then return end
	
	if has_alife_info("squad_is_alive") and has_alife_info("psih_is_alive") then 
		send_archievement("acv_sos")
	end
end

function acv_snp()
	if has_alife_info("acv_snp") then return end
	
	if  has_alife_info("upiter_sdelka_have") and 
		has_alife_info("fli_chaes_have") and 
		has_alife_info("borov_bottle_done") and
		has_alife_info("viking_proverka_have")
	then 
		send_archievement("acv_snp")
	end
end

function acv_docs()
	if not has_alife_info("acv_docs_fail") then
		send_archievement("acv_docs")
	end
end

function acv_aem()
	if not has_alife_info("acv_aem") then
		send_archievement("acv_aem")
	end
end

function acv_cognized_zone()
	if has_alife_info("acv_cognized_zone") then return end

	for i=1,36 do
		if not has_alife_info("arhara_obman"..tostring(i)) then return end
	end

	send_archievement("acv_cognized_zone")
end

function acv_sishik()
	if has_alife_info("acv_sishik") then return end
	
	if has_alife_info("acv_sishik1") and has_alife_info("acv_sishik2") and has_alife_info("acv_sishik3") and has_alife_info("acv_sishik4") then 
		send_archievement("acv_sishik")
	end
end

function acv_task()
	if has_alife_info("acv_task_fail") then return end

	if has_alife_info("info_chess_dictofon_done") and has_alife_info("snp_video_arhiv_done") then 	
		send_archievement("acv_task")
		start_real_timer("run", 5, "archievements.acv_stalker()")
	end
end

function acv_real()
	if has_alife_info("acv_real_fail") then return end

	send_archievement("acv_real")
end

function acv_vzn()
	if has_alife_info("acv_vzn3") then return end

	if     not has_alife_info("acv_vzn1") then
		send_archievement("acv_vzn1")
	elseif not has_alife_info("acv_vzn2") then
		Actor:give_info_portion("acv_vzn2")
	elseif not has_alife_info("acv_vzn3") then
		send_archievement("acv_vzn3")
	end
end

function acv_life()
	if sak.all_questmen_alive() then
		if has_alife_info("acv_umer") then
			send_archievement("acv_resur")
		else
			send_archievement("acv_alive")
		end
	end
end

function acv_money()
	if Actor:money() > 90000000 then return end
	
	if not has_alife_info("acv_money1") and Actor:money() >= 5000000 then
		send_archievement("acv_money1")
	end
	if not has_alife_info("acv_money2") and Actor:money() >= 15000000 then
		send_archievement("acv_money2")
	end
	if not has_alife_info("acv_money3") and Actor:money() >= 30000000 then
		send_archievement("acv_money3")
	end
end

function has_cheated_jump()
	if has_alife_info("acv_has_cheated") then return end

	news_manager.send_tip("acv_jump_text", nil, "nano", 30000)
	send_archievement("acv_has_cheated")
end

function has_cheated_money()
	if has_alife_info("acv_has_cheated") then return end
	
	news_manager.send_tip("acv_money_text", nil, "nano", 30000)
	send_archievement("acv_has_cheated")
end

function has_cheated_item()
	if has_alife_info("acv_has_cheated") or has_alife_info("mm_opt") then return end

	news_manager.send_tip("acv_item_text", nil, "nano", 30000)
	send_archievement("acv_has_cheated")
end

function has_cheated_zone()
	if has_alife_info("acv_has_cheated") then return end
	
	news_manager.send_tip("acv_zone_text", nil, "nano", 30000)
	send_archievement("acv_has_cheated")
end

function acv_angel()
	if all_ecologs_alive() then
		inventory.give_items("af_life_heart",1)
		send_archievement("acv_angel")
	end
end
function all_ecologs_alive()
	local ecologs = {
		"bar_ecolog_professor",
		"bar_ecolog_crush_1",
		"bar_ecolog_crush_2",
		"bar_ecolog_crush_3",
		"bar_ecolog_crush_4",
	}
	local se_obj, obj
	
	for _, name in ipairs(ecologs) do
		se_obj = AI:object(name)
		if not se_obj then return false end
		
		obj = level.object_by_id(se_obj.id)
		if not obj or not obj:alive() then return false end
	end
	
	return true
end

function acv_kill()
	local value = amk.load_variable("acv_kill", 0)+1
	amk.save_variable("acv_kill", value)
	
	if not has_alife_info("acv_kill") and value >= 3000 then
		send_archievement("acv_kill")
	end
	if not has_alife_info("acv_kill2") and value >= 6000 then
		send_archievement("acv_kill2")
	end
	acv_unstoppable()
end

function acv_mons()
	local value = amk.load_variable("acv_mons", 0)+1
	amk.save_variable("acv_mons", value)
	
	if not has_alife_info("acv_mons") and value >= 6000 then
		send_archievement("acv_mons")
	end
	if not has_alife_info("acv_mons2") and value >= 10000 then
		send_archievement("acv_mons2")
	end
	acv_unstoppable()
end

function acv_unstoppable()
	if not has_alife_info("acv_unstoppable") and amk.load_variable("acv_kill", 0)+amk.load_variable("acv_mons", 0) >= 20000 then
		send_archievement("acv_unstoppable")
	end
end

function acv_stalker()
	if  has_alife_info("acv_sishik") and 
		has_alife_info("acv_angel") and 
		has_alife_info("acv_vandal") and 
		has_alife_info("acv_sos") and 
		has_alife_info("acv_docs") and 
		has_alife_info("acv_cognized_zone") and 
		has_alife_info("acv_lekar") and 
		has_alife_info("acv_tereza") and 
		has_alife_info("acv_farm") and 
		has_alife_info("acv_rank2") and 
		has_alife_info("acv_emb") and 
		has_alife_info("acv_hell") and 
		has_alife_info("acv_snp") and 
		has_alife_info("acv_ct") and 
		has_alife_info("acv_kill") and 
		has_alife_info("acv_mons") and 
		has_alife_info("acv_zoms") and 
		has_alife_info("acv_task") and 
		has_alife_info("acv_vzn1") and 
		has_alife_info("acv_alive") and 
		has_alife_info("acv_rem") and 
		has_alife_info("acv_paparacci") and 
		has_alife_info("acv_wpn") and 
		has_alife_info("fli_done") and 
		has_alife_info("taynik_nayti_oz_10_done") and 
		has_alife_info("volna_day4_done") and 
		has_alife_info("info_chess_dictofon_done") --and 
		-- not has_alife_info("acv_has_cheated") and
		-- not has_alife_info("acv_halavshic3") and
		-- not has_alife_info("acv_bridge") and
		-- not has_alife_info("acv_docs_fail") and
		-- not has_alife_info("acv_money3") and
		-- not has_alife_info("acv_alk") and
		-- not has_alife_info("acv_slp") and
		-- not has_alife_info("acv_xam") and
		-- not has_alife_info("acv_task_fail") and
		-- not has_alife_info("acv_vzn3") and
		-- not has_alife_info("acv_umer")
	then
		send_archievement("acv_stalker")
	end
end

-- единая функция обработки и выдачи подсчитываемого достижения
function acv_count_event(acv, count, qty)
	if has_alife_info(acv) then return end
	
	if not qty then
		qty = 1
	end
	
	local value = amk.load_variable(acv, 0)+qty
	
	if value >= count then
		amk.del_variable(acv)
		send_archievement(acv)
		return
	end

	amk.save_variable(acv, value) 
end

-- единая функция обработки и выдачи 2-х последовательно подсчитываемых достижений
function acv_count_2event(acv, count, acv2, count2, qty)
	if has_alife_info(acv) and has_alife_info(acv2) then return end
	
	if not qty then
		qty = 1
	end
	
	local value = amk.load_variable(acv, 0)+qty
	
	if not has_alife_info(acv) and value >= count then
		send_archievement(acv)
	end

	if value >= count2 then
		amk.del_variable(acv)
		send_archievement(acv2)
		return
	end

	amk.save_variable(acv, value) 
end

-- единая функция обработки и выдачи 3-х последовательно подсчитываемых достижений
function acv_count_3event(acv, count, acv2, count2, acv3, count3, qty)
	if has_alife_info(acv) and has_alife_info(acv2) and has_alife_info(acv3) then return end
	
	if not qty then
		qty = 1
	end
	
	local value = amk.load_variable(acv, 0)+qty
	
	if not has_alife_info(acv) and value >= count then
		send_archievement(acv)
	end

	if not has_alife_info(acv2) and value >= count2 then
		send_archievement(acv2)
	end

	if value >= count3 then
		amk.del_variable(acv)
		send_archievement(acv3)
		return
	end

	amk.save_variable(acv, value) 
end

-- счетчик смертей гг
function on_actor_death(who)
	if has_alife_info("peshera_go") then return end	-- сон в Пещере не считаем

	set_death_count("death", get_death_count("death")+1)
	
	if who and IsAnomaly(who) then
		set_death_count("anoms", get_death_count("anoms")+1)
	end
end
function acv_death()
	if not has_alife_info("acv_death") and get_death_count("death") >= 500 then
		send_archievement("acv_death")
	end
	
	if not has_alife_info("acv_anoms") and get_death_count("anoms") >= 20 then
		send_archievement("acv_anoms")
	end
end

-- универсальный независимый от сейвов счетчик, реализованный на файлах - считает количество смертей гг а также время прохождения
function get_death_count(what)
	local f = getFS()
	local flist = f:file_list_open_ex("$game_stats$", bit_or(FS.FS_ListFiles, FS.FS_RootOnly), "*."..what)

	if flist:Size() > 0 then
		return tonumber(string.match(flist:GetAt(0):NameFull(),"^(%d+)"))
	else
		local f1 = f:update_path("$fs_root$", "fsgame.ltx")
		local f2 = f:update_path("$game_stats$", "0."..what)
		f:file_copy(f1, f2)
		return 0
	end
end
function set_death_count(what, value)
	local f = getFS()
	local fileName = f:file_list_open_ex("$game_stats$", bit_or(FS.FS_ListFiles, FS.FS_RootOnly), "*."..what):GetAt(0):NameFull()
	local fileNameNew = tostring(value).."."..what
	if fileNameNew ~= fileName then
		local f1 = f:update_path("$game_stats$", fileName)
		local f2 = f:update_path("$game_stats$", fileNameNew)
		f:file_rename(f1, f2, true)
	end
end

function on_new_game()
	get_death_count("game")
	set_death_count("game", 0)
	get_death_count("death")
	set_death_count("death", 0)
	get_death_count("anoms")
	set_death_count("anoms", 0)
end

function save_gametime()
	if AI then
		set_death_count("game", get_death_count("game")+math.floor(time_global()/60000+0.5))
	end
end

-- универсальный механизм проверки, что обработан каждый объект из списка
function has_all(tbl, info, section)
	for i, s in ipairs(tbl) do
		if s == section and not has_alife_info(info..i) then
			Actor:give_info_portion(info..i)
			return has_all_info(tbl, info)
		end
	end
	return false
end
function has_all_info(tbl, info)
	for i=1, #tbl do
		if not has_alife_info(info..i) then
			return false
		end
	end
	return true
end

-- взятие тайника без уникальных предметов
-- перенесено в snp в общий массив
function check_treasure(box)
	local section = box:section()
	if     section == "m_inventory_box13" then
		Actor:give_info_portion("acv_sishik1")
		acv_sishik()
	elseif section == "x_inventory_box3" then
		Actor:give_info_portion("acv_sishik2")
		acv_sishik()
	elseif section == "y_inventory_box1" then
		Actor:give_info_portion("acv_sishik3")
		acv_sishik()
	elseif section == "z_inventory_box15" then
		Actor:give_info_portion("acv_sishik4")
		acv_sishik()
	end
end

-- подъем предмета
local mut_parts = {
	['mutant_spider_gland'] = true,
	['mutant_rotan_heart'] = true,
	['mutant_plague_hand'] = true,
	['mutant_carlic_hand'] = true,
	['mutant_raptor_kogot'] = true,
	['mutant_zanoza_leg'] = true,
	['mutant_flesh_eye'] = true,
	['mutant_boar_leg'] = true,
	['mutant_dog_tail'] = true,
	['mutant_psevdodog_tail'] = true,
	['mutant_krovosos_jaw'] = true,
	['mutant_burer_hand'] = true,
	['mutant_zombie_hand'] = true,
	['mutant_snork_leg'] = true,
	['mutant_face_tushkano'] = true,
	['mutant_hand_kontroler'] = true,
	['mutant_poltergeist_glas'] = true,
	['mutant_psevdogigant_hand'] = true,
	['mutant_tail_cat'] = true,
	['mutant_chimera_kogot'] = true,
	['mutant_fracture_hand'] = true,
	['mutant_deathclaw_antler'] = true,
	['part_digitis_biblio'] = true,
	['mutant_vypolzen_hrebet'] = true,
	['part_tarakan'] = true,
	['part_tarakan_strong'] = true,
	['mutant_zombie_teeth'] = true,
	['mutant_spleen_rat'] = true
}
function on_item_take(obj)
	local section = obj:section()
	
	if Actor:dont_has_info("acv_wpn")
		and has_all(wpns, "acv_wpn", section)
	then
		Actor:give_info_portion("acv_wpn")
		send_archievement("acv_wpn")
	end

	if mut_parts[section] and Actor:dont_has_info("acv_ynat") then
		local a = Actor
		for k in pairs(mut_parts) do
			if a:object(k) == nil then return end
		end
		send_archievement("acv_ynat")
	end
end

-- использование предмета
function on_use_item(section)
	if Actor:dont_has_info("acv_tera")
		and has_all(medicals, "acv_tera", section)
	then
		send_archievement("acv_tera")
	end
	
	if Actor:dont_has_info("acv_gurman")
		and (section == "vorona_egg"
		or section == "mozg"
		or section == "bezoar"
		or section == "mushroom")
	then
		send_archievement("acv_gurman")
	end
end

-- получение поршня
function on_info(info_id)
	if not has_alife_info("acv_rem") and
		has_alife_info("dolgovazyi_toolkit_done") and
		has_alife_info("dolgovazyi_voen2_done") and
		has_alife_info("vasily_toolkit_done") and
		has_alife_info("dimak_toolkit_done") and
		has_alife_info("atp_propusk_shurup_done") and
		has_alife_info("petr_sidor_vzyt_done") and
		has_alife_info("sidor_amulet_vzyt_done") and
		has_alife_info("sak_repair_box_done")
	then
		send_archievement("acv_rem")
	end

	if not has_alife_info("acv_paparacci") and
		not has_alife_info("foto_ohota_fail") and
		has_alife_info("odnonogiy_foto_done") and
		has_alife_info("izomorf_dialog_have") and
		has_alife_info("izomorf_dialog_done") and
		has_alife_info("foto_ohota_done") and
		has_alife_info("foto_anomaly_done") and
		has_alife_info("silent_hunt_done") and
		has_alife_info("kontrik_electro_done") and
		has_alife_info("ohota_wolf_done") and
		has_alife_info("volna_foto_done") and
		has_alife_info("bar_dolg_petrenko_electra_flash_done") and
		has_alife_info("foto_strelok_done")
	then
		send_archievement("acv_paparacci")
	end

	if not has_alife_info("acv_etolog") and
		not has_alife_info("foto_ohota_fail") and
		has_alife_info("izomorf_dialog_have") and
		has_alife_info("izomorf_dialog_done") and
		has_alife_info("foto_ohota_done") and
		has_alife_info("silent_hunt_done") and
		has_alife_info("kontrik_electro_done") and
		has_alife_info("ohota_wolf_done") and
		has_alife_info("bar_dolg_petrenko_electra_flash_done")
	then
		send_archievement("acv_etolog")
	end
end

local foods = {
	["kolbasa"] = true,
	["conserva"] = true,
	["bread"] = true,
	["sandwich"] = true,
	["sweetness"] = true
}
local params = {}

-- получение подсчитываемого предмета
function on_receive_count_item(obj)
	local section = obj:section()

	if (not foods[section] and
		not isMagazinedWeapon(obj))
		or 
		(has_alife_info("acv_food") and
		has_alife_info("acv_weapon"))
	then return end
	
	params.food = 0
	params.wpn = 0
	
	Actor:inventory_for_each(count_objects)
	
	if not has_alife_info("acv_food") and params.food >= 200 then
		send_archievement("acv_food")
	elseif not has_alife_info("acv_weapon") and params.wpn >= 100 then
		send_archievement("acv_weapon")
	end
	
	params = {}
end
function count_objects(item)
	if foods[item:section()] then
		params.food = params.food+1
	elseif isMagazinedWeapon(item) then
		params.wpn = params.wpn+1
	end
end

function send_archievement(acv_name)
	if Actor:has_info(acv_name) then return end
	Actor:give_info_portion(acv_name)
	start_real_timer("send_archievement", 2.5, acv_name)
end
function send_archievement_chunk(acv_name)
	local acv_text = "%c[255,255,255,0]Новое достижение\\n%c[255,255,185,0]"..game.translate_string(acv_name)
	Actor:give_game_news(acv_text, "ui\\ui_iconsTotal", Frect():set(747,517,83,47), 0, 20000)
	xr_sound.get_safe_sound_object([[device\pda\pda_objective]]):play(Actor, 0, sound_object.s2d)
	
	local hud = get_hud():AddCustomStatic("main_task", true)
	hud:wnd():SetTextST(acv_text)
	hud.m_endTime = time_global()/1000+10

	if acv_name == "acv_stalker" then
		akill.achieve_all_taynik_spawn(acv_name)
	elseif acv_name ~= "acv_vzn3"
		and acv_name ~= "acv_slp"
		and acv_name ~= "acv_alk"
		and acv_name ~= "acv_money3"
		and acv_name ~= "acv_buliz"
		and acv_name ~= "acv_vodka"
		and acv_name ~= "acv_food"
		and acv_name ~= "acv_xam"
		and acv_name ~= "acv_has_cheated"
	then
		akill.achieve_taynik_spawn(acv_name)
	end
end

function send_umer_info(obj)
	local npc_name = naxac_netpk.get_character_name(obj)

	amk.send_tip("%c[255,255,0,0]Зафиксирована смерть сталкера по кличке "..npc_name.."%c[default]", "ЛОКАЛЬНАЯ СЕТЬ", 0, 15, "questman_death", "questman_death")
	local hud = get_hud():AddCustomStatic("main_task", true)
	hud:wnd():SetTextST("%c[255,255,0,0]Погиб сталкер:\\n"..npc_name)
	hud.m_endTime = time_global()/1000+7

	Actor:give_info_portion("acv_umer")
end

function mm_opt()
--	if level.present() and (Actor ~= nil) and Actor:alive() then
--		Actor:give_info_portion("mm_opt")
--	end
--	start_real_timer("mm_opt", 0.2)
end
