-- -*- mode: lua; encoding: windows-1251 -*-
--[[ embrions
  idea by andrew53
  algorithm & optimization by Monnoroch
  realization by Shadowman  
  special thanks to Malandrinus for manual on object_binder
]]

local mut_sec =  {
    ["zone_krovosos"]     = { sec = "bloodsucker_weak",          cnt = 1 },
    ["zone_burer"]        = { sec = "burer_weak",                cnt = 1 },
    ["zone_zombie"]       = { sec = "zombie_weak",               cnt = 1 },
    ["zone_snork"]        = { sec = "snork_weak",                cnt = 1 },
    ["zone_flesh"]        = { sec = "flesh_weak",                cnt = 1 },
    ["zone_gigant"]       = { sec = "gigant_normal",             cnt = 1 },
    ["zone_poltergeist"]  = { sec = "m_poltergeist_normal_tele", cnt = 1 },
    ["zone_psevdodog"]    = { sec = "pseudodog_weak",            cnt = 1 },
    ["zone_controller"]   = { sec = "m_controller_normal",       cnt = 1 },
    ["zone_chimera"]      = { sec = "chimera_weak",              cnt = 1 },
    ["zone_boar"]         = { sec = "boar_weak",                 cnt = 2 },
    ["zone_tushkano"]     = { sec = "tushkano_normal",           cnt = 4 },
    ["zone_psydog"]       = { sec = "psy_dog",                   cnt = 1 },
    ["zone_cat"]          = { sec = "cat_weak",                  cnt = 2 },
    ["zone_dog"]          = { sec = "dog_normal",                cnt = 3 },
	-- emb
    ["zone_rat"]          = { sec = "rat_strong",                cnt = 4 },
    ["zone_tarakan"]      = { sec = "tarakan_normal",            cnt = 4 },
    ["zone_tarakan2"]     = { sec = "tarakan_strong",            cnt = 2 },
    ["zone_bloodsucker"]  = { sec = "bloodsucker_effector",      cnt = 1 },
    ["zone_bloodsucker2"] = { sec = "bloodsucker_hell",          cnt = 1 },
    ["zone_deathclaw"]    = { sec = "deathclaw_strong",          cnt = 1 },
    ["zone_fracture"]     = { sec = "fracture_strong",           cnt = 1 },
    ["zone_bibliotekar"]  = { sec = "bibliotekar",               cnt = 1 },
    ["zone_mono"]         = { sec = "snp_tank1",                 cnt = 1 },
    ["zone_tm"]           = { sec = "shadow_monolith_cocoon",    cnt = 1 },
    ["zone_babka"]        = { sec = "zombie_babka_strong",       cnt = 1 },
    ["zone_ghost"]        = { sec = "zombie_ghost",              cnt = 1 },
    ["zone_kachok"]       = { sec = "boar_kachok",               cnt = 1 },
    ["zone_big"]          = { sec = "gigant_big_strong",         cnt = 1 },
    ["zone_jumper"]       = { sec = "gigant_jumper_strong",      cnt = 1 },
    ["zone_electro"]      = { sec = "electro_chimera",           cnt = 1 },
    ["zone_x_ray"]        = { sec = "chimera_x_ray",             cnt = 1 },
    ["zone_wolf"]         = { sec = "chimera_wolf",              cnt = 1 }
}

function init(obj)
    local new_binder = embr_binder(obj)
    obj:bind_object(new_binder)
end

class "embr_binder" (object_binder)
function embr_binder:__init(obj) super(obj)
end 

function embr_binder:reload(section)
    object_binder.reload(self, section)
end

function embr_binder:reinit()
    object_binder.reinit(self)
end

function embr_binder:net_spawn(data)
    local t = mut_sec[ self.object:section() ]
    for i = 1, t.cnt do
        AI:create( t.sec, self.object:position(), self.object:level_vertex_id(), self.object:game_vertex_id() )
    end
	AI:release( AI:object( self.object:id( )) )
    return object_binder.net_spawn(self, data)
end

function embr_binder:net_destroy()
    object_binder.net_destroy(self)
end