local t = {}

function load_job(sj, gname, type, squad, groups)

	--' Гулаги ОП2
	-- псевдышы на Юпе
    if type == "upiter_gigants" then
		for i = 1,5 do
			t = { section = "logic@upiter_gigants",
			  idle = 0,
			  prior = 10, state = {0},
			  in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	-- библиотекари на Юпе
    if type == "upiter_bibliotekars" then
		for i = 1,5 do
			t = { section = "logic@upiter_bibliotekars",
			  idle = 0,
			  prior = 10, state = {0},
			  in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	-- Когти на Юпе
    if type == "upiter_kogots" then
		for i = 1,6 do
			t = { section = "logic@upiter_kogots",
			  idle = 0,
			  prior = 10, state = {0},
			  in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--' занозы в кустиках на Юпе
	if type == "upi_zanoza" then
		for i = 1,4 do
			t = { section = "logic@upi_zanoza", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end
	
	--' прыгуны у копалки на Юпе
	if type == "upi_pryguny" then
		for i = 1,6 do
			t = { section = "logic@upi_pryguny", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

--'Восточная Припять
	if type == "pri_kogots" then
		for i = 1,4 do
			t = { section = "logic@pri_kogots", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "pri_zanoza" then
		for i = 1,6 do
			t = { section = "logic@pri_zanoza", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "pri_chimera" then
		for i = 1,4 do
			t = { section = "logic@pri_chimera", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--'Лабиринт карлуши
	if type == "labi_karlushy" then
		for i = 1,6 do
			t = { section = "logic@labi_karlushy", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "labi_karlushy_two" then
		for i = 1,6 do
			t = { section = "logic@labi_karlushy_two", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--'Х-8 карлуши и полтеры на базе бюреров
	if type == "x_laba_karlushy" then
		for i = 1,6 do
			t = { section = "logic@x_laba_karlushy", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "x_laba_polterburer" then
		for i = 1,6 do
			t = { section = "logic@x_laba_polterburer", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--'Подземка Припяти карлуши, полтеры на базе бюреров и тушканы с карликами 
	if type == "podzemka_karlushy" then
		for i = 1,10 do
			t = { section = "logic@podzemka_karlushy", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "podzemka_polterburer" then
		for i = 1,8 do
			t = { section = "logic@podzemka_polterburer", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "podzemka_karliki" then
		for i = 1,12 do
			t = { section = "logic@podzemka_karliki", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--'ЧАЭС-1 химеры и соски
	if type == "chaes1_chimera" then
		for i = 1,8 do
			t = { section = "logic@chaes1_chimera", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	if type == "chaes1_kogots" then
		for i = 1,12 do
			t = { section = "logic@chaes1_kogots", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	--'Юпитер зомби в тоннеле
	if type == "upi_zombie" then
		for i = 1,10 do
			t = { section = "logic@upi_zombie", 
			idle = 0,
			prior = 20, state = {0},
			in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	-- Гулаг танков на Юпитере №1
	if type == "upi_tanki_lager1" then
		for i = 1,3 do
			t = { section = "logic@upi_tanki_lager1",
			  idle = 0,
			  prior = 10, state = {0},
			  in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end

	-- Гулаг танков на Юпитере №2
	if type == "upi_tanki_lager2" then
		for i = 1,4 do
			t = { section = "logic@upi_tanki_lager2",
			  idle = 0,
			  prior = 10, state = {0},
			  in_rest = "", out_rest = ""
			}
			table.insert(sj, t)
		end
	end
	
	-- Ратоны в Затоне 1ый гулаг
     if type == "zaton_raton_lair_1" then
	    t = { section = "logic@zaton_raton_lair11",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair12",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair13",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair14",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

	-- Ратоны в Затоне 2ой гулаг
     if type == "zaton_raton_lair_2" then
	    t = { section = "logic@zaton_raton_lair21",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair22",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair23",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair24",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair25",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair26",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair27",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

	-- Ратоны в Затоне 3ий гулаг
     if type == "zaton_raton_lair_3" then
	    t = { section = "logic@zaton_raton_lair31",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair32",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair33",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair34",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	    t = { section = "logic@zaton_raton_lair35",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

 --' Гулаг Мессера в ТД 
	if type == "val_sos" then
		t = { section = "logic@val_sos",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info.name == "val_sos_wounded"
						end
		}
		table.insert(sj, t)
	end

-- Гулаг Иванцов Пличко Барин
    if type == "bar_ivanbarprapor" then
        t = { section = "logic@bar_ivanbarprapor_ivancov",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = "",
		    predicate = function(obj_info)
        					return obj_info.profile_name == "bar_dolg_ivancov"
						end	
        }
        table.insert(sj, t)
        t = { section = "logic@bar_ivanbarprapor_plichko",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = "",
		    predicate = function(obj_info)
        					return obj_info.profile_name == "bar_dolg_guard_commander"
						end	
        }
        table.insert(sj, t)
        t = { section = "logic@bar_ivanbarprapor_barin",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = "",
		    predicate = function(obj_info)
        					return obj_info.profile_name == "sim_dolg_veteran_barin"
						end	
        }
        table.insert(sj, t)
         end

	--' Гулаги ОП2 конец

--' электрохимера в ав пещере
 if type == "av_electro_chimera" then
  t = { section = "logic@av_electro", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
    end

--' призрачная химера в ав пещере
 if type == "av_chimera_x_ray" then
  t = { section = "logic@av_x_ray", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
    end

--' бюрер в МГ
 if type == "dcity_burer" then
  t = { section = "logic@city_burer", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
    end

-- псевдыш в МГ
     if type == "dcity_gigant" then
	    t = { section = "logic@dcity_gigantik",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

-- библиотекарь в таракановке
     if type == "dcity_bibliotekar" then
	    t = { section = "logic@dcity_bibliot",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

-- кровосос-эфектор1 в ав пещере
     if type == "av_peshera_krovosos_one" then
	    t = { section = "logic@av_krovosos_one",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

-- кровосос-эфектор2 в ав пещере
     if type == "av_peshera_krovosos_two" then
	    t = { section = "logic@av_krovosos_two",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

-- Гулаг нейтралов на милитари
    if type == "military_neytral" then
        t = { section = "logic@military_neytral_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@military_neytral_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@military_neytral_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@military_neytral_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@military_neytral_kamp2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@military_neytral_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
         end

-- главный гулаг ластдей в МГ
    if type == "dcity_lastday" then
        t = { section = "logic@dcity_lastday_walker1",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker2",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker3",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker4",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker5",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_kamp1",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker6",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_kamp2",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker7",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker8",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker9",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker10",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker11",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker12",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker13",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker14",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker15",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker16",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_lastday_walker17",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        end


-- минигулаг бандосов в МГ
    if type == "dcity_bandit_garazh" then
        t = { section = "logic@dcity_bandit_garazh_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_bandit_garazh_kamp2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
     end

-- 3гулаг бандосов в МГ
    if type == "dcity_bandit_gulag3" then
        t = { section = "logic@dcity_bandit_gulag3_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_bandit_gulag3_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_bandit_gulag3_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dcity_bandit_gulag3_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
     end

	-- КРОВОСОСИКИ В МГ	
     if type == "dcity_krovosos" then
	    t = { section = "logic@dcitysos1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@dcitysos2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end

--' бюреры на атп
 if type == "atp_burer" then
  t = { section = "logic@atp_burer", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_burer", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
   end

--' химеры1 на атп
 if type == "atp_chimera1" then
  t = { section = "logic@atp_chimera1", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_chimera1", 
   idle = 0,
   prior = 20, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
   end 

--' Плоти1 на атп
 if type == "atp_flesh1" then
  t = { section = "logic@atp_flesh1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_flesh1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_flesh1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_flesh1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
 end


--' псы1 на атп
 if type == "atp_dog1" then
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  t = { section = "logic@atp_dog1", 
   idle = 0,
   prior = 5, state = {0},
   in_rest = "", out_rest = ""
  }
  table.insert(sj, t)
 end
   

    -- ГУЛАГ ЗЕЛЕНЫХ НА БОЛОТАХ
    if type == "marsh_hunters" then
        t = { section = "logic@dan_do",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "marsh_dan"
						end	
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot1_do",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot2_do",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot3_do",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot4_do",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@oxot5_do",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@dan",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "marsh_dan"
						end	
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot1",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot2",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot3",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@oxot4",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@oxot5",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    end

    -- ГУЛАГ ЗЕЛЕНЫХ В БАРЕ
    if type == "bar_ohotnik" then
        t = { section = "logic@bar_ohotnik_chel1",
            idle = 0,
            prior = 10, state = {0},
            online = true,
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@bar_ohotnik_chel2",
            idle = 0,
            prior = 10, state = {0},
            online = true,
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@bar_ohotnik_zahar_chel3",
            idle = 0,
            prior = 10, state = {0},
            online = true,
            in_rest = "", out_rest = ""
		--predicate = function(obj_info)
			            	--return obj_info.name == "stalker_green_zahar"
			            --end
        }
        table.insert(sj, t)
        t = { section = "logic@bar_ohotnik_chel4",
            idle = 0,
            prior = 10, state = {0},
            online = true,
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        end    

      -- ГУЛАГ НАЕМНИКОВ НА СВАЛКЕ
    if type == "killer_garbage_lager" then
        t = { section = "logic@killer_garbage_lager_man1",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man2",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man3",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man4",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man5",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man6",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man7",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_man8",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_kamp",
            idle = 0,
            prior = 2, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@killer_garbage_lager_kamp",
            idle = 0,
            prior = 2, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        end
	 --БАЗА НЕБА НА БОЛОТАХ	
	if type == "marsh_baza_nebo" then
	    t = { section = "logic@scy_leader",
		  idle = 0,
		  prior = 30, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "clear_scy_leader"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@ohr_leader",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@chasovoi1",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@chasovoi2",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@chasovoi3",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@patbaz1",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@patbaz2",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@barpos",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam1",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam2",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam3",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam4",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam5",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kam6",
		  idle = 0,
		  prior = 5, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@ucen",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "agr_nebo_trader"
						end	
		} 
		table.insert(sj, t)
	end	
	 --НЕБО НЕДАЛЕКО ОТ БАЗЫ(ВОЗЛЕ ТЕЛЕПОРТА НА БАЗУ)	
	if type == "marsh_small_nebo" then
	    t = { section = "logic@post_neb1",
		  idle = 0,
		  prior = 20, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		} 
		table.insert(sj, t)
		t = { section = "logic@post_neb2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		} 
		table.insert(sj, t)
		t = { section = "logic@post_cam1",
		  idle = 0,
		  prior = 20, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		} 
		table.insert(sj, t)
		t = { section = "logic@post_cam2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		}
		table.insert(sj, t)
		t = { section = "logic@post_cam3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		} 
		table.insert(sj, t)
		t = { section = "logic@post_neb3",
		  idle = 0,
		  prior = 22, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 200
		}
		table.insert(sj, t)
	end	
	-- СНОРКИ АТАКУЮТ НЕБОВЦЕВ	
     if type == "marsh_snork" then
	    t = { section = "logic@snork_atak1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snork_atak2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snork_atak3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snork_atak4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	--БАНДИТЫ В ЦЕРКВИ НА БОЛОТАХ	
	if type == "marsh_church_band" then
	    t = { section = "logic@marshban1",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban2",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban3",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban_patr",
		  idle = 0,
		  prior = 25, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban_kos1",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban_kos2",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban_kos3",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@marshban_kos4",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	end	
	 --БАЗА НЕБА У ВХОДА НА БОЛОТА	
	if type == "marsh_exit_nebo" then
	    t = { section = "logic@dyak_wait",
		  idle = 0,
		  prior = 30, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "dyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@esc_saha_plen_offline",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14001
						 end	
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata1_sit",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata2_sit",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata3_sit",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@dyak_dal",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "dyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@esc_saha_plen",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14001
						 end	
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata1",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata2",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata3",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@dyak",
		  idle = 0,
		  prior = 30, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "dyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@esc_saha",
		  idle = 0,
		  prior = 30, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14001
						 end	
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata1_ohr",
		  idle = 0,
		  prior = 20, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata2_patr",
		  idle = 0,
		  prior = 15, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
		t = { section = "logic@ex_nebo_ata3_free",
		  idle = 0,
		  prior = 10, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	end	
	-- КОТЫ И ИЗЛОМЫ ВОЗЛЕ ЦЕРКВИ НА БОЛОТАХ	
     if type == "marsh_fracture" then
	    t = { section = "logic@zver1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zver2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zver3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zver4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- ПСЕВДОПСЫ НЕДАЛЕКО ОТ ПЛАВУЧЕЙ БАЗЫ НА БОЛОТАХ	
     if type == "marsh_psevdo" then
	    t = { section = "logic@psevdo_bol1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@psevdo_bol2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@psevdo_bol3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- БОЛОТНАЯ ТВАРЬ НЕДАЛЕКО ОТ ПЛАВУЧЕЙ БАЗЫ НА БОЛОТАХ 	
     if type == "marsh_bloodsucker_effector" then
	    t = { section = "logic@bloodsucker_effector",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end	
	-- СНОРКИ НА БОЛОТАХ	
     if type == "snork_marsh" then
	    t = { section = "logic@snmar1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snmar2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snmar3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@snmar4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- КРОВОСОСИКИ НА БОЛОТАХ	
     if type == "bloodsucker_marsh" then
	    t = { section = "logic@blomar1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@blomar2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- БЮРЕРЫ И СОБАКЕВИЧИ НА БОЛОТАХ	
     if type == "burer_marsh" then
	    t = { section = "logic@burmar1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@burmar2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@burmar3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@burmar4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@burmar5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@burmar6",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- КАБАНЫ НА БОЛОТАХ	
     if type == "boar_marsh" then
	    t = { section = "logic@boarmar1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@boarmar2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@boarmar3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@boarmar4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@boarmar5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- ЧАЕПИТИЕ НА БОЛОТАХ	№1
     if type == "stalker_green1" then
	    t = { section = "logic@stagreen1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@stagreen2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@stagreen3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- ЧАЕПИТИЕ НА БОЛОТАХ	№2
     if type == "stalker_green2" then
	    t = { section = "logic@sta_green21",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@sta_green22",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@sta_green23",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	--КАЛМЫК И КО НА БОЛОТАХ	
	if type == "kalmyak_marsh" then
	    t = { section = "logic@kalmyak_offline",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kalmyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar1_offline",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar2_offline",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar3_offline",
		  idle = 0,
		  prior = 10, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_wait",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kalmyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar1",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar2",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar3",
		  idle = 0,
		  prior = 10, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak",
		  idle = 0,
		  prior = 30, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kalmyak"
						end	
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar1_ohr",
		  idle = 0,
		  prior = 20, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar2_kam",
		  idle = 0,
		  prior = 10, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@kalmyak_napar3_kam",
		  idle = 0,
		  prior = 10, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	--КОНТРОЛЕР НА ХУТОРЕ(САМЫЙ КРАЙНИЙ НА СЕВЕРО-ЗАПАДЕ) НА БОЛОТАХ	
	if type == "marsh_controller_hutor" then
	    t = { section = "logic@controller_hu_offline",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@controller_hu",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	--ЗОМБИ НА ХУТОРЕ(САМЫЙ КРАЙНИЙ НА СЕВЕРО-ЗАПАДЕ) НА БОЛОТАХ	
	if type == "marsh_zombi_hutor" then
	    t = { section = "logic@zombi_hu1",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@zombi_hu2",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@zombi_hu3",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@zombi_hu4",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@zombi_hu5",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@zombi_hu6",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	--МСТИТЕЛИ ВОЗЛЕ ПЕРЕХОДА НА КОРДОН, НА БОЛОТАХ
	if type == "marsh_sniper" then
	    t = { section = "logic@snip_hu1",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu2",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu3",
		  idle = 0,
		  prior = 15, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu4",
		  idle = 0,
		  prior = 15, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu5",
		  idle = 0,
		  prior = 15, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu6",
		  idle = 0,
		  prior = 15, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@snip_hu7",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	--КОШКИ НЕДАЛЕКО ОТ ФЕРМЫ С ОХОТНИКАМИ, НА БОЛОТАХ
	if type == "marsh_cat" then
	    t = { section = "logic@cat_hu1",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@cat_hu2",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@cat_hu3",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@cat_hu4",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@cat_hu5",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@cat_hu6",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	--БОЛОТНАЯ ТВАРЬ ЕЩЕ ОДНА ГДЕ-ТО ВОЗЛЕ ФЕРМЫ
	if type == "bloodsuker_mar2" then
	    t = { section = "logic@sucker_eff",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	--БОЛОТНАЯ ТВАРЬ №3  ГДЕ-ТО ВОЗЛЕ ВЫШКИ(САМАЯ КРАЙНЯЯ НА ЮГО-ЗАПАДЕ)
	if type == "bloodsuker_mar3" then
	    t = { section = "logic@bloodsuk_mar",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end
    --СОБАЧКИ, ВОЗЛЕ ЦЕРКВИ НА БОЛОТАХ
	if type == "dog_marsh" then
	    t = { section = "logic@dog_chu1",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@dog_chu2",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@dog_chu3",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@dog_chu4",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@dog_chu5",
		  idle = 0,
		  prior = 20, state = {0},
          online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
    end	
    -- КОТ ВОЗЛЕ ДЕРЕВНИ НА БОЛОТАХ	
	if type == "kot_mar_one" then
	    t = { section = "logic@kotsit_of",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	    t = { section = "logic@kotsit_centr",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
		 t = { section = "logic@kotsit",
		  idle = 0,
		  prior = 30, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	end	
	-- КОТ В БАРЕ НА БАЗЕ ЧИСТОГО НЕБА НА БОЛОТАХ	
	if type == "kot_mar_two" then
	    t = { section = "logic@kotrestr",
		  idle = 0,
		  prior = 30, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
		 t = { section = "logic@kotrestrbar",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	end	
	-- КОТ В БАРЕ НА ТЕРРИТОРИИ БАРА	
	if type == "bar_kot" then
	    t = { section = "logic@on_restr",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	    t = { section = "logic@kot_in_bar",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
		t = { section = "logic@kot_in_of",
		  idle = 0,
		  prior = 30, state = {2},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	end	
	-- ПСЕВДОГИГАНТЫ И СВИНЬИ НЕДАЛЕКО ОТ Ж\Д И ПЕРЕХОДА НА АГРОПРОМ, НА БОЛОТАХ	
     if type == "poltergeist_marsh" then
	    t = { section = "logic@polt1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@polt2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@polt3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@polt4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@polt5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@polt6",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- БАЗА СВОБОДЫ В ЛИМАНСКЕ
	if type == "freedom_limansk" then
--	t = { section = "logic@borman",
--		  idle = 0,
--		  prior = 30, state = {0},
--		  online = true,
--		  in_rest = "", out_rest = "",
--		  position_threshold = 600,
--		    predicate = function(obj_info)
--        					return obj_info.profile_name == "borman"
--						end	
--		} 
--		table.insert(sj, t)
        t = { section = "logic@frelim1",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@frelim2",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@frelim3",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@frelim4",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@frelim5",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@frelim6",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@frelim7",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    end
	-- ЗОМБИРОВАННЫЕ ВОЗЛЕ ПЕРЕХОДА СО СКЛАДОВ НА ЛИМАНСК	
     if type == "man_zombied_limansk" then
	    t = { section = "logic@man_zombexit1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@man_zombexit2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@man_zombexit3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@man_zombexit4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@man_zombexit5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
--[[	
	-- ЗОМБИ ВОЗЛЕ ПЕРЕХОДА СО СКЛАДОВ НА ЛИМАНСК	
     if type == "exit_of_mil" then
	    t = { section = "logic@eximil1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@eximil2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@eximil3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@eximil4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@eximil5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
	end
--]]	
	-- СНАЙПЕРЫ СВОБОДЫ ПЕРЕД МАЛЕНЬКИМ МОСТОМ В ЛИМАНСКЕ
	if type == "lim_snip_tri" then
	t = { section = "logic@house1",
		  idle = 0,
		  prior = 30, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@house2",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	-- СНАЙПЕРЫ СВОБОДЫ В ДОМЕ ВО ДВОРИКЕ В ЛИМАНСКЕ
	if type == "lim_snip_two" then
	t = { section = "logic@indom1",
		  idle = 0,
		  prior = 30, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
        t = { section = "logic@indom2",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
		t = { section = "logic@indom3",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	-- СНАЙПЕР СВОБОДЫ НА КРЫЛЬЦЕ НА ПЛОЩАДИ В ЛИМАНСКЕ
	if type == "lim_snip_one" then
	t = { section = "logic@insnip",
		  idle = 0,
		  prior = 30, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	-- ЗОМБИ ПЕРЕД МОСТИКОМ В ЛИМАНСКЕ	
     if type == "liman_zombie3" then
	    t = { section = "logic@zoli1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zoli2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zoli3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zoli4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zoli5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- ЗОМБИ АТАКУЮТ СВОБОДУ В ЛИМАНСКЕ	
     if type == "liman_zombie_atak" then
	    t = { section = "logic@zombatak1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombatak2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombatak3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombatak4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombatak5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- БЮРЕР ИЛИ КРОВОСОС НА ПЛОЩАДИ В ЛИМАНСКЕ
	if type == "lim_burer_two" then
	t = { section = "logic@lim_bu",
		  idle = 0,
		  prior = 30, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- БЮРЕР ИЛИ КРОВОСОС ОКОЛО МОСТА В ЛИМАНСКЕ
	if type == "lim_burer_one" then
	t = { section = "logic@liman_burer",
		  idle = 0,
		  prior = 30, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- ЗОМБИРОВАННЫЕ НА ПЛОЩАДИ В ЛИМАНСКЕ	
     if type == "lim_zombied_tri" then
	    t = { section = "logic@zombtri1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtri2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtri3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtri4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- ЗОМБИРОВАННЫЕ ВО ДВОРЕ В ЛИМАНСКЕ	
     if type == "lim_zombied_two" then
	    t = { section = "logic@zombtwo1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtwo2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtwo3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtwo4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombtwo5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- КРОВОСОС НА СТРОЙКЕ В ЛИМАНСКЕ
	if type == "lim_bloodsucker" then
	t = { section = "logic@lim_blood",
		  idle = 0,
		  prior = 20, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- КОНТРОЛЕР ВО ДВОРЕ НЕДАЛЕКО ОТ СТРОЙКИ В ЛИМАНСКЕ
	if type == "lim_controller" then
	t = { section = "logic@lim_contr",
		  idle = 0,
		  prior = 20, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- ЗОМБИРОВАННЫЕ ВОЗЛЕ РАЗРУШЕННОГО МОСТА В ЛИМАНСКЕ	
     if type == "lim_zombied_four" then
	    t = { section = "logic@zombfour1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombfour2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombfour3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombfour4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@zombfour5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
	-- МОНОЛИТ В ЛИМАНСКЕ
	if type == "lim_mono_one" then
	t = { section = "logic@black1",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug1"
						end	
		} 
		table.insert(sj, t)
	t = { section = "logic@black2",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug1"
						end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@black3",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug1"
						end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@black4",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug1"
						end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@limon1",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon2",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon3",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon4",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon5",
		  idle = 0,
		  prior = 25, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon6",
		  idle = 0,
		  prior = 15, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon7",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@limon8",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@limon9",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@limon10",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)		
	end	
	-- НАЕМНИКИ СЦЕНА С ХАЛЯВОЙ НА КОРДОНЕ	
    if type == "killer_esc_xalyava" then
	t = { section = "logic@xalkiller1_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller2_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller3_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)  
    t = { section = "logic@xalkiller4_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@xalkiller5_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller6_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller7_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller8_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
	t = { section = "logic@xalkiller1_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller2_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller3_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)  
    t = { section = "logic@xalkiller4_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@xalkiller5_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller6_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller7_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller8_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@xalkiller1",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller2",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller3",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)  
    t = { section = "logic@xalkiller4",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@xalkiller5",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller6",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller7",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t) 
    t = { section = "logic@xalkiller8",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)			
    end 
    -- ХАЛЯВА И ДРУГ, СЦЕНА С ХАЛЯВОЙ НА КОРДОНЕ	
    if type == "esc_xalyava" then
    t = { section = "logic@xalesc_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@xalesc_drug_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava_drug"
						end	
		} 
		table.insert(sj, t)	
    t = { section = "logic@xalesc_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@xalesc_drug_wait",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava_drug"
						end	
		} 
		table.insert(sj, t)	
    t = { section = "logic@xalesc",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@xalesc_drug",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava_drug"
						end	
		} 
		table.insert(sj, t)		
	end	
	-- ХАЛЯВА И ДРУГ НА БОЛОТАХ	
    if type == "marsh_xalyava" then
	t = { section = "logic@xalmar",
		  idle = 0,
		  prior = 25, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@xalmar_drug",
		  idle = 0,
		  prior = 25, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "xalyava_drug"
						end	
		} 
		table.insert(sj, t)
    end		
		-- ЧУК И ГЕК	
    if type == "agro_brother" then
	t = { section = "logic@chuk_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14006
						 end
		} 
		table.insert(sj, t)
    t = { section = "logic@gek_offline",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14007
						 end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@chuk",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14006
						 end
		} 
		table.insert(sj, t)
    t = { section = "logic@gek",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14007
						 end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@chuk_karav",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14006
						 end
		} 
		table.insert(sj, t)
    t = { section = "logic@gek_karav",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14007
						 end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@chuk_sit",
		  idle = 0,
		  prior = 25, state = {3},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14006
						 end
		} 
		table.insert(sj, t)
    t = { section = "logic@gek_sit",
		  idle = 0,
		  prior = 25, state = {3},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 100,
		    predicate = function(obj_info) 
                       			return obj_info.story_id == 14007
						 end	
		} 
		table.insert(sj, t)		
	end	
	-- МОНОЛИТ В ПЕРВОЙ ЗАЛЕ В ГОСПИТАЛЕ
	if type == "pred_hos_mono" then
	t = { section = "logic@hsmon1_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	t = { section = "logic@hsmon2_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon3_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon4_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon5_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon6_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon7_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon8_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon9_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon10_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon1_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	t = { section = "logic@hsmon2_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon3_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon4_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon5_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon6_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon7_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon8_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon9_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon10_wa",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon1",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	t = { section = "logic@hsmon2",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon3",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@hsmon4",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon5",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon6",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon7",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon8",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon9",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@hsmon10",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    end	
    -- ЧЕРНЫЕ В ЦЕНТРАЛЬНОЙ ЗАЛЕ В ГОСПИТАЛЕ
	if type == "centr_black_mono" then
	t = { section = "logic@blacmon1_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)	
		t = { section = "logic@blacmon2_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)
	t = { section = "logic@blacmon3_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@blacmon1",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)	
    t = { section = "logic@blacmon2",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)
    t = { section = "logic@blacmon3",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "blizn_krug3"
						end	
		} 
		table.insert(sj, t)	
    end	
    -- БОЛОТНЫЕ ТВАРИ В ГОСПИТАЛЕ	
	if type == "centr_bloodsucker" then
	    t = { section = "logic@hospblood1_of",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@hospblood2_of",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@hospblood1",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
		t = { section = "logic@hospblood2",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
    -- БЮРЕР ИЛИ КРОВОСОС В ГОСПИТАЛЕ ПОСЛЕ РАЗБОРКИ
	if type == "after_doctor_blood" then
	t = { section = "logic@hosafter1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	t = { section = "logic@hosafter2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end	
	-- КОТ И КО В ГОСПИТАЛЕ	
    if type == "hos_stalker" then
    t = { section = "logic@kot_hos_wa",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kot"
						end	
		} 
		table.insert(sj, t)
	t = { section = "logic@stalk_hos1_wa",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos2_wa",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@stalk_hos3_wa",
		  idle = 0,
		  prior = 20, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@kot_hos_kar",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kot"
						end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos1_kar",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos2_kar",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos3_kar",
		  idle = 0,
		  prior = 20, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@kot_hos",
		  idle = 0,
		  prior = 25, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600,
		    predicate = function(obj_info)
        					return obj_info.profile_name == "kot"
						end	
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos1",
		  idle = 0,
		  prior = 20, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos2",
		  idle = 0,
		  prior = 20, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@stalk_hos3",
		  idle = 0,
		  prior = 20, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	end	
	-- СТАЛКЕРЫ У БАШНИ В КРАСНОМ ЛЕСУ
	if type == "stalker_forest_bashya" then
    t = { section = "logic@stforest1",
		  idle = 0,
		  prior = 15, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)
	t = { section = "logic@stforest2",
		  idle = 0,
		  prior = 15, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest3",
		  idle = 0,
		  prior = 5, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest4",
		  idle = 0,
		  prior = 5, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest5",
		  idle = 0,
		  prior = 5, state = {0},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
    t = { section = "logic@stforest1_def",
		  idle = 0,
		  prior = 15, state = {1},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)
	t = { section = "logic@stforest2_def",
		  idle = 0,
		  prior = 15, state = {1},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest3_def",
		  idle = 0,
		  prior = 5, state = {1},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest4_def",
		  idle = 0,
		  prior = 5, state = {1},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest5_def",
		  idle = 0,
		  prior = 5, state = {1},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
    t = { section = "logic@stforest1_af",
		  idle = 0,
		  prior = 15, state = {2, 4},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)
	t = { section = "logic@stforest2_af",
		  idle = 0,
		  prior = 15, state = {2, 4},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest3_af",
		  idle = 0,
		  prior = 5, state = {2, 4},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest4_af",
		  idle = 0,
		  prior = 5, state = {2, 4},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest5_af",
		  idle = 0,
		  prior = 5, state = {2, 4},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest1_atak",
		  idle = 0,
		  prior = 15, state = {3},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)
	t = { section = "logic@stforest2_atak",
		  idle = 0,
		  prior = 15, state = {3},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest3_atak",
		  idle = 0,
		  prior = 5, state = {3},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest4_atak",
		  idle = 0,
		  prior = 5, state = {3},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)	
	t = { section = "logic@stforest5_atak",
		  idle = 0,
		  prior = 5, state = {3},
		  in_rest = "", out_rest = "",
		  position_threshold = 100
		} 
		table.insert(sj, t)			
    end 
    -- SHADOWMAN В БАШНЕ В КРАСНОМ ЛЕСУ
	if type == "shadowman_forest_bashya" then
    t = { section = "logic@shadwait",
		  idle = 0,
		  prior = 30, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@shadwait_def",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@shadwait_af",
		  idle = 0,
		  prior = 30, state = {2, 4},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@shadwait_atak",
		  idle = 0,
		  prior = 30, state = {3},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)		
	end	
	-- SHADOWMAN ЖДЕТ ИГРОКА У ВХОДА С РАДАРА В КРАСНОМ ЛЕСУ
	if type == "forest_shadowman" then
    t = { section = "logic@shadowman_of",
		  idle = 0,
		  prior = 30, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@shadowman",
		  idle = 0,
		  prior = 30, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)		
	end	
	-- НЕБОВЦЫ И ФРИМАНЫ ЗАХВАТ МОСТА В КРАСНОМ ЛЕСУ
	if type == "freed_nebo" then
    t = { section = "logic@fremneb1_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@fremneb2_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
	t = { section = "logic@fremneb3_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@fremneb4_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@fremneb5_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@fremneb6_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
	t = { section = "logic@fremneb1",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb2",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb3",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb4",
		  idle = 0,
		  prior = 5, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb5",
		  idle = 0,
		  prior = 5, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb6",
		  idle = 0,
		  prior = 5, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)
    t = { section = "logic@fremneb1_kar",
		  idle = 0,
		  prior = 15, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb2_kar",
		  idle = 0,
		  prior = 15, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb3_kar",
		  idle = 0,
		  prior = 15, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb4_kar",
		  idle = 0,
		  prior = 5, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb5_kar",
		  idle = 0,
		  prior = 5, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb6_kar",
		  idle = 0,
		  prior = 5, state = {2},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb1_most",
		  idle = 0,
		  prior = 15, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb2_most",
		  idle = 0,
		  prior = 15, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb3_most",
		  idle = 0,
		  prior = 15, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb4_most",
		  idle = 0,
		  prior = 5, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb5_most",
		  idle = 0,
		  prior = 5, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)	
    t = { section = "logic@fremneb6_most",
		  idle = 0,
		  prior = 5, state = {3},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 600
		} 
		table.insert(sj, t)			
	end	
	-- НАЕМНИКИ ЗАЩИЩАЕМ МОСТ  В КРАСНОМ ЛЕСУ
	if type == "killer_forest_most" then
    t = { section = "logic@kilmos1",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos2",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos3",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos4",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos5",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos6",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
    t = { section = "logic@kilmos7",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
    t = { section = "logic@kilmos8",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
    t = { section = "logic@kilmos9",
		  idle = 0,
		  prior = 20, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
    t = { section = "logic@kilmos10",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos11",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos12",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos13",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos14",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@kilmos15",
		  idle = 0,
		  prior = 10, state = {0},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	end 
    -- НАЕМНИКИ АТАКУЕМ МОСТ  В КРАСНОМ ЛЕСУ
	if type == "bunker_forest" then
    t = { section = "logic@bunfor1_day",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor2_day",
		  idle = 0,
		  prior = 20, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor3_day",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	t = { section = "logic@bunfor4_day",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor5_day",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor6_day",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor1_night",
		  idle = 0,
		  prior = 20, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor2_night",
		  idle = 0,
		  prior = 20, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor3_night",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	t = { section = "logic@bunfor4_night",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor5_night",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@bunfor6_night",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)		
	end	
	-- СНОРКИ ВОЗЛЕ ТАНКА В КРАСНОМ ЛЕСУ
	if type == "snork_forest" then
    t = { section = "logic@snfor1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@snfor2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@snfor3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
    t = { section = "logic@snfor4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@snfor5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	t = { section = "logic@snfor6",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@snfor7",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end	
	-- ГИГАНТ ВОЗЛЕ ТАНКА В КРАСНОМ ЛЕСУ
	if type == "giant_forest" then
    t = { section = "logic@giafor",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end	
	-- ПСЕВДОСОБАКИ В ЛЕСУ(ВЕЗДЕ И ЗЛЫЕ) В КРАСНОМ ЛЕСУ
	if type == "pseudodog_forest" then
    t = { section = "logic@pseudfor1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor4",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor5",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor6",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	t = { section = "logic@pseudfor7",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@pseudfor8",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end
	-- КРОВОСОСЫ В ЛЕСУ(ВЕЗДЕ И ЗЛЫЕ) В КРАСНОМ ЛЕСУ
	if type == "bloodsucker_forest" then
    t = { section = "logic@bloodfor1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@bloodfor2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	t = { section = "logic@bloodfor3",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end	
	-- ГИГАНТ НЕДАЛЕКО ОТ ДОМИКА ЛЕСНИКА В КРАСНОМ ЛЕСУ
	if type == "on_road_forest" then
    t = { section = "logic@on_rofor",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- КРОВОСОС НЕДАЛЕКО ОТ ВХОДА С РАДАРА В КРАСНОМ ЛЕСУ
	if type == "road_bloodsucker" then
    t = { section = "logic@roadbloodfor",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	end	
	-- БЮРЕРЫ НЕДАЛЕКО ОТ МОСТА В КРАСНОМ ЛЕСУ
	if type == "burer_forest" then
    t = { section = "logic@burfor1",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)
	t = { section = "logic@burfor2",
		  idle = 0,
		  prior = 10, state = {0},
		  in_rest = "", out_rest = ""
		} 
		table.insert(sj, t)	
	end	
	-- ОХОТНИКИ В КРАСНОМ ЛЕСУ
	if type == "green_forest" then
	t = { section = "logic@green_day_speak_night",
		  idle = 0,
		  prior = 25, state = {0, 1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_day_patr_night",
		  idle = 0,
		  prior = 15, state = {0, 1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_day1",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_day2",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_day3",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_day4",
		  idle = 0,
		  prior = 10, state = {0},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_night1",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_night2",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_night3",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@green_night4",
		  idle = 0,
		  prior = 10, state = {1},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	end	
    -- МИТЯ НА БОЛОТАХ
	if type == "mitya_marsh" then
	t = { section = "logic@mitya_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@mitya",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@mitya_free",
		  idle = 0,
		  prior = 25, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	end	
	-- ГРАБИТЕЛИ МИТИ НА БОЛОТАХ
	if type == "grab_mitya_marsh" then
	t = { section = "logic@grab_stal1_speak_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal2_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal3_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	t = { section = "logic@grab_stal4_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal5_of",
		  idle = 0,
		  prior = 15, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal1_speak",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal2",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal3",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	t = { section = "logic@grab_stal4",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@grab_stal5",
		  idle = 0,
		  prior = 15, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)		
	end 	
	-- ДЕНИС В КРАСНОМ ЛЕСУ
	if type == "forest_wound_smart" then
	t = { section = "logic@forest_wound_of",
		  idle = 0,
		  prior = 25, state = {0},
		  online = false,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@forest_wound",
		  idle = 0,
		  prior = 25, state = {1},
		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)	
	t = { section = "logic@forest_wound_sleep",
		  idle = 0,
		  prior = 25, state = {2},
--		  online = true,
		  in_rest = "", out_rest = "",
		  position_threshold = 400
		} 
		table.insert(sj, t)
	end	
end    

function load_states(gname, type)
    if type == "marsh_hunters" then
		return function(gulag)
			if not has_alife_info("sveeblov_ferma_have") then
				return 0 -- оффлайн
			else
				return 1 -- работаем
			end
		end
	end
    if type == "bar_ohotnik" then
        return function(gulag)
            return 0
        end
    end
    if type == "dcity_bandit_garazh" then
        return function(gulag)
            return 0
        end
    end
    if type == "dcity_bandit_gulag3" then
        return function(gulag)
            return 0
        end
    end
    if type == "military_neytral" then
        return function(gulag)
            return 0
        end
    end
    if type == "dcity_lastday" then
        return function(gulag)
            return 0
        end
    end
   if type == "killer_garbage_lager" then
        return function(gulag)
            return 0
        end
    end
    if type == "atp_flesh1" then        
         return function(gulag)
              return 0
         end
    end
    if type == "atp_dog1" then       
         return function(gulag)
              return 0
         end
    end
    if type == "atp_chimera1" then       
         return function(gulag)
              return 0
         end
    end
    if type == "av_chimera_x_ray" then        
         return function(gulag)
              return 0
         end
    end
    if type == "av_electro_chimera" then        
         return function(gulag)
              return 0
         end
    end
    if type == "atp_burer" then        
         return function(gulag)
              return 0
         end
    end
    if type == "dcity_burer" then        
         return function(gulag)
              return 0
         end
    end
	if type == "marsh_baza_nebo" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_small_nebo" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_snork" then
		return function(gulag)
			return 0
		end
	end
	if type == "marsh_church_band" then
		return function(gulag)
			return 0
		end
	end
	if type == "marsh_exit_nebo" then
		return function(gulag)
			if not has_alife_info("dyak_help_start") then
				return 0 -- ожидаем игрока
			elseif has_alife_info("dyak_help_have") then 
				return 2 -- отдыхаем
			else
				return 1 -- работаем
			end
		end
	end
	if type == "marsh_fracture" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_psevdo" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_bloodsucker_effector" then
        return function(gulag)
            return 0
        end
    end

--' Гулаги ОП2 
	if type == "val_sos" then
        return function(gulag)
            return 0
        end
    end

	if type == "bar_ivanbarprapor" then
        return function(gulag)
            return 0
        end
    end	

	if type == "upiter_gigants" then
        return function(gulag)
            return 0
        end
    end
	if type == "upiter_bibliotekars" then
        return function(gulag)
            return 0
        end
    end
	if type == "upiter_kogots" then
        return function(gulag)
            return 0
        end
    end
	if type == "upi_pryguny" then
        return function(gulag)
            return 0
        end
    end
	if type == "upi_zanoza" then
        return function(gulag)
            return 0
        end
    end
	if type == "pri_kogots" then
        return function(gulag)
            return 0
        end
    end
	if type == "pri_zanoza" then
        return function(gulag)
            return 0
        end
    end
	if type == "pri_chimera" then
        return function(gulag)
            return 0
        end
    end
	if type == "labi_karlushy" then
        return function(gulag)
            return 0
        end
    end
	if type == "labi_karlushy_two" then
        return function(gulag)
            return 0
        end
    end
	if type == "x_laba_karlushy" then
        return function(gulag)
            return 0
        end
    end
	if type == "x_laba_polterburer" then
        return function(gulag)
            return 0
        end
    end
	if type == "podzemka_karlushy" then
        return function(gulag)
            return 0
        end
    end
	if type == "podzemka_polterburer" then
        return function(gulag)
            return 0
        end
    end
	if type == "podzemka_karliki" then
        return function(gulag)
            return 0
        end
    end
	if type == "chaes1_chimera" then
        return function(gulag)
            return 0
        end
    end
	if type == "chaes1_kogots" then
        return function(gulag)
            return 0
        end
    end
	if type == "upi_zombie" then
        return function(gulag)
            return 0
        end
    end
	if type == "upi_tanki_lager1" then
        return function(gulag)
            return 0
        end
    end
	if type == "upi_tanki_lager2" then
        return function(gulag)
            return 0
        end
    end

	if type == "zaton_raton_lair_1" then
        return function(gulag)
            return 0
        end
    end

	if type == "zaton_raton_lair_2" then
        return function(gulag)
            return 0
        end
    end

	if type == "zaton_raton_lair_3" then
        return function(gulag)
            return 0
        end
    end
--' Гулаги ОП2 конец

	if type == "dcity_gigant" then
        return function(gulag)
            return 0
        end
    end
	if type == "dcity_bibliotekar" then
        return function(gulag)
            return 0
        end
    end
	if type == "av_peshera_krovosos_one" then
        return function(gulag)
            return 0
        end
    end
	if type == "av_peshera_krovosos_two" then
        return function(gulag)
            return 0
        end
    end
	if type == "snork_marsh" then
        return function(gulag)
            return 0
        end
    end
	if type == "bloodsucker_marsh" then
        return function(gulag)
            return 0
        end
    end
	if type == "burer_marsh" then
        return function(gulag)
            return 0
        end
    end
	if type == "dcity_krovosos" then
        return function(gulag)
            return 0
        end
    end
	if type == "boar_marsh" then
        return function(gulag)
            return 0
        end
    end
	if type == "stalker_green1" then
        return function(gulag)
            return 0
        end
    end
	if type == "stalker_green2" then
        return function(gulag)
            return 0
        end
    end
	if type == "kalmyak_marsh" then
		return function(gulag)
			if not has_alife_info("kalmyak_vstreca_start") then
				return 0 -- оффлайн
			elseif has_alife_info("kalmyak_vstreca_begin") then 
				return 2 -- отдыхаем или мочим игрока
			else
				return 1 -- работаем
			end
		end
	end
	if type == "marsh_controller_hutor" then
		return function(gulag)
			if not has_alife_info("controller_hutor_start") then
				return 0 -- оффлайн
			else
				return 1 -- работаем
			end
		end
	end
	if type == "marsh_zombi_hutor" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_sniper" then
        return function(gulag)
            return 0
        end
    end
	if type == "marsh_cat" then
        return function(gulag)
            return 0
        end
    end
	if type == "bloodsuker_mar2" then
        return function(gulag)
            return 0
        end
    end
	if type == "bloodsuker_mar3" then
        return function(gulag)
            return 0
        end
    end
	if type == "dog_marsh" then
        return function(gulag)
            return 0
        end
    end
	if type == "kot_mar_one" then
		return function(gulag)
			if not has_alife_info("dan_about_kot") then
				return 0 -- оффлайн
			elseif has_alife_info("kot_need_doc_start") then 
				return 2 -- работаем
			else
				return 1 -- сидим
			end
		end
	end
	if type == "kot_mar_two" then
		return function(gulag)
			if not has_alife_info("kot_in_marsh_restr") then
				return 0 -- идем на рестриктор
			else
				return 1 -- в баре
			end
		end
	end
	if type == "bar_kot" then
		return function(gulag)
			if not has_alife_info("bkot_spawn") then
				return 0 -- оффлайн
			elseif has_alife_info("info_del_lim_teleport") then 
				return 2 -- оффлайн
			else
				return 1 -- в баре
			end
		end
	end	
	if type == "poltergeist_marsh" then
		return function(gulag)
			return 0
		end
	end
	if type == "freedom_limansk" then
		return function(gulag)
			return 0
		end
	end
	if type == "man_zombied_limansk" then
		return function(gulag)
			return 0
		end
	end
--[[	
	if type == "exit_of_mil" then
		return function(gulag)
			return 0
		end
	end
--]]	
	if type == "lim_snip_tri" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_snip_two" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_snip_one" then
		return function(gulag)
			return 0
		end
	end
	if type == "liman_zombie3" then
		return function(gulag)
			return 0
		end
	end
	if type == "liman_zombie_atak" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_burer_two" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_burer_one" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_zombied_tri" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_zombied_two" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_bloodsucker" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_controller" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_zombied_four" then
		return function(gulag)
			return 0
		end
	end
	if type == "lim_mono_one" then
		return function(gulag)
			return 0
		end
	end
	if type == "killer_esc_xalyava" then
		return function(gulag)
			if not has_alife_info("xalyava_nebo_begin") then
				return 0 -- оффлайн
			elseif has_alife_info("xalyava_nebo_next") then 
				return 2 -- работаем
			else
				return 1 -- ждем
			end
		end
	end
	if type == "esc_xalyava" then
		return function(gulag)
			if not has_alife_info("xalyava_nebo_begin") then
				return 0 -- оффлайн
			elseif has_alife_info("xalyava_nebo_next") then 
				return 2 -- работаем
			else
				return 1 -- ждем
			end
		end
	end
	if type == "marsh_xalyava" then
		return function(gulag)
			return 0
		end
	end
	if type == "agro_brother" then
		return function(gulag)
			if not has_alife_info("kot_agro_mono_spawn") then
				return 0 -- оффлайн
			elseif has_alife_info("kot_agro_mono_spawn") and not has_alife_info("kot_agro_mono_begin") then 
				return 1 -- плен	
			elseif has_alife_info("kot_agro_mono_begin") and not has_alife_info("kot_agro_mono_actor") then 
				return 2 -- сопроваждаем актера
			elseif has_alife_info("kot_agro_mono_actor") then 
				return 3 -- отдыхаем				
			end
		end
	end
	if type == "pred_hos_mono" then
		return function(gulag)
			if not has_alife_info("info_del_lim_teleport") then
				return 0 -- оффлайн
			elseif has_alife_info("pred_mono_atak") then 
				return 2 -- работаем
			else
				return 1 -- ждем
			end
		end
	end
	if type == "centr_black_mono" then
		return function(gulag)
			if not has_alife_info("actor_in_tunel") then
				return 0 -- оффлайн
			else
				return 1 -- работаем
			end
		end
	end
	if type == "centr_bloodsucker" then
		return function(gulag)
			if not has_alife_info("actor_in_tunel") then
				return 0 -- оффлайн
			else
				return 1 -- работаем
			end
		end
	end
	if type == "after_doctor_blood" then
        return function(gulag)
            return 0
        end
    end
	if type == "hos_stalker" then
		return function(gulag)
			if not has_alife_info("info_del_lim_teleport") then
				return 0 -- оффлайн
			elseif has_alife_info("actor_in_tunel") then 
				return 2 -- отдыхаем
			else
				return 1 -- работаем
			end
		end
	end
	if type == "stalker_forest_bashya" then
		return function(gulag)
			if not has_alife_info("shadowman_zver_start") then
				return 0 -- отдыхаем
			elseif has_alife_info("shadowman_zver_start") and not has_alife_info("shadowman_all") then 
				return 1 -- воюем	
			elseif has_alife_info("shadowman_all") and not has_alife_info("contr_forest_deads") then 
				return 2 -- отдыхаем
			elseif has_alife_info("contr_forest_deads") and not has_alife_info("denis_wound_next") then 
				return 3 -- помогаем игроку	
			elseif has_alife_info("denis_wound_next") then 
				return 4 -- отдыхаем				
			end
		end
	end
	if type == "shadowman_forest_bashya" then
		return function(gulag)
			if not has_alife_info("shadowman_zver_start") then
				return 0 -- отдыхаем
			elseif has_alife_info("shadowman_zver_start") and not has_alife_info("shadowman_all") then 
				return 1 -- воюем	
			elseif has_alife_info("shadowman_all") and not has_alife_info("contr_forest_deads") then 
				return 2 -- отдыхаем
			elseif has_alife_info("contr_forest_deads") and not has_alife_info("denis_wound_next") then 
				return 3 -- помогаем игроку	
			elseif has_alife_info("denis_wound_next") then 
				return 4 -- отдыхаем				
			end
		end
	end
	if type == "forest_shadowman" then
		return function(gulag)
			if not has_alife_info("actor_in_forest") then
				return 0 -- оффлайн
			else
				return 1 -- онлайн
			end
		end
	end
	if type == "freed_nebo" then
		return function(gulag)
			if not has_alife_info("actor_in_forest") then
				return 0 -- оффлайн
			elseif has_alife_info("actor_in_forest") and not has_alife_info("shadowman_forest_start") then 
				return 1 -- ждем	
			elseif has_alife_info("shadowman_forest_start") and not has_alife_info("shadowman_forest_have") then 
				return 2 -- сопроваждаем актера
			elseif has_alife_info("shadowman_forest_have") then 
				return 3 -- отдыхаем				
			end
		end
	end
	if type == "killer_forest_most" then
        return function(gulag)
            return 0
        end
    end
	if type == "bunker_forest" then
		return function(gulag)
			if Actor ~= nil then
				if ( level.get_time_hours() >= 5 and level.get_time_hours() <= 22 ) then
					return 0  -- день
				else
					return 1  -- ночь
				end
			else
				return gulag.state
			end
		end
	end	
	if type == "snork_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "giant_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "pseudodog_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "bloodsucker_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "on_road_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "road_bloodsucker" then
        return function(gulag)
            return 0
        end
    end
	if type == "burer_forest" then
        return function(gulag)
            return 0
        end
    end
	if type == "green_forest" then
		return function(gulag)
			if Actor ~= nil then
				if ( level.get_time_hours() >= 5 and level.get_time_hours() <= 22 ) then
					return 0  -- день
				else
					return 1  -- ночь
				end
			else
				return gulag.state
			end
		end
	end	
	if type == "mitya_marsh" then
		return function(gulag)
			if not has_alife_info("klyak_forest_doc_marsh") then
				return 0 -- оффлайн
			elseif has_alife_info("klyak_forest_doc_next") then 
				return 2 -- отдыхаем
			else
				return 1 -- работаем
			end
		end
	end
	if type == "grab_mitya_marsh" then
		return function(gulag)
			if not has_alife_info("klyak_forest_doc_marsh") then
				return 0 -- оффлайн
			else
				return 1 -- онлайн
			end
		end
	end
	if type == "forest_wound_smart" then
		return function(gulag)
			if not has_alife_info("contr_forest_deads") then
				return 0 -- оффлайн
			elseif has_alife_info("denis_wound_next") then 
				return 2 -- отдыхаем
			else
				return 1 -- работаем
			end
		end
	end
end    

function load_ltx(gname, type)
    return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
    if gulag_type == "marsh_hunters" then
        return npc_community == "green"
    end
    if gulag_type == "dcity_bandit_garazh" then
        return npc_community == "bandit"
    end
    if gulag_type == "dcity_bandit_gulag3" then
        return npc_community == "bandit"
    end
    if gulag_type == "military_neytral" then
        return npc_community == "stalker"
    end
    if gulag_type == "dcity_lastday" then
        return npc_community == "lastday"
    end
    if gulag_type == "bar_ohotnik" then
        return npc_community == "green"
    end    
   if gulag_type == "killer_garbage_lager" then
        return npc_community == "killer"
    end
	if gulag_type == "marsh_baza_nebo" then
        return npc_community == "nebo"
    end
	if gulag_type == "marsh_small_nebo" then
        return npc_community == "nebo"
    end
	if gulag_type == "marsh_church_band" then
        return npc_community == "bandit"
    end
	if gulag_type == "marsh_exit_nebo" then
        return npc_community == "nebo"
    end
	if gulag_type == "stalker_green1" then
        return npc_community == "green" or npc_community == "stalker"
    end
	if gulag_type == "stalker_green2" then
        return npc_community == "green" or npc_community == "stalker"
    end
	if gulag_type == "kalmyak_marsh" then
        return npc_community == "stalker"
    end
	if gulag_type == "marsh_sniper" then
        return npc_community == "sniper"
    end
	if gulag_type == "kot_mar_one" then
		return se_obj:profile_name() == "kot"
	end
	if gulag_type == "kot_mar_two" then
		return se_obj:profile_name() == "kot"
	end
	if gulag_type == "bar_kot" then
		return se_obj:profile_name() == "kot"
	end
	if gulag_type == "freedom_limansk" then
        return npc_community == "freedom"
    end
	if gulag_type == "man_zombied_limansk" then
        return npc_community == "zombied"
    end
	if gulag_type == "lim_snip_tri" then
        return npc_community == "freedom"
    end
	if gulag_type == "lim_snip_two" then
        return npc_community == "freedom"
    end
	if gulag_type == "lim_snip_one" then
        return npc_community == "freedom"
    end
	if gulag_type == "lim_zombied_tri" then
        return npc_community == "zombied"
    end
	if gulag_type == "lim_zombied_two" then
        return npc_community == "zombied"
    end
	if gulag_type == "lim_zombied_four" then
        return npc_community == "zombied"
    end
	if gulag_type == "lim_mono_one" then
        return npc_community == "monolith"
    end
	if gulag_type == "killer_esc_xalyava" then
        return npc_community == "killer"
    end
	if gulag_type == "esc_xalyava" then
        return npc_community == "nebo"
    end
	if gulag_type == "marsh_xalyava" then
        return npc_community == "nebo"
    end
	if gulag_type == "agro_brother" then
        return npc_community == "stalker"
    end
	if gulag_type == "pred_hos_mono" then
        return npc_community == "monolith"
    end
	if gulag_type == "centr_black_mono" then
        return npc_community == "monolith"
    end
	if gulag_type == "hos_stalker" then
        return npc_community == "stalker"
    end
	if gulag_type == "stalker_forest_bashya" then
        return npc_community == "stalker"
    end
	if gulag_type == "shadowman_forest_bashya" then
		return se_obj:profile_name() == "shadowman"
	end
	if gulag_type == "forest_shadowman" then
		return se_obj:profile_name() == "shadowman"
	end
	if gulag_type == "freed_nebo" then
        return npc_community == "nebo" or npc_community == "freedom"
    end
	if gulag_type == "killer_forest_most" then
        return npc_community == "killer"
    end
	if gulag_type == "bunker_forest" then
        return npc_community == "killer"
    end
	if gulag_type == "green_forest" then
        return npc_community == "green"
    end
	if gulag_type == "grab_mitya_marsh" then
        return npc_community == "stalker" or npc_community == "bandit"
    end
	if gulag_type == "mitya_marsh" then
		return se_obj:profile_name() == "mitya"
	end
	if gulag_type == "forest_wound_smart" then
		return se_obj:profile_name() == "forest_wound"
	end
	if gulag_type == "val_sos" then
		return se_obj:profile_name() == "val_sos_wounded"
	end
	if gulag_type == "bar_ivanbarprapor" then
		return se_obj:profile_name() == "bar_dolg_ivancov" or se_obj:profile_name() == "bar_dolg_guard_commander" or se_obj:profile_name() == "sim_dolg_veteran_barin"
	end 
    return false
end

function checkMonster(npc_community, gulag_type)
    if gulag_type == "marsh_snork" then
		return npc_community == "snork"
	end
	if gulag_type == "marsh_fracture" then
		return npc_community == "fracture" or npc_community == "cat"
	end
	if gulag_type == "marsh_psevdo" then
		return npc_community == "pseudodog"
	end
	if gulag_type == "marsh_bloodsucker_effector" then
		return npc_community == "bloodsucker"
	end
	
--' Гулаги ОП2
	if gulag_type == "upiter_gigants" then
		return npc_community == "pseudo_gigant"
	end
	if gulag_type == "upiter_bibliotekars" then
		return npc_community == "fracture"
	end
	if gulag_type == "upiter_kogots" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "upi_pryguny" then
		return npc_community == "snork"
	end
	if gulag_type == "upi_zanoza" then
		return npc_community == "flesh"
	end
	if gulag_type == "pri_kogots" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "pri_zanoza" then
		return npc_community == "flesh"
	end
	if gulag_type == "pri_chimera" then
		return npc_community == "chimera"
	end
	if gulag_type == "labi_karlushy" then
		return npc_community == "fracture"
	end
	if gulag_type == "labi_karlushy_two" then
		return npc_community == "fracture"
	end
	if gulag_type == "x_laba_karlushy" then
		return npc_community == "fracture"
	end
	if gulag_type == "x_laba_polterburer" then
		return npc_community == "burer"
	end
	if gulag_type == "podzemka_karlushy" then
		return npc_community == "fracture"
	end
	if gulag_type == "podzemka_polterburer" then
		return npc_community == "burer"
	end
	if gulag_type == "podzemka_karliki" then
		return npc_community == "tushkano"
	end
	if gulag_type == "chaes1_chimera" then
		return npc_community == "chimera"
	end
	if gulag_type == "chaes1_kogots" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "upi_zombie" then
		return npc_community == "zombie"
	end
	if gulag_type == "upi_tanki_lager1" then
        return npc_community == "monolith"
        end
	if gulag_type == "upi_tanki_lager2" then
        return npc_community == "monolith"
        end
	if gulag_type == "zaton_raton_lair_1" then
		return npc_community == "tushkano"
	end
	if gulag_type == "zaton_raton_lair_2" then
		return npc_community == "tushkano"
	end
	if gulag_type == "zaton_raton_lair_3" then
		return npc_community == "tushkano"
	end
--' Гулаги ОП2 конец

	if gulag_type == "dcity_gigant" then
		return npc_community == "pseudo_gigant"
	end
	if gulag_type == "dcity_bibliotekar" then
		return npc_community == "fracture"
	end
	if gulag_type == "av_peshera_krovosos_one" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "av_peshera_krovosos_two" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "snork_marsh" then
		return npc_community == "snork"
	end
	if gulag_type == "bloodsucker_marsh" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "dcity_krovosos" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "burer_marsh" then
		return npc_community == "burer" or npc_community == "dog"
	end
	if gulag_type == "boar_marsh" then
		return npc_community == "boar"
	end
	if gulag_type == "marsh_controller_hutor" then
		return npc_community == "controller"
	end
	if gulag_type == "marsh_zombi_hutor" then
		return npc_community == "zombie"
	end
	if gulag_type == "marsh_cat" then
        return npc_community == "cat"
    end
	if gulag_type == "bloodsuker_mar2" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "bloodsuker_mar3" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "dog_marsh" then
		return npc_community == "dog"
	end
	if gulag_type == "poltergeist_marsh" then
		return npc_community == "flesh" or npc_community == "pseudo_gigant"
	end
--	if gulag_type == "exit_of_mil" then
--		return npc_community == "zombie"
--	end
	if gulag_type == "liman_zombie_atak" then
		return npc_community == "controller" or npc_community == "poltergeist"
	end
	if gulag_type == "liman_zombie3" then
		return npc_community == "controller" or npc_community == "poltergeist"
	end
	if gulag_type == "lim_burer_two" then
		return npc_community == "burer" or npc_community == "bloodsucker"
	end
	if gulag_type == "lim_burer_one" then
		return npc_community == "burer" or npc_community == "bloodsucker"
	end
	if gulag_type == "lim_bloodsucker" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "lim_controller" then
		return npc_community == "controller"
	end
	if gulag_type == "centr_bloodsucker" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "after_doctor_blood" then
		return npc_community == "burer" or npc_community == "bloodsucker"
	end
	if gulag_type == "snork_forest" then
		return npc_community == "snork"
	end
	if gulag_type == "giant_forest" then
		return npc_community == "pseudo_gigant"
	end
	if gulag_type == "pseudodog_forest" then
		return npc_community == "pseudodog"
	end
	if gulag_type == "bloodsucker_forest" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "on_road_forest" then
		return npc_community == "pseudo_gigant"
	end
	if gulag_type == "road_bloodsucker" then
		return npc_community == "bloodsucker"
	end
	if gulag_type == "burer_forest" then
		return npc_community == "burer"
	end
     if gulag_type == "atp_flesh1" then
          return npc_community == "flesh"
     end
     if gulag_type == "atp_dog1" then
          return npc_community == "dog"
     end
     if gulag_type == "atp_chimera1" then
          return npc_community == "chimera"
     end
     if gulag_type == "atp_burer" then
          return npc_community == "burer"
     end
     if gulag_type == "dcity_burer" then 
          return npc_community == "burer"
     end
     if gulag_type == "av_chimera_x_ray" then
          return npc_community == "chimera"
     end
     if gulag_type == "av_electro_chimera" then
          return npc_community == "chimera"
     end
    return false
end













