-- -*- mode: lua; encoding: windows-1251 -*-
function ggg()
	naxac_debug.show_debug_static()
end


--[[--------------------------------------------------------------------------------------------------------
	level_changers.create_teleport_on_actor(vector():set(-586.895874023438,-1.76928663253784,-409.773040771484), 2578, 4129)
------------------------------------------------------------------------------------------------------------
	Actor:set_actor_position( vector():set(326.864013671875,19.6529998779297,300.252990722656) )
------------------------------------------------------------------------------------------------------------
	local obj = level.get_target_obj()
	if obj then
		log(obj:name())
	end
------------------------------------------------------------------------------------------------------------
	local spwn_id = AI:spawn_id(97091)
	log(tostring(spwn_id))
------------------------------------------------------------------------------------------------------------
	local obj = Actor:object("wpn_ak105")
	if obj then
		if _G.tmp_ammo_type == nil then
			_G.tmp_ammo_type = {}
		end
		local v
		local data = netpk:get(AI:object(obj:id()), netpk.fState)
		local at = data.ammo_type
		for i = 0, 2000 do
			v = obj:get_wpn_int(nil, i)
			if _G.First_test_AT == nil then
				if v == at then
					log("found: %s -> %s", i, v)
					_G.tmp_ammo_type[i] = true
				end
			else
				if _G.tmp_ammo_type[i] then
					if v == at then
					log("found: %s -> %s", i, v)
					else
						_G.tmp_ammo_type[i] = nil
					end
				end
			end
		end
		_G.First_test_AT = true
		log("-------------------------------------------------")
		obj:set_wpn_int(936, 4+2+1)
	end
------------------------------------------------------------------------------------------------------------
function restore_anoms()
	if has_alife_info("snpt_vp1_have") then
		AI:create("zone_ozero",vector():set(58.848209381104,1.0079244375229,367.44982910156),276095,3760)
	end
	for i = 15606, 15618, 1 do
		AI:create(i)
	end
--	local t = {723,726,740,745,746,747,749,750,751,754,755,773}
--	for i,v in ipairs(t) do AI:create(v) end
end

function add_spot_lc()
	local obj = AI:story_object(story_ids.lc_pripyat_to_east_pripyat)
	level.map_add_object_spot_ser(obj.id, "level_changer2", "В Восточную Припять")
end
--]]--------------------------------------------------------------------------------------------------------

