-- -*- mode: lua; encoding: windows-1251 -*-
function ggg()
	naxac_debug.show_debug_static()
end

--[[--------------------------------------------------------------------------------------------------------
	Actor:set_actor_position( vector():set(353.559509277344,37.2006721496582,339.662933349609) )
------------------------------------------------------------------------------------------------------------
	-- для рассчёта стоимости апрейженных стволов
	local wpns = {
		"wpn_ak74",
		"wpn_ak74u",
		"wpn_abakan",
		"wpn_bizon",
		"wpn_mp5",
		"wpn_mp7a3",
		"wpn_uzi",
		"wpn_fn2000",
		"wpn_g36",
		"wpn_lr300",
		"wpn_sig550",
		"wpn_sg552_sk1",
		"wpn_l85",
		"wpn_famas_p3_sk1",
		"wpn_m16a2_sk1",
		"wpn_tavor",
		"wpn_hk417_sk1",
		"wpn_ak47",
		"wpn_sr25_mk11_mod0_sk1",
		"wpn_groza",
		"wpn_val",
		"wpn_svd",
		"wpn_svu",
		"wpn_m1891_30_scope",
		"wpn_vintorez",
		"wpn_b94",
		"wpn_awm",
		"wpn_saiga12c",
		"wpn_spas12",
		"wpn_wincheaster1300",
		"wpn_bm16",
		"wpn_toz34",
		"wpn_ppsh41_sk2",
		"wpn_kriss_super_v",
		"wpn_p90",
		"wpn_pkm",
		"wpn_m4",
		"wpn_m4super90",
		"wpn_m79",
		"wpn_mp5k",
		"wpn_protecta",
		"wpn_scorpion",
		"wpn_aks74m",
		"wpn_ak103",
		"wpn_ak104",
		"wpn_ak105",
		"wpn_ak107",
		"wpn_ak108",
		"wpn_ak9",
		"wpn_ak12"
	}
	local up = {
		["_kalibr"] = 0.33, ["_ves"] = 0.37, ["_otdaca"] = 0.4,
		["_kalibr_ves"] = 0.68, ["_kalibr_otdaca"] = 0.74,
		["_otdaca_ves"] = 0.87, ["_kalibr_otdaca_ves"] = 1.4
	}
	for i, sect in ipairs(wpns) do
		local t = {}
		local base_cost = sys_ini:r_u32(sect, "cost")
		log("~ %s (%s)", sect, tostring(base_cost))
		for k, v in pairs(up) do
			local new_sec = sect..k
			if sys_ini:section_exist(new_sec) then
				if base_cost <= 5000 then v = v * 1.5 end
				local add_cost = math.ceil(base_cost*v/50)*50
				local new_cost = add_cost + base_cost
				log("	%s -> %s)", new_sec, tostring(new_cost))
			end
		end
	end
------------------------------------------------------------------------------------------------------------
level_changers.create_teleport_on_actor(vector():set(-586.895874023438,-1.76928663253784,-409.773040771484), 2578, 4129)
------------------------------------------------------------------------------------------------------------
	level_changers.create_level_changer("lc_pripyat_to_bar", true)
------------------------------------------------------------------------------------------------------------
	local max_lv = n_vertexes.get_max_level_vertex()
	local actor_pos = Actor:position()
	local dist, min_dist = 0, math.huge
	local vert = 0
	for i = 1, max_lv do
		local pos = level.vertex_position(i)
		dist = pos:distance_to_sqr(actor_pos)
		if dist < min_dist then
			min_dist = dist
			vert = i
		end
	end
	log("nearest level_vertex: %s", vert)
------------------------------------------------------------------------------------------------------------
	local path_walk_name = "pri_monolith_river_port_walker_1_walk"
	local path_look_name = "pri_monolith_river_port_walker_1_look"

	local path_walk = patrol(path_walk_name)
	local path_look = patrol(path_look_name)
	for i = 0, path_walk:count()-1 do
		local flw = path_walk:flags(i)
		log("point %s[%s] : flags = %s", path_walk:name(i), tostring(i), tostring(flw:get()))
		if flw:get() ~= 0 then
			for j = 0, path_look:count()-1 do
				local fll = path_look:flags(j)
				if fll:equal(flw) then
					log( "- found look point: #%s (%s)", path_look:name(j), tostring(fll:get()) )
					break
				end
			end
		end
	end
------------------------------------------------------------------------------------------------------------
	local obj = level.get_target_obj()
	if obj then
		log(obj:name())
	end
------------------------------------------------------------------------------------------------------------
	local spwn_id = AI:spawn_id(97091)
	log(tostring(spwn_id))
------------------------------------------------------------------------------------------------------------
	local obj = Actor:object("wpn_ak105")
	if obj then
		if _G.tmp_ammo_type == nil then
			_G.tmp_ammo_type = {}
		end
		local v
		local data = netpk:get(AI:object(obj:id()), netpk.fState)
		local at = data.ammo_type
		for i = 0, 2000 do
			v = obj:get_wpn_int(nil, i)
			if _G.First_test_AT == nil then
				if v == at then
					log("found: %s -> %s", i, v)
					_G.tmp_ammo_type[i] = true
				end
			else
				if _G.tmp_ammo_type[i] then
					if v == at then
					log("found: %s -> %s", i, v)
					else
						_G.tmp_ammo_type[i] = nil
					end
				end
			end
		end
		_G.First_test_AT = true
		log("-------------------------------------------------")
		obj:set_wpn_int(936, 4+2+1)
	end
------------------------------------------------------------------------------------------------------------
function restore_anoms()
	if has_alife_info("snpt_vp1_have") then
		AI:create("zone_ozero",vector():set(58.848209381104,1.0079244375229,367.44982910156),276095,3760)
	end
	for i = 15606, 15618, 1 do
		AI:create(i)
	end
--	local t = {723,726,740,745,746,747,749,750,751,754,755,773}
--	for i,v in ipairs(t) do AI:create(v) end
end

function add_spot_lc()
	local obj = AI:story_object(story_ids.lc_pripyat_to_east_pripyat)
	level.map_add_object_spot_ser(obj.id, "level_changer2", "В Восточную Припять")
end
--]]--------------------------------------------------------------------------------------------------------

