-- -*- mode: lua; encoding: windows-1251 -*-
----------------------------------------------------------------------------------------------------------------------
--	Выдача информации сталкерам.
--	автор: Диденко Руслан (Stohe)
--	TODO: 
----------------------------------------------------------------------------------------------------------------------

local info_by_community = {}
info_by_community.default = {
	["encyclopedy_zone_artifact_af-medusa"] = "novice",
	["encyclopedy_zone_artifact_af-cristall-flower"] = "novice",
	["encyclopedy_zone_artifact_af-night-star"] = "stalker",
	["encyclopedy_zone_artifact_af-vyvert"] = "novice",
	["encyclopedy_zone_artifact_af-gravi"] = "novice",
	["encyclopedy_zone_artifact_af-gold-fish"] = "stalker",
	["encyclopedy_zone_artifact_af-blood"] = "novice",
	["encyclopedy_zone_artifact_af-mincer-meat"] = "novice",
	["encyclopedy_zone_artifact_af-soul"] = "stalker",
	["encyclopedy_zone_artifact_af-drops"] = "veteran",
	["encyclopedy_zone_artifact_af-fireball"] = "master",
	["encyclopedy_zone_artifact_af-cristall"] = "master",
	["encyclopedy_zone_artifact_af-electra-sparkler"] = "veteran",
	["encyclopedy_zone_artifact_af-electra-flash"] = "veteran",
	["encyclopedy_zone_artifact_af-electra-moonlight"] = "veteran",
	["encyclopedy_zone_artifact_af-rusty-thorn"] = "veteran",
	["encyclopedy_zone_artifact_af-rusty-kristall"] = "veteran",
	["encyclopedy_zone_artifact_af-rusty-sea-urchin"] = "master",
	["encyclopedy_zone_artifact_af-fuzz-kolobok"] = "master",
	["encyclopedy_zone_artifact_af-ameba-slime"] = "veteran",
	["encyclopedy_zone_artifact_af-ameba-slug"] = "veteran",
	["encyclopedy_zone_artifact_af-ameba-mica"] = "master",
	["encyclopedy_zone_artifact_af-dummy-glassbeads"] = "master",
	["encyclopedy_zone_artifact_af-dummy-pellicle"] = "master",
	["encyclopedy_zone_artifact_af-dummy-battery"] = "veteran",
	["encyclopedy_zone_artifact_af-dummy-dummy"] = "veteran",
	["encyclopedy_zone_artifact_af-dummy-spring"] = "master",
	["encyclopedy_zone_zone-story_story-2006"] = "novice",
	["encyclopedy_zone_zone-story_story-2008"] = "stalker",
	["encyclopedy_zone_zone-story_story-2010"] = "veteran",
	["encyclopedy_zone_zone-story_story-raid"] = "veteran",
	["encyclopedy_zone_anomalies_bald"] = "novice",
	["encyclopedy_zone_anomalies_gravi"] = "novice",
	["encyclopedy_zone_anomalies_meat"] = "novice",
	["encyclopedy_zone_anomalies_zharka"] = "stalker",
	["encyclopedy_zone_anomalies_electra"] = "novice",
	["encyclopedy_zone_anomalies_fuzz"] = "stalker",
	["encyclopedy_zone_anomalies_radioactive"] = "novice",
	["encyclopedy_zone_anomalies_ameba"] = "stalker",
	-- new
	["encyclopedy_zone_anomalies_lift"] = "stalker",
	["encyclopedy_zone_anomalies_monolit"] = "veteran",
	["encyclopedy_zone_anomalies_zhar"] = "novice",
	["encyclopedy_zone_anomalies_smallrain"] = "novice",
	["encyclopedy_zone_anomalies_sphere"] = "novice",
	["encyclopedy_zone_anomalies_zavesa"] = "novice",
	["encyclopedy_zone_anomalies_fountain"] = "novice",
	["encyclopedy_zone_anomalies_xvatalka"] = "novice",
	["encyclopedy_zone_anomalies_zvezda"] = "stalker",
	["encyclopedy_zone_anomalies_smoke"] = "stalker",
	["encyclopedy_zone_anomalies_emi"] = "veteran",
	["encyclopedy_zone_anomalies_smallrain1"] = "veteran",
	["encyclopedy_zone_anomalies_pulsar"] = "novice",
	--<<
	["encyclopedy_zone_locations_escape"] = "novice",
	["encyclopedy_zone_locations_garbage"] = "novice",
	["encyclopedy_zone_locations_agroprom"] = "stalker",
	["encyclopedy_zone_locations_darkdolina"] = "stalker",
	["encyclopedy_zone_locations_bar"] = "stalker",
	["encyclopedy_zone_locations_rostok"] = "stalker",
	["encyclopedy_zone_locations_yantar"] = "veteran",
	["encyclopedy_zone_locations_military-loc"] = "veteran",
	["encyclopedy_zone_locations_radar"] = "veteran",
	["encyclopedy_zone_locations_pripiat"] = "master",
	["encyclopedy_zone_locations_stancia"] = "master",
	["encyclopedy_mutant_crow_general"] = "novice",
	["encyclopedy_mutant_rat_general"] = "novice",
	["encyclopedy_mutant_flesh_general"] = "novice",
	["encyclopedy_mutant_blind_general"] = "novice",
	["encyclopedy_mutant_cat_general"] = "novice",
	["encyclopedy_mutant_tushkano"] = "novice",
	["encyclopedy_mutant_boar_general"] = "novice",
	["encyclopedy_mutant_pseudodog_general"] = "stalker",
	["encyclopedy_mutant_bloodsucker_general"] = "stalker",
	["encyclopedy_mutant_fracture_general"] = "stalker",
	["encyclopedy_mutant_chimera_general"] = "stalker",
	["encyclopedy_mutant_burer_general"] = "stalker",
	["encyclopedy_mutant_zombie_general"] = "stalker",
	["encyclopedy_mutant_zombieg_general"] = "stalker",
	["encyclopedy_mutant_pseudogiant_general"] = "veteran",
	["encyclopedy_mutant_poltergeist_general"] = "veteran",
	["encyclopedy_mutant_controller_general"] = "veteran",
	["encyclopedy_mutant_snork_general"] = "stalker",
	-- new
	["encyclopedy_mutant_poltergeistp"] = "veteran",
	["encyclopedy_mutant_krovosos_albinos"] = "master",
	["encyclopedy_mutant_fracture_karlik"] = "veteran",
	["encyclopedy_mutant_zanoza"] = "master",
	["encyclopedy_mutant_molerat"] = "novice",
	["encyclopedy_mutant_vypolzen"] = "veteran",
	["encyclopedy_mutant_vypolzen_red"] = "veteran",
	["encyclopedy_mutant_monster_bear"] = "master",
	["encyclopedy_mutant_chimera_new_wolf"] = "master",
	["encyclopedy_mutant_chimera_new_electro"] = "master",
	["encyclopedy_mutant_polter_flame"] = "veteran",
	["encyclopedy_mutant_chimera_black"] = "veteran",
	["encyclopedy_mutant_electro_chimera"] = "stalker",
	["encyclopedy_mutant_chimera_red"] = "stalker",
	["encyclopedy_mutant_chimera_white"] = "master",
	["encyclopedy_mutant_fire_chimera"] = "master",
	["encyclopedy_mutant_controller_flame"] = "veteran",
	["encyclopedy_mutant_controller_electro"] = "veteran",
	["encyclopedy_mutant_kontroler_act"] = "veteran",
	["encyclopedy_mutant_kontroler_5"] = "veteran",
	["encyclopedy_mutant_controller_babka"] = "veteran",
	["encyclopedy_mutant_pseudodog_grey"] = "veteran",
	["encyclopedy_mutant_karlito"] = "stalker",
	["encyclopedy_mutant_zomb14"] = "novice",
	["encyclopedy_mutant_zomb13"] = "novice",
	["encyclopedy_mutant_dog_zombie"] = "stalker",
	["encyclopedy_mutant_volkodav"] = "stalker",
	["encyclopedy_mutant_snork_jumper"] = "stalker",
	["encyclopedy_mutant_snork_stronger"] = "stalker",
	["encyclopedy_mutant_rotan"] = "master",
	["encyclopedy_mutant_poltergeist_dd"] = "master",
	["encyclopedy_mutant_electro_polter"] = "master",
	["encyclopedy_mutant_polter_xray"] = "master",
	["encyclopedy_mutant_krovosos_zombie"] = "stalker",
	["encyclopedy_mutant_flesh_swamp"] = "stalker",
	["encyclopedy_mutant_bloodsucker_child"] = "veteran",
	["encyclopedy_mutant_deathclaw"] = "veteran",
	["encyclopedy_mutant_bibliotekar_black"] = "veteran",
	["encyclopedy_mutant_burer_electro"] = "veteran",
	["encyclopedy_mutant_tushkano_strong"] = "veteran",
	["encyclopedy_mutant_new_hell"] = "master",
	["encyclopedy_mutant_oboroten"] = "master",
	["encyclopedy_mutant_spider"] = "master",
	["encyclopedy_mutant_kikimora"] = "veteran",
	["encyclopedy_mutant_vodyannoy"] = "veteran",
	["encyclopedy_mutant_karlik"] = "stalker",
	["encyclopedy_mutant_himera_prizrak"] = "veteran",
	["encyclopedy_mutant_zombieg"] = "stalker",
	["encyclopedy_mutant_black_dog"] = "veteran",
	["encyclopedy_mutant_bibliotekar"] = "master",
	["encyclopedy_mutant_tarakan"] = "stalker",
	["encyclopedy_mutant_zombie_babka"] = "novice",
	["encyclopedy_mutant_zombie_skelet"] = "stalker",
	--<<
	["encyclopedy_social_military_army"] = "novice",
	["encyclopedy_social_military_milstalkers"] = "veteran",
	["encyclopedy_social_scientists_mobile-labs"] = "stalker",
	["encyclopedy_social_stalker-clans_duty"] = "novice",
	["encyclopedy_social_stalker-clans_freedom"] = "stalker",
	["encyclopedy_social_stalker-clans_monolith"] = "stalker",
	["encyclopedy_social_stalker-clans_zomstalkers"] = "stalker",
	["encyclopedy_social_stalker-clans_bandits"] = "novice",
	["encyclopedy_social_stalker-clans_killers"] = "stalker",
	["encyclopedy_social_stalker-clans_loners"] = "veteran",
	["stalker_story_12"] = "stalker",
}

info_by_community.stalker = {
	["stalker_story_10"] = "veteran",
	["stalker_story_14"] = "veteran"
}
table.copy( info_by_community.stalker, info_by_community.default )

info_by_community.monolith = {
	["stalker_story_16"] = "stalker",
	["stalker_story_17"] = "stalker",
	["stalker_story_18"] = "stalker",
	["stalker_story_19"] = "stalker",
	["stalker_story_20"] = "stalker",
	["stalker_story_21"] = "veteran",
	["stalker_story_22"] = "veteran",
	["stalker_story_23"] = "veteran",
	["stalker_story_25"] = "veteran",
	["stalker_story_26"] = "veteran",
	["stalker_story_27"] = "veteran",
	["stalker_story_28"] = "veteran",
	["stalker_story_29"] = "veteran"
}
table.copy( info_by_community.monolith, info_by_community.default )

info_by_community.military = {
	["stalker_story_10"] = "veteran",
	["stalker_story_24"] = "veteran"
}
table.copy( info_by_community.military, info_by_community.default )

info_by_community.killer = {
	["stalker_story_7"] = "stalker",
}
table.copy( info_by_community.killer, info_by_community.default )

info_by_community.dolg = {
	["stalker_story_2"] = "stalker",
	["stalker_story_6"] = "master",
	["stalker_story_10"] = "veteran",
	["stalker_story_13"] = "veteran"
}
table.copy( info_by_community.dolg, info_by_community.default )

info_by_community.freedom = {
	["stalker_story_3"] = "stalker",
	["stalker_story_9"] = "master",
	["stalker_story_10"] = "veteran"
}
table.copy( info_by_community.freedom, info_by_community.default )

info_by_community.bandit = {
	["stalker_story_11"] = "stalker"
}
table.copy( info_by_community.bandit, info_by_community.default )

local rank_info = {
	["novice"]  = 1,
	["stalker"] = 2,
	["veteran"] = 3,
	["master"]  = 4,
	["legend"]  = 5
}

function loadInfo(npc, char_ini)
	local se_obj = AI:object(npc:id())
	if se_obj==nil or se_obj.treasure_processed == true then return end

	-- Загрузка из кастом даты
	if char_ini:section_exist("known_info") then
		local n = char_ini:line_count("known_info")
		local result, id, value = 0,"",""
	
		for i=0,n-1 do
			result, id, value = char_ini:r_line("known_info",i,"","")

			give_npc_info(npc, id)
		end
		return
	end
	
	
	-- Загрузка из генератора.
	local community_info = info_by_community[npc:character_community()] or info_by_community.default
	
	local rank = ranks.get_obj_rank_name(npc)
	local rank_num = rank_info[rank] or rank_info["stalker"]

	local tt = {}
	-- оставляем инфопоршны, которые есть и там и там.
	for k, v in pairs(community_info) do
		if rank_info[v] <= rank_num then
			-- Добавляем в список доступных знаний
			table.insert(tt, k)
		end	
	end
	
	-- одного вполне хватит - чтобы на подольше хватило
	if math.random(100) >= 90 then
		local ii = table.random(tt)
		give_npc_info(npc, ii)
	end
end

function give_npc_info(npc, info)
	-- Даем НПС инфопоршны
	npc:give_info_portion(info)

	-- Проверяем есть ли озвученная история на этот инфопоршн, и если есть
	-- добавляем ее тоже
	if sound_theme.theme[info] ~= nil then
		if db.story_by_id[npc:id()] == nil then
			db.story_by_id[npc:id()] = {}
		end
		
		table.insert(db.story_by_id[npc:id()], info)
	end
end

