----------------------------------
-- made by xStream 03.2008
----------------------------------
local table_remove = table.remove
local math_random = math.random
local math_floor = math.floor
local string_find = string.find

local excluded_npcs={
	['aem_arny'] = true, 	-- section of arena manager
	['aes_soldier_desant_wave_0006']=true,	-- name
	['aes_soldier_desant_wave_0007']=true,	-- name
	['aes_soldier_desant_wave_0015']=true,	-- name
	['aes_soldier_desant_wave_0023']=true,	-- name
	['aes_soldier_desant_wave_0029']=true,	-- name
	['aes_soldier_desant_wave_0042']=true,	-- name
	['aes_soldier_desant_wave_0053']=true,	-- name
	["agr_factory_defence_stalker3"]=true,	-- name
	["agr_factory_defence_stalker5_0000"]=true,	-- name
	["agr_krot"]="neytral_gaz_outfit_m2", -- name
	["agr_nebo_chromov1"]=true,			-- section
	["agr_nii_commander"]=true,			-- name
	["agr_ratcatcher"]=true,			-- name
	["agr_sniper1"]=true,				-- section
	["agro_adrenalin"]=true,			-- name
	["agro_chsovoy_trezv"]=true,		-- name
	["agro_mobil_torgash"]=true,		-- name
	["agro_piyn_soldier1"]=true,		-- name
	["agro_piyn_soldier2"]=true,		-- name
	["amk_artem_kulinar"]=true,			-- name
	["amk_vitek_voron"]=true,			-- name
	["andersen"]=true,					-- name
	["arhara_ecolog_guard1"]=true,		-- name
	["arhara_zaton"]=true,				-- name
	["atp_brigada1"]=true,				-- name
	["atp_brigada4"]=true,				-- name
	["atp_kalinin"]=true,				-- name
	["atp_mobil_torgovetz"]=true,		-- name
	["aver_filin"]=true,				-- name
	["aver_hunter_respawn_1"]=true,		-- section
	["aver_hunter_stalk_1"]=true,		-- name
	["aver_hunter_stalk_2"]=true,		-- name
	["aver_hunter_stalk_3"]=true,		-- name
	["aver_hunter_stalk_4"]=true,		-- name
	["aver_odnonogiy"]=true,			-- name
	["aver_pantera_new"]=true,			-- name
	["aver_zlobnuy"]=true,				-- name
	["aver_zvezdochet2"]=true,			-- name
	["bar_arena_man"]=true,				-- name
	["bar_bar_drunk_dolg"]=true,		-- name
	["bar_bar_guard"]=true,				-- name
	["bar_bar_guard_2"]=true,			-- name
--	["bar_bar_hunter"]=true,			-- character_profile
	["bar_bar_visitor_hunter"]=true,	-- name
	["bar_bar_lisiy"]=true,				-- name
	["bar_bar_osvedomitel"]=true,		-- name
	["bar_barman"]=true,				-- name
	["bar_docent"]=true,				-- name
	["bar_dolg_ivancov"]=true,			-- name
	["bar_dolg_leader"]=true,			-- name
	["bar_dolg_petrenko"]=true,			-- name
	["bar_dolg_regular_5"]=true,		-- name
	["bar_ecolog_professor"]=true,		-- name
	["bar_freedom_attacker_commander"]=true,	-- name
	["bar_ohotnik_respawn_1"]=true,		-- name
	["bar_stalker_0001"]=true,			-- name
	["bar_zastava_guard_3"]=true,		-- name
	["bkot"]=true,						-- name
	["black_doctor"]=true,				-- name
	["black_generators_stalk1"]=true,	-- name
	["black_generators_stalk2"]=true,	-- name
	["black_generators_stalk6"]=true,	-- name
	["black_generators_stalk9"]=true,	-- name
	["bodi_pantera1"]=true,				-- name
	["bodi_pantera2"]=true,				-- name
	["body1_pantera_new"]=true,			-- name
	["body2_pantera_new"]=true,			-- name
	["boloto_provodnik"]=true,			-- name
	["bunker_kluk"]=true,				-- name
	["chaes1_prizrak"]=true,			-- name
	["city_starshoy"]=true,				-- name
	["city_tema_likvidator"]=true,		-- name
	["clear_scy_leader"]=true,			-- name
	["dark_sold_atak1"]=true,			-- name
	["dark_sold_atak2"]=true,			-- name
	["dcity2_dok2_bolot2_vid"]=true,	-- name
	["dcity_dok_bolot"]=true,			-- name
	["dcity_dok_nevidim"]=true,			-- name
	["dcity_kontrol_stalk"]=true,		-- name
	["dcity_last_rasstrel1"]=true,		-- name
	["dcity_last_rasstrel2"]=true,		-- name
	["dcity_last_vhod_1"]=true,			-- name
	["dcity_last_vhod_2"]=true,			-- name
	["dcity_last_vhod_3"]=true,			-- name
	["dcity_last_vhod_4"]=true,			-- name
	["dcity_oxran_1"]=true,				-- name
	["dcity_parfumer"]=true,			-- name
	["dead_city_molniy"]=true,			-- name
	["dead_city_zlobnuy"]=true,			-- name
	["devchonka"]=true,					-- name
	["doktor"]=true,					-- name
	["doktor1"]=true,					-- name
	["dolgovazyi"]=true,				-- name
	["dyak"]=true,						-- name
	["esc_akim"]=true,					-- name
	["esc_father_pant"]=true,			-- name
	["esc_fox"]="neytral_gaz_outfit_m2",	-- name
	["esc_hunter_zaschita_1"]=true,		-- name
	["esc_hunter_zaschita_2"]=true,		-- name
	["esc_hunter_zaschita_3"]=true,		-- name
	["esc_kostya"]=true,				-- name
	["esc_provodnik"]="neytral_gaz_outfit_m2",	-- name
	["esc_novice_attacker1"]=true,		-- name
	["esc_shustryi"]=true,				-- name
	["esc_blokpost_commander"]=true,	-- name
	["esc_bridge_soldier5"]=true,		-- name
	["esc_stalker_fanat"]="neytral_gaz_outfit_m2",	-- name
	["esc_vagon_wounded"]=true,			-- name
	["esc_wolf"]="neytral_gaz_outfit_m2",	-- name
	["esc_zvezdochet"]=true,			-- name
	["escape_trader"]=true,				-- name
	["final_akim"]=true,				-- name
	["final_ara"]=true,					-- name
	["final_arhara"]=true,				-- name
	["final_barman"]=true,				-- name
	["final_borov"]=true,				-- name
	["final_chimaera"]=true,			-- name
	["final_dan"]=true,					-- name
	["final_dok_arh"]=true,				-- name
	["final_holod"]=true,				-- name
	["final_klenov"]=true,				-- name
	["final_kolmogor"]=true,			-- name
	["final_kluk"]=true,				-- name
	["final_krot"]=true,				-- name
	["final_lukash"]=true,				-- name
	["final_muxa"]=true,				-- name
	["final_otshelnik"]=true,			-- name
	["final_petrenko"]=true,			-- name
	["final_piligrim"]=true,			-- name
	["final_prizrak"]=true,				-- name
	["final_saharov"]=true,				-- name
	["final_shade_mono"]=true,			-- name
	["final_shaxter"]=true,				-- name
	["final_voronin"]=true,				-- name
	["forest_lesnik"]=true,				-- name
	["forest_ohotnik1"]=true,			-- name & section
	["forest_ohotnik2"]=true,			-- name & section
	["forest_ohotnik3"]=true,			-- name
	["forest_ohotnik4"]=true,			-- name
	["forest_ohotnik5"]=true,			-- name
	["frits"]=true,						-- name
	["gar_dm_novice"]=true,				-- name
	["gar_dolg_blokpost_4"]=true,		-- name
	["gar_hellcar"]="neytral_gaz_outfit_m2",	-- name
	["gar_seryi"]="neytral_gaz_outfit_m2",	-- name
	["gar_sniper1"]=true,				-- section
	["gar_sniper7"]=true,				-- section
	["gen_andersen1"]=true,				-- name
	["gen_pantera_life"]=true,			-- name
	["gen_prizrak_izomorf"]=true,		-- name
	["gen_sapsan1"]=true,				-- name
	["gen_solvador1"]=true,				-- name
	["gener_bl_doktor1"]=true,			-- name
	["gener_desant_black1"]=true,		-- name
	["gener_desant_black2"]=true,		-- name
	["gener_desant_black3"]=true,		-- name
	["gener_desant_black_komandir"]=true,	-- name
	["gener_dok_stalk1"]=true,			-- name
	["gener_dok_stalk2"]=true,			-- name
	["gener_dok_stalk3"]=true,			-- name
	["gener_frits2"]=true,				-- name
	["generators_black_dok"]=true,		-- name
	["generators_prizrak"]=true,		-- name
	["generators_udav"]=true,			-- name
	["hos_father_new"]=true,			-- name
	["hos_new_panterka"]=true,			-- name
	["hos_no_gulag_vhod_black1"]=true,	-- name
	["hosp_father"]=true,				-- name
	["hosp_real_bl_dok"]=true,			-- name
	["hospital_bl_dok"]=true,			-- name
	["hospital_pantera_girl"]=true,		-- name
	["kalmyak"]=true,					-- name
	["kapitan_agro"]=true,				-- name
	["kluk_bar"]=true,					-- name
	["kluk_chaes2"]=true,				-- name
	["kluk_sklad"]=true,				-- name
	["kolmogor"]=true,					-- name
	["kordon_bandit_podmoga4"]=true,	-- name
	["kot"]=true,						-- name
	["kot_hos"]=true,					-- name
	["kuzhetsov"]=true,					-- name
	["labirint_monolit_shahter"]=true,	-- name
	["labirint_shade_monolit"]=true,	-- name
	["land_arhara_zvezdochet"]=true,	-- name
	["land_lazaret_stalker1"]=true,		-- name
	["land_lazaret_stalker2"]=true,		-- name
	["land_lazaret_stalker3"]=true,		-- name
	["land_lazaret_starik"]=true,		-- name
	["land_medik"]=true,				-- name
	["last_dokplen_nachalnik"]=true,	-- name
	["marsh_barman"]=true,				-- name
	["marsh_dan"]=true,					-- name
	["marsh_hunters_respawn_1"]=true,	-- name
	["marsh_ohotnik1"]=true,			-- name
	["marsh_ohotnik2"]=true,			-- name
	["marsh_ohotnik3"]=true,			-- name
	["marsh_ohotnik4"]=true,			-- name
	["marsh_ohotnik5"]=true,			-- name
	["marsh_remont"]=true,				-- name
	["marsh_udav"]=true,				-- name
	["mil_ara"]=true,					-- name
	["mil_dolg_stalker0000"]=true,		-- name
	["mil_freedom_member0001"]=true,	-- name
	["mil_freedom_member0002"]=true,	-- name
	["mil_freedom_member0012"]=true,	-- name
	["mil_freedom_member0018"]=true,	-- name
	["mil_freedom_member0021"]=true,	-- name
	["mil_freedom_stalker0004"]=true,	-- name
	["mil_freedom_stalker0026"]=true,	-- name
	["mil_gavr_bodyguard2"]=true,		-- section
	["mil_sniper1"]=true,				-- section
	["mil_stalker0012"] = true,			-- name
	["mil_stalker0023"]=true,			-- name
	["mil_trader_gavr"]=true,			-- section
	["military_vitamin"]=true,			-- name
	["molniy"]=true,					-- name
	["muha_soldat_ranen"]=true,			-- name
	["new_kluk_nz"]=true,				-- name
	["new_prizrak"]=true,				-- name
	["odnonogiy_stalk"]=true,			-- name
	["otshelnik"]=true,					-- name
	["pantera"]=true,					-- name
	["pantera_new"]=true,				-- name
	["parfumer_dcity_shtab"]=true,		-- name
	["peshera_plennyi"]=true,			-- name
	["peshera_shaxter"]=true,			-- name
	["peshera_stahanov"]=true,			-- name
	["peshera_xabaruch"]=true,			-- name
	["piligrim"]=true,					-- name
	["piligrim_1"]=true,				-- name
	["piligrim_2"]=true,				-- name
	["piligrim_bar"]=true,				-- name
	["piligrim_sklad"]=true,			-- name
	["piyan_kapitan"]=true,				-- name
	["prip_dok_arh"]=true,				-- name
	["prip_radist2_ozhil"]=true,		-- name
	["puzir_crest"]=true,				-- name
	["puzir_sniper3"]=true,				-- name
	["radar_vitamin"]=true,				-- name
	["radist_after"]=true,				-- name
	["rostok_stalker"]=true,			-- name
	["sadik1_mono_valker4"]=true,		-- name
	["sadik_mono_valker2"]=true,		-- name
	["sadik_mono_valker3"]=true,		-- name
	["Sak"]=true,						-- name
	["sak_military_stalker"]=true,		-- name
	["sim_stalker_master_chuchelo"]=true,	-- name
	["sim_stalker_master_diador"]=true,	-- name
	["sim_stalker_master_master"]=true,	-- name
	["solvador"]=true,					-- name
	["soprov_muha_soldat"]=true,		-- name
	["stalk_kluk"]=true,				-- name
	["stalk_radist"]=true,				-- name
	["stalk_semetskiy"]=true,			-- name
	["stalker_green_bar1"]=true,		-- name
	["stalker_green_bar2"]=true,		-- name
	["stalker_green_bar3"]=true,		-- name
	["stalker_green_zahar"]=true,		-- name
	["svalka_plot_stalk"]=true,			-- name
	["tehnik_golograma"]=true,			-- name
	["val_lager_bandits_borov"]=true,	-- name
	["val_bandit_krisyk"]=true,			-- name
	["val_bandit_trader"]=true,			-- name
	["val_escort_bandit_halfdead"]=true,	-- name
	["val_escort_captive"]=true,		-- name
	["val_escort_nap1"]=true,			-- name
	["val_prisoner_captive"]=true,		-- name
	["val_sos_wounded"]=true,			-- name
	["village_pantera"]=true,			-- name
	["village_piligrim"]=true,			-- name
	["warlab_andersen2"]=true,			-- name
	["warlab_boss"]=true,				-- name
	["warlab_golograma"]=true,			-- name
	["warlab_solvador2"]=true,			-- name
	["warlab_stalker_oso"]=true,		-- name
	["warlab_vitamin"]=true,			-- name
	["yakut_agro"]=true,				-- name
	["yakut_agro2"]=true,				-- name
	["yan_scientist_help"] = true,		-- name
	["yantar_baty"]=true,				-- name
	["yantar_chernomor"]=true,			-- name
	["yantar_ecolog_general"]=true,		-- name
	["zemlyk"]=true,					-- name
	["zvezd_after_warl"]=true,			-- name
	-- snp
	["kotobegemot_bar"] = true,
	["kotobegemot_zaton"] = true,
	["ariadna_bar"] = true,
	["ariadna_zaton"] = true,
	["fenrir_zaton"] = true,
	["fenrir_2chaes"] = true,
	["fenrir_jupiter"] = true,
	["wolffrend_talk_zaton"] = true,
	["wolffrend_talk_zaton2"] = true,
	["resident_evil_zaton"] = true,
	["resident_evil_jupiter"] = true,
	["bibliofrend_talk_zaton"] = true,
	["bibliofrend_talk_black_zaton"] = true,
	["anna_zaton"] = true,
	["anna_zaton2"] = true,
	["anna_jupiter"] = true,
	["ludmila_zaton"] = true,
	["maria_kordon"] = true,
	["elsa_yantar"] = true,
	["gena_oso"] = true,
	["snegir_2chaes"] = true,
	["snegir_kordon"] = true,
	["snegir2_2chaes"] = true,
	["snegir3_2chaes"] = true,
	["bubulyka_zaton"] = true,
	["lobsang_zaton"] = true,
	["brodaga_mg"] = true,
	["brodaga_zaton"] = true,
	["boroda_jupiter"] = true,
	["boroda_zaton"] = true,
	["vesker_zaton"] = true,
	["proper70_limansk"] = true,
	["proper70_jupiter"] = true,
	["proper70_zaton"] = true,
	["tm_jupiter1"] = true,
	["parad_tm"] = true,
	["tm_brother_labirint"] = true,
	["tm_brother_2chaes"] = true,
	["volazar"] = true,
	["volazar_new"] = true,
	["ozersky"] = true,
	-- ОП-2
	["esc_buusty"]=true,
	["buusty_team_1"]=true,
	["esc_kuzmat"]=true,
	["zaton_masha"]=true,
	["zaton_dasha"]=true,
	["noi_npc"]=true,
	["chudak_npc"]=true,
	["nazar_volna"]=true,
	["kogot_volna"]=true,
	["pes_volna"]=true,
	["gonta_volna"]=true,
	["gluhar_volna"]=true,
	["medved_volna"]=true,
	["fenix_volna"]=true,
	["elbrus_volna"]=true,
	["locman_volna"]=true,
	["gromoboi_volna"]=true,
	["grif_volna"]=true,
	["buusty_zaton"]=true,
	["kuzmat_zaton"]=true,
	["mercaushiy_zaton"]=true,
	["nazar_npc"]=true,
	["masha_npc"]=true,
	["dasha_npc"]=true,
	["akill_npc"]=true,
	["zat_doc"]=true,
	["slavka_volna"]=true,
	["zat_romale"]=true,
	["esc_pantera_zadan_soldier"]=true,
	["alexandrych_marsh"]=true,
	["dragunof_npc"]=true,
	["fotograf_npc"]=true,
	["klesh_npc"]=true,
	["grom_npc"]=true,
	["labirint_shade_monolit1"]=true,
	["yan_ecolog_help1"]=true
}

local upgrade_delta = 720
local upgrade_exp = 270
local upgrade_phase = 0
local stalkers = {}
local upgrade_steps={
	[0]={
		npc_num = 15,
		prb = 0.6
	},
	[1]={
		npc_num = 11,
		prb = 0.5
	},
	[2]={
		npc_num = 10,
		prb = 0.4
	},
	[3]={
		npc_num = 8,
		prb = 0.4
	}
}
local auto_upgrades = true
local visible_auto_upgrades = false
local upgrade_top_lvl={
	l01_escape = 2,
	l02_garbage = 2,
	l03_agroprom = 2,
	l03u_agr_underground=1,
	l04_darkvalley=2,
	l04u_labx18=2,
	l05_bar=3,
	l06_rostok=3,
	l07_military=4,
	l08_yantar=3,
	l08u_brainlab=3,
	l10_radar=4,
	l10u_bunker=4,
	l11_pripyat=4,
	l12_stancia=4,
	l12_stancia_2=4,
	l12u_control_monolith=4,
	l12u_sarcofag=4,
	atp_for_test22=3,
	limansk=4,
	hospital=4,
	generators=4,
	warlab=4,
	lost_village=4,
	marsh=3,
	dead_city=4,
	zaton=4,
	jupiter=4,
	pripyat=4,
	l41_darkscape_ogse=3
}
local upgrade_over_top_chance = 0.1

local armors_by_visuals = {
	bandit = {
		stalker_bandit_3 = 1,
		stalker_bandit_8 = 2,
		stalker_bandit_veteran = 3,
		stalker_bandit_master = 4,
		stalker_bandit_exoskeleton = 4
	},
	sniper = {
		stalker_bandit_veteran = 3,
		stalker_bandit_master = 4
	},
	green = {
	    hunter5 = 3,
	    hunter4 = 3,
		hunter1 = 3,
		hunter3 = 3
	},
	nebo = {
		stalker_nebo_rukzak = 1,
		stalker_nebo_balon_1 = 2,
		stalker_nebo_nauchniy = 3,
		stalker_nebo_exoskeleton = 4
	},
	dolg = {
		stalker_do_mask = 1,
		stalker_do_balon_8 = 1,
		stalker_do_antigas = 2,
		stalker_do_nauchniy = 3,
		stalker_do_exoskeleton = 4
	},
	ecolog = {
		stalker_ecolog = 3,
		stalker_ecolog_military = 3
	},
	hero = {
		stalker_commander = 2,
--		stalker_soldier = 2,
		stalker_ecolog = 3,
		stalker_chemical = 3,
		stalker_specops = 3,
		stalker_scien = 3
	},
	killer = {
		stalker_ki_mask = 1,
		stalker_ki_antigas = 2,
		stalker_ki_nauchniy = 3,
		stalker_ki_exoskeleton = 4
	},
	militari = {
		stalker_militari_antigas_1 = 3,
		stalker_militari_antigas_2 = 3,
		stalker_militari_1 = 3,
		stalker_militari_2 = 3
	},
	monolit = {
		stalker_mo_hood_9 = 2,
		stalker_mo_mask = 1,
		stalker_mo_head1 = 1,
		stalker_mo_nauchniy = 3,
		stalker_mo_elite = 3,
		stalker_mo_exo = 4
	},
	neytral = {
		stalker_bar_security = 2,
		stalker_neytral_balon_8 = 1,
		stalker_neytral_hood_8 = 2,
		stalker_neytral_hood_9 = 2,
		stalker_neytral_hood_92 = 2,
		stalker_2_gas = 2,
		stalker_3_gas = 2,
		stalker_4_gas = 2,
		stalker_2_mask = 1,
		stalker_3_mask = 1,
		stalker_2_ochki = 1,
		stalker_4_ochki = 1,
		stalker_neytral_nauchniy = 3,
		stalker_ne_exoskeleton = 4
	},
	novice = {
		green_stalker_2 = 0,
		green_stalker_3 = 0,
		green_stalker_4 = 1,
		green_stalker_1 = 0,
		green_stalker_10 = 0,
		green_stalker_antigas = 1
	},
	soldier = {
		soldier_mask = 1,
		soldier_antigas = 2,
		stalker_military_black = 3,
		stalker_military_green = 3
	},
	svoboda = {
		stalker_sv_rukzak_1_1 = 1,
		stalker_sv_rukzak_3_1 = 1,
		stalker_sv_hood_9 = 2,
		stalker_sv_hood_91 = 2,
		stalker_sv_nauchniy = 3,
		stalker_sv_exoskeleton = 4
	}
}

local armors_by_community = {
	stalker={
		"novice","neytral"
	},
	monolith={
		"monolit"
	},
	killer={
		"killer","neytral"
	},
	ecolog={
	},
	dolg={
		"dolg"
	},
	freedom={
		"svoboda"
	},
	bandit={
		"svoboda","dolg","neytral","militari"
	},
	sniper={
		"killer","neytral"
	},
	green={
		"svoboda","dolg","neytral","militari"
	},
    nebo={
		"nebo"
	},
	military = {
		"militari"
	}
}

local armor_levels={
	green_stalker_suit = 0,
	novice_suit = 0,
	bandit_suit = 0,
	bandit_black_suit = 2,
	bandit_brown_suit = 2,
	stalker_killer_suit = 2,
	monolit_suit = 3,
	specnaz_suit = 2,
	specnaz_soldier_suit = 2,
	stalker_suit = 2,
	stalker_guard_suit = 2,
	stalker_suit_m1g = 2,
	stalker_suit_m2g = 2,
	stalker_suit_v1 = 2,
	stalker_suit_v1g = 2,
	stalker_suit_v2 = 2,
	stalker_suit_v2g = 2,
	stalker_suit_v3 = 2,
	stalker_suit_v3g = 2,
	exoskelet = 4,
	exoskelet_mo_skunk = 4,
	exoskelet_sv_skunk = 4,
	exoskelet_ki_skunk = 4,
	exoskelet_ne_skunk = 4,
	exoskelet_do_skunk = 4,
	bandit_exoskelet = 4,
	svoboda_light_suit = 1,
	svoboda_heavy_suit = 2,
	dolg_suit = 2,
	stalker_scient_suit = 3,
	stalker_dolg_nauchniy_suit = 3,
	stalker_free_nauchniy_suit = 3,
	stalker_kill_nauchniy_suit = 3,
	stalker_mono_nauchniy_suit = 3,
    monolit_suit_black = 3,
	ecolog_suit = 3,
	scientist_suit = 3,
	scientist_white = 3,
	stalker_military_suit = 3,
--	soldier_suit = 1,
    nebo_light_suit = 1,
	nebo_heavy_suit = 2,
	nebo_nauchniy_suit = 3,
	exoskelet_nebo = 4,
	stalker_comander_suit = 3
}

local suits_to_visuals = {
	stalker={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
			[[bandit\stalker_bandit_3]],
			[[bandit\stalker_bandit_5]],
			[[bandit\stalker_bandit_8]]
		},
		bandit_brown_suit = {
			[[bandit\stalker_bandit_veteran]]
		},
		bandit_black_suit = {
			[[bandit\stalker_bandit_master]]
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_mask]],
			[[killer\stalker_ki_antigas]]
		},
		monolit_suit = {
			[[monolit\stalker_mo_mask]],
			[[monolit\stalker_mo_hood_9]],
			[[monolit\stalker_mo_head1]]
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
			[[neytral\stalker_neytral_hood_8]],
			[[neytral\stalker_neytral_balon_8]]
		},
		stalker_guard_suit = {
			[[neytral\stalker_bar_security]]
		},
		stalker_suit_m1g = {
			[[neytral\stalker_neytral_hood_9]]
		},
		stalker_suit_m2g = {
			[[neytral\stalker_neytral_hood_92]]
		},
		stalker_suit_v1g = {
			[[neytral\stalker_2_gas]]
		},
		stalker_suit_v2g = {
			[[neytral\stalker_3_gas]]
		},
		stalker_suit_v3g = {
			[[neytral\stalker_4_gas]]
		},
		stalker_suit_v1 = {
			[[neytral\stalker_2_mask]],
			[[neytral\stalker_2_ochki]]
		},
		stalker_suit_v2 = {
			[[neytral\stalker_3_mask]]
		},
		stalker_suit_v3 = {
			[[neytral\stalker_4_ochki]]
		},
		exoskelet = {
			[[neytral\stalker_neytral_exoskeleton]]
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[neytral\stalker_ne_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[bandit\stalker_bandit_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
  
		},
		nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	nebo={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
			[[bandit\stalker_bandit_3]],
			[[bandit\stalker_bandit_5]],
			[[bandit\stalker_bandit_8]]
		},
		bandit_brown_suit = {
			[[bandit\stalker_bandit_veteran]]
		},
		bandit_black_suit = {
			[[bandit\stalker_bandit_master]]
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_mask]],
			[[killer\stalker_ki_antigas]]
		},
		monolit_suit = {
			[[monolit\stalker_mo_mask]],
			[[monolit\stalker_mo_hood_9]],
			[[monolit\stalker_mo_head1]]
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
			[[neytral\stalker_neytral_hood_8]],
			[[neytral\stalker_neytral_balon_8]]
		},
		stalker_guard_suit = {
			[[neytral\stalker_bar_security]]
		},
		stalker_suit_m1g = {
			[[neytral\stalker_neytral_hood_9]]
		},
		stalker_suit_m2g = {
			[[neytral\stalker_neytral_hood_92]]
		},
		stalker_suit_v1g = {
			[[neytral\stalker_2_gas]]
		},
		stalker_suit_v2g = {
			[[neytral\stalker_3_gas]]
		},
		stalker_suit_v3g = {
			[[neytral\stalker_4_gas]]
		},
		stalker_suit_v1 = {
			[[neytral\stalker_2_mask]],
			[[neytral\stalker_2_ochki]]
		},
		stalker_suit_v2 = {
			[[neytral\stalker_3_mask]]
		},
		stalker_suit_v3 = {
			[[neytral\stalker_4_ochki]]
		},
		exoskelet = {
			[[neytral\stalker_neytral_exoskeleton]]
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[neytral\stalker_ne_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[bandit\stalker_bandit_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		stalker_nano_suit = {
			[[nano\stalker_nano]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
		nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	monolith={
		green_stalker_suit = {
		},
		novice_suit = {
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
		},
		monolit_suit = {
		},
		monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
		},
		specnaz_soldier_suit = {
		},
		stalker_suit = {
		},
		stalker_guard_suit = {
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
		},
		exoskelet_ki_skunk = {
		},
		exoskelet_ne_skunk = {
		},
		exoskelet_do_skunk = {
		},
		bandit_exoskelet = {
		},
		svoboda_light_suit = {
		},
		svoboda_heavy_suit = {
		},
		dolg_suit = {
		},
		stalker_scient_suit = {
		},
		stalker_dolg_nauchniy_suit = {
		},
		stalker_free_nauchniy_suit = {
		},
		stalker_kill_nauchniy_suit = {
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		ecolog_suit = {
		},
                nebo_light_suit = {
		},
		nebo_heavy_suit = {
		},
		nebo_nauchniy_suit = {
		},
		exoskelet_nebo = {
		},
		scientist_suit = {
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
		},
--		soldier_suit = {
--		},
		stalker_comander_suit = {
		}	
	},
	killer={
		green_stalker_suit = {
		},
		novice_suit = {
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_antigas]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		monolit_suit = {
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
		},
		specnaz_soldier_suit = {
		},
		stalker_suit = {
		},
		stalker_guard_suit = {
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
		},
		exoskelet_sv_skunk = {
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
		},
		exoskelet_do_skunk = {
		},
		bandit_exoskelet = {
		},
		svoboda_light_suit = {
		},
		svoboda_heavy_suit = {
		},
		dolg_suit = {
		},
		stalker_scient_suit = {
		},
		stalker_dolg_nauchniy_suit = {
		},
		stalker_free_nauchniy_suit = {
		},
		stalker_kill_nauchniy_suit = {
		},
		stalker_mono_nauchniy_suit = {
		},
		ecolog_suit = {
		},
                nebo_light_suit = {
		},
		nebo_heavy_suit = {
		},
		nebo_nauchniy_suit = {
		},
		exoskelet_nebo = {
		},
		scientist_suit = {
		},
		stalker_military_suit = {
		},
--		soldier_suit = {
--		},
		stalker_comander_suit = {
		}	
	},
	ecolog={
		green_stalker_suit = {
		},
		novice_suit = {
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
		},
		monolit_suit = {
		},
                monolit_suit_black = {
		},
		specnaz_suit = {
		},
		specnaz_soldier_suit = {
		},
		stalker_suit = {
		},
		stalker_guard_suit = {
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
		},
		exoskelet_sv_skunk = {
		},
		exoskelet_ki_skunk = {
		},
		exoskelet_ne_skunk = {
		},
		exoskelet_do_skunk = {
		},
		bandit_exoskelet = {
		},
		svoboda_light_suit = {
		},
		svoboda_heavy_suit = {
		},
		dolg_suit = {
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
		},
		nebo_heavy_suit = {
		},
		nebo_nauchniy_suit = {
		    [[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
		},
--		soldier_suit = {
--		},
		stalker_comander_suit = {
		}	
	},
	sniper={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
			[[bandit\stalker_bandit_3]],
			[[bandit\stalker_bandit_5]],
			[[bandit\stalker_bandit_8]]
		},
		bandit_brown_suit = {
			[[bandit\stalker_bandit_veteran]]
		},
		bandit_black_suit = {
			[[bandit\stalker_bandit_master]]
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_mask]],
			[[killer\stalker_ki_antigas]]
		},
		monolit_suit = {
			[[monolit\stalker_mo_mask]],
			[[monolit\stalker_mo_hood_9]],
			[[monolit\stalker_mo_head1]]
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
			[[neytral\stalker_neytral_hood_8]],
			[[neytral\stalker_neytral_balon_8]]
		},
		stalker_guard_suit = {
			[[neytral\stalker_bar_security]]
		},
		stalker_suit_m1g = {
			[[neytral\stalker_neytral_hood_9]]
		},
		stalker_suit_m2g = {
			[[neytral\stalker_neytral_hood_92]]
		},
		stalker_suit_v1g = {
			[[neytral\stalker_2_gas]]
		},
		stalker_suit_v2g = {
			[[neytral\stalker_3_gas]]
		},
		stalker_suit_v3g = {
			[[neytral\stalker_4_gas]]
		},
		stalker_suit_v1 = {
			[[neytral\stalker_2_mask]],
			[[neytral\stalker_2_ochki]]
		},
		stalker_suit_v2 = {
			[[neytral\stalker_3_mask]]
		},
		stalker_suit_v3 = {
			[[neytral\stalker_4_ochki]]
		},
		exoskelet = {
			[[neytral\stalker_neytral_exoskeleton]]
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[neytral\stalker_ne_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[bandit\stalker_bandit_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	green={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
			[[bandit\stalker_bandit_3]],
			[[bandit\stalker_bandit_5]],
			[[bandit\stalker_bandit_8]]
		},
		bandit_brown_suit = {
			[[bandit\stalker_bandit_veteran]]
		},
		bandit_black_suit = {
			[[bandit\stalker_bandit_master]]
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_mask]],
			[[killer\stalker_ki_antigas]]
		},
		monolit_suit = {
			[[monolit\stalker_mo_mask]],
			[[monolit\stalker_mo_hood_9]],
			[[monolit\stalker_mo_head1]]
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
			[[neytral\stalker_neytral_hood_8]],
			[[neytral\stalker_neytral_balon_8]]
		},
		stalker_guard_suit = {
			[[neytral\stalker_bar_security]]
		},
		stalker_suit_m1g = {
			[[neytral\stalker_neytral_hood_9]]
		},
		stalker_suit_m2g = {
			[[neytral\stalker_neytral_hood_92]]
		},
		stalker_suit_v1g = {
			[[neytral\stalker_2_gas]]
		},
		stalker_suit_v2g = {
			[[neytral\stalker_3_gas]]
		},
		stalker_suit_v3g = {
			[[neytral\stalker_4_gas]]
		},
		stalker_suit_v1 = {
			[[neytral\stalker_2_mask]],
			[[neytral\stalker_2_ochki]]
		},
		stalker_suit_v2 = {
			[[neytral\stalker_3_mask]]
		},
		stalker_suit_v3 = {
			[[neytral\stalker_4_ochki]]
		},
		exoskelet = {
			[[neytral\stalker_neytral_exoskeleton]]
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[neytral\stalker_ne_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[bandit\stalker_bandit_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	dolg={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
		},
		monolit_suit = {
		},
                monolit_suit_black = {
		},
		specnaz_suit = {
		},
		specnaz_soldier_suit = {
		},
		stalker_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_m1g = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_m2g = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v1g = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v2g = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v3g = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v1 = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v2 = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_suit_v3 = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_guard_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		exoskelet_sv_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[dolg\stalker_do_exoskeleton]]
		},
		svoboda_light_suit = {
		},
		svoboda_heavy_suit = {
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	freedom={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
		},
		monolit_suit = {
		},
                monolit_suit_black = {
		},
		specnaz_suit = {
		},
		specnaz_soldier_suit = {
		},
		stalker_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_m1g = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_m2g = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v1g = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v2g = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v3g = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v1 = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v2 = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_suit_v3 = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		stalker_guard_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		bandit_exoskelet = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		stalker_scient_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}	
	},
	bandit={
		green_stalker_suit = {
			[[novice\green_stalker_1]],
			[[novice\green_stalker_10]],
			[[novice\green_stalker_antigas]]
		},
		novice_suit = {
			[[novice\green_stalker_2]],
			[[novice\green_stalker_3]],
			[[novice\green_stalker_4]]
		},
		bandit_suit = {
			[[bandit\stalker_bandit_3]],
			[[bandit\stalker_bandit_5]],
			[[bandit\stalker_bandit_8]]
		},
		bandit_brown_suit = {
			[[bandit\stalker_bandit_veteran]]
		},
		bandit_black_suit = {
			[[bandit\stalker_bandit_master]]
		},
		stalker_killer_suit = {
			[[killer\stalker_ki_mask]],
			[[killer\stalker_ki_antigas]]
		},
		monolit_suit = {
			[[monolit\stalker_mo_mask]],
			[[monolit\stalker_mo_hood_9]],
			[[monolit\stalker_mo_head1]]
		},
                monolit_suit_black = {
			[[monolit\stalker_mo_elite]]
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
			[[neytral\stalker_neytral_hood_8]],
			[[neytral\stalker_neytral_balon_8]]
		},
		stalker_guard_suit = {
			[[neytral\stalker_bar_security]]
		},
		stalker_suit_m1g = {
			[[neytral\stalker_neytral_hood_9]]
		},
		stalker_suit_m2g = {
			[[neytral\stalker_neytral_hood_92]]
		},
		stalker_suit_v1g = {
			[[neytral\stalker_2_gas]]
		},
		stalker_suit_v2g = {
			[[neytral\stalker_3_gas]]
		},
		stalker_suit_v3g = {
			[[neytral\stalker_4_gas]]
		},
		stalker_suit_v1 = {
			[[neytral\stalker_2_mask]],
			[[neytral\stalker_2_ochki]]
		},
		stalker_suit_v2 = {
			[[neytral\stalker_3_mask]]
		},
		stalker_suit_v3 = {
			[[neytral\stalker_4_ochki]]
		},
		exoskelet = {
			[[neytral\stalker_neytral_exoskeleton]]
		},
		exoskelet_mo_skunk = {
			[[monolit\stalker_mo_exo]]
		},
		exoskelet_sv_skunk = {
			[[svoboda\stalker_sv_exoskeleton]]
		},
		exoskelet_ki_skunk = {
			[[killer\stalker_ki_exoskeleton]]
		},
		exoskelet_ne_skunk = {
			[[neytral\stalker_ne_exoskeleton]]
		},
		exoskelet_do_skunk = {
			[[dolg\stalker_do_exoskeleton]]
		},
		bandit_exoskelet = {
			[[bandit\stalker_bandit_exoskeleton]]
		},
		svoboda_light_suit = {
			[[svoboda\stalker_sv_rukzak_1_1]],
			[[svoboda\stalker_sv_rukzak_3_1]]
		},
		svoboda_heavy_suit = {
			[[svoboda\stalker_sv_hood_9]],
			[[svoboda\stalker_sv_hood_91]]
		},
		dolg_suit = {
			[[dolg\stalker_do_antigas]],
			[[dolg\stalker_do_balon_8]],
			[[dolg\stalker_do_mask]]
		},
		stalker_scient_suit = {
			[[neytral\stalker_neytral_nauchniy]]
		},
		stalker_dolg_nauchniy_suit = {
			[[dolg\stalker_do_nauchniy]]
		},
		stalker_free_nauchniy_suit = {
			[[svoboda\stalker_sv_nauchniy]]
		},
		stalker_kill_nauchniy_suit = {
			[[killer\stalker_ki_nauchniy]]
		},
		stalker_mono_nauchniy_suit = {
			[[monolit\stalker_mo_nauchniy]]
		},
		ecolog_suit = {
			[[ecolog\stalker_ecolog]]
		},
                nebo_light_suit = {
			[[nebo\stalker_nebo_rukzak]]
		},
		nebo_heavy_suit = {
			[[nebo\stalker_nebo_balon_1]]
		},
		nebo_nauchniy_suit = {
			[[nebo\stalker_nebo_nauchniy]]
		},
		exoskelet_nebo = {
			[[nebo\stalker_nebo_exoskeleton]]
		},
		scientist_suit = {
			[[ecolog\stalker_ecolog_military]]
		},
		scientist_white = {
			[[scientist\nauchniy_white]]
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--			[[hero\stalker_soldier]]
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}
	},
	military = {
		green_stalker_suit = {
		},
		novice_suit = {
		},
		bandit_suit = {
		},
		stalker_killer_suit = {
		},
		monolit_suit = {
		},
                monolit_suit_black = {
		},
		specnaz_suit = {
			[[soldier\soldier_antigas]],
			[[soldier\soldier_spetsnaz]]
		},
		specnaz_soldier_suit = {
			[[soldier\soldier_mask]]
		},
		stalker_suit = {
		},
		stalker_guard_suit = {
		},
		exoskelet = {
		},
		exoskelet_mo_skunk = {
		},
		exoskelet_sv_skunk = {
		},
		exoskelet_ki_skunk = {
		},
		exoskelet_ne_skunk = {
		},
		exoskelet_do_skunk = {
		},
		bandit_exoskelet = {
		},
		svoboda_light_suit = {
		},
		svoboda_heavy_suit = {
		},
		dolg_suit = {
		},
		stalker_scient_suit = {
		},
		stalker_dolg_nauchniy_suit = {
		},
		stalker_free_nauchniy_suit = {
		},
		stalker_kill_nauchniy_suit = {
		},
		stalker_mono_nauchniy_suit = {
		},
		ecolog_suit = {
		},
                nebo_light_suit = {
		},
		nebo_heavy_suit = {
		},
		nebo_nauchniy_suit = {
		},
		exoskelet_nebo = {
		},
		scientist_suit = {
		},
		scientist_white = {
		},
		stalker_military_suit = {
			[[militari\stalker_militari_antigas_1]],
			[[militari\stalker_militari_1]]
		},
--		soldier_suit = {
--		},
		stalker_comander_suit = {
			[[militari\stalker_militari_antigas_2]],
			[[militari\stalker_militari_2]]
		}	
	}
}

local level_by_visual = {}
local visual_by_sect = {
	-- bandit
	["stalker_bandit"] = "bandit_outfit",
	['stalker_bandit_2'] = "bandit_outfit_red",
	['stalker_bandit_4'] = "bandit_outfit_red",
	['stalker_bandit_5'] = "bandit_outfit_blue",
	['stalker_bandit_9'] = "bandit_outfit_blue",
	['stalker_bandit_1'] = "bandit_outfit_red1",
	['stalker_bandit_drunk'] = "outfit_bandit_m1",
	['stalker_bandit_8'] = "bandit_gaz_outfit_m1",
	['stalker_bandit_veteran'] = "bandit_veteran_outfit",
	['stalker_bandit_borov'] = "bandit_master_outfit",
	['stalker_bandit_master'] = "bandit_master_outfit",
	['stalker_bandit_exoskeleton'] = "exo_bandit_outfit",
	-- dolg
	['stalker_do_antigas'] = "dolg_gaz_outfit_m1",
	['stalker_do_komandir'] = "outfit_dolg_m1",
	['stalker_do_nauchniy'] = "dolg_scientific_outfit",
	['stalker_do_exoskeleton'] = "dolg_black_exoskeleton",
	-- nebo
	['stalker_nebo_balon_1'] = "nebo_heavy_outfit",
	['stalker_nebo_rukzak'] = "nebo_light_outfit",
	['stalker_nebo_nauchniy'] = "nebo_scientific_outfit",
	['stalker_nebo_exoskeleton'] = "nebo_exo_outfit",
	-- ecolog
	['stalker_ecolog'] = "ecolog_outfit",
	['nauchniy_1'] = "ecolog_outfit",
	['protect_suit2'] = "ecolog_outfit",
	['stalker_ecolog_military'] = "protection_outfit",
	['stalker_chemical'] = "protection_outfit",
	['nauchniy_0'] = "protection_outfit",
	['protect_suit1'] = "protection_outfit",
	-- izgoy
	['izgoy'] = "bandit_veteran_outfit",
	-- killer
	['stalker_ki_head_1'] = "outfit_killer_m1",
	['stalker_ki_antigas'] = "killer_gaz_outfit_m1",
	['stalker_ki_nauchniy'] = "merc_scientific_outfit",
	['stalker_ki_exoskeleton'] = "killer_blue_exoskeleton",
    ["stalker_fantom_exoskeleton"] = "killer_green_exoskeleton",
	-- military
	['stalker_militari_1'] = "military_outfit",
	['stalker_militari_antigas_1'] = "military_outfit",
	['stalker_military'] = "military_outfit",
	['stalker_military_green'] = "military_outfit",
	['stalker_militari_2'] = "militaryspec_outfit",
	['stalker_militari_antigas_2'] = "militaryspec_outfit",
	['stalker_commander'] = "militaryspec_outfit",
	['stalker_military_black'] = "militaryspec_outfit",
	-- monolith
	['stalker_monolit'] = "monolit_outfit",
	['stalker_mo_hood_9'] = "monolit_gaz_outfit_m1",
	['stalker_mo_nauchniy'] = "monolit_scientific_outfit",
	['stalker_mo_exo'] = "monolit_exoskeleton",
	['stalker_mo_elite'] = "monolit_black_outfit",
	-- neytral		
	['stalker_hood'] = "stalker_outfit",
	['stalker_bar_security'] = "stalker_guard_outfit",
	['stalker_neytral_hood_92'] = "neytral_gaz_outfit_m1",
	['stalker_neytral_hood_9'] = "neytral_gaz_outfit_m2",
	['stalker_2_gas'] = "neytral_gaz_outfit_v1",
	['stalker_3_gas'] = "neytral_gaz_outfit_v2",
	['stalker_4_gas'] = "neytral_gaz_outfit_v3",
	['stalker_2_mask'] = "stalker_outfit_v1",
	['lisiy'] = "stalker_outfit_v1",
	['stalker_2_ochki'] = "stalker_outfit_v1",
	['stalker_2_rozh1'] = "stalker_outfit_v1",
	['stalker_2_usi'] = "stalker_outfit_v1",
	['stalker_3_mask'] = "stalker_outfit_v2",
	['hellcar'] = "stalker_outfit_v2",
	['stalker_3_rozh2'] = "stalker_outfit_v2",
	['stalker_3_usi'] = "stalker_outfit_v2",
	['stalker_4_rozh3'] = "stalker_outfit_v3",
	['serega'] = "stalker_outfit_v3",
	['stalker_4_ochki'] = "stalker_outfit_v3",
	['stalker_prizrak'] = "outfit_stalker_m1",
	['stalker_neytral_nauchniy'] = "scientific_outfit",
	['stalker_scien'] = "scientific_outfit",
	['stalker_neytral_exoskeleton'] = "exo_outfit",
	['stalker_exoskeleton'] = "exo_outfit",
	["stalker_neytral_nauchnyu_exo"] = "exo_scientist_outfit",
	["stalker_ne_exoskeleton"] = "exo_outfit",
	-- novice
	['green_stalker_1'] = "neytral_novice_outfit_m1",
	['green_stalker_2'] = "novice_outfit",
	['stalker_novice'] = "outfit_novice_m1",
	['green_stalker_3'] = "novice_outfit_rain_1",
	['green_stalker_4'] = "neytral_novice_outfit_cam",
	['green_stalker_5'] = "novice_outfit_new_2",
	['green_stalker_6'] = "novice_outfit_rain_2",
	['green_stalker_7'] = "neytral_novice_outfit_cam_2",
	['green_stalker_8'] = "neytral_novice_outfit_cam_3",
	['green_stalker_9'] = "novice_outfit_new_1",
	['green_stalker_10'] = "neytral_novice_outfit_cam_1",
	['green_stalker_11'] = "neytral_novice_outfit_new",
	['green_stalker_antigas'] = "neytral_novice_gaz_outfit_m1",

	['hunter1'] = "hunter1_novice_outfit",
	['hunter3'] = "hunter3_novice_outfit",
	['hunter4'] = "hunter4_novice_outfit",
	['hunter5'] = "hunter_novice_outfit",
	-- soldier
	['soldier_mask'] = "outfit_soldier_m1",
	['soldier_obichniy'] = "outfit_soldier_m1",
	['stalker_soldier'] = "outfit_soldier_m1",
	['soldier_spetsnaz'] = "specops_outfit",
	['stalker_specops'] = "specops_outfit",
	['soldier_antigas'] = "outfit_specnaz_m1",
	-- stalker_zombi
	['stalker_zombie1'] = "bandit_outfit",
	['stalker_zombie2'] = "dolg_outfit",
	['zombie_fresh_1'] = "dolg_outfit",
	['stalker_zombie3'] = "stalker_outfit",
	['stalker_zombie6'] = "stalker_outfit",
	['zombie_fresh_2'] = "stalker_outfit",
	['stalker_zombie4'] = "killer_outfit",
	['stalker_zombie5'] = "stalker_guard_outfit",
	['stalker_zombie7'] = "novice_outfit",
	['stalker_zombie8'] = "neytral_novice_outfit_m1",
	['stalker_zombie_specnaz'] = "specops_outfit",
	['zombie_fresh_0'] = "svoboda_heavy_outfit",
	['zombie_exoskeleton'] = "broken_exoskeleton",
	-- svoboda
	['stalker_sv_rukzak_1_1'] = "svoboda_light_outfit",
	['stalker_sv_rukzak_3'] = "svoboda_light_outfit",
	['stalker_svoboda_light'] = "svoboda_light_outfit",
	['stalker_sv_rukzak_1'] = "svoboda_heavy_outfit",
	['stalker_sv_rukzak_2'] = "svoboda_heavy_outfit",
	['stalker_sv_rukzak_3_1'] = "svoboda_heavy_outfit",
	['stalker_sv_cook'] = "svoboda_heavy_outfit",
	['stalker_sv_max'] = "svoboda_heavy_outfit",
	['stalker_svoboda_heavy'] = "svoboda_heavy_outfit",
	['stalker_sv_hood_91'] = "svoboda_gaz_outfit_m1",
	['stalker_sv_hood_9'] = "svoboda_heavy_gaz_outfit_m1",
	['stalker_sv_nauchniy'] = "freedom_scientific_outfit",
	['stalker_sv_exoskeleton'] = "svoboda_exoskeleton",
	['stalker_sv_leader'] = "outfit_svoboda_m1",
	-- other
    ["stalker_zp_exoskeleton"] = "voen_exo_outfit",
	["stalker_svs_exoskeleton"] = "outfit_lethalspeed_exo_m1",
	["stalker_svns_exoskeleton"] = "outfit_lethalspeed_exo_m2",
	["nauchniy_white"] = "scientist_suit_white"
}

function get_outfit_level(section)
	local vis_suit = sys_ini:r_string(section, "visual")
	vis_suit = string.match(vis_suit, ".*\\([%w_%-]+)")

	return armor_levels[vis_suit] or 0
end

function get_npc_visual_level(visual)
	if level_by_visual[visual] == nil then
		level_by_visual[visual] = 5
		local sect = get_suit_sect(visual)
		if sect then
			level_by_visual[visual] = get_outfit_level(sect)
		end
	end
	return level_by_visual[visual]
end

function npc_update(binder)
	if (binder.armor_check_update or 0)<time_global() then
		local npc = binder.object
		local npc_sec = protected_items.get_obj_name(npc)
		if ( not npc:alive() ) or excluded_npcs[npc_sec] then
			binder.armor_check_update = time_global() + 2000000
			return
		else
			binder.armor_check_update = time_global()+2000
		end

		if npc:critically_wounded() or npc:wounded() then return end
		if suits_to_visuals[ npc:character_community() ] then
			npc:iterate_inventory(check_armor,npc)
		end
	end
end

function check_armor(npc, item)
	if item:is_outfit() then
		local vis = sys_ini:r_string(item:section(), "visual")
		vis = string.match(vis, ".*\\([%w_%-]+)")

		local vis_tbl = suits_to_visuals[ npc:character_community() ][vis]
		if vis_tbl then
			if #vis_tbl > 0 and get_npc_current_visual_level( npc:id() ) <= armor_levels[vis] then
				if ((not Actor:see(npc) and npc:position():distance_to(Actor:position())>1) or 
					npc:position():distance_to(Actor:position())>100) then
					
					change_vis( npc:id(), "actors\\"..vis_tbl[math_random(#vis_tbl)], armor_levels[vis], true )
					local se_item = AI:object( item:id() )
					if se_item then AI:release( se_item, true ) end
				end
			end
		end
	end
end

function get_npc_level(id)
	local sobj = AI:object(id)
	if sobj and sobj.rank and sobj:rank()~=0 then
		return math_floor(sobj:rank()/upgrade_exp)
	end
	return 0
end

function get_suit_sect(vis, npc_name)
	local sect = nil
	-- для эксклюзивных нпс броник можно прописать в таблицу excluded_npcs
	if npc_name and type( excluded_npcs[npc_name] ) == "string" then
		sect = excluded_npcs[npc_name]
	elseif visual_by_sect[vis] then
		sect = visual_by_sect[vis]
	elseif string_find(vis,"stalker_bandit") then
		sect = "bandit_outfit"
	elseif string_find(vis,"stalker_do") then
		sect = "dolg_outfit"
	elseif string_find(vis,"stalker_ki") then
		sect = "killer_outfit"
	elseif string_find(vis,"stalker_mo") then
		sect = "monolit_outfit"
	elseif string_find(vis,"stalker_neytral_rukzak") then
		sect = "outfit_stalker_m2"
	elseif string_find(vis,"stalker_neytral") then
		sect = "stalker_outfit"
	elseif string_find(vis,"soldier_bandana")
		or string_find(vis,"soldier_beret")
	then
		sect = "outfit_soldier_m1"
	elseif string_find(vis,"stalker_sv_balon_1") then
		sect = "svoboda_heavy_outfit"
	end
	return sect
end

function get_npc_current_visual_level(id)
--get_console():execute("load ~~~ get_npc_current_visual_level old")
	local se_obj = AI:object(id)
	local t = netpk:get(se_obj,netpk.fState)
	if t then
		local vis = t.visual_name
		if vis then
			vis = string.match(vis, ".*\\([%w_%-]+)")
			
			return get_npc_visual_level(vis)
		end
	end
	return 0
end


function change_vis(id, suit_vis, lvl, now)
	local sobj = AI:object(id)
	if sobj and look_for_armor(sobj,suit_vis) then 
		if now then 
			local npc = level.object_by_id(id)
			if npc then
				npc:clear_animations()
			end
			switch_offline(npc)
			amk.convert_npc[id]=true
		end
		sobj:set_rank(upgrade_exp*lvl+math_random(1,50))
	end
end

--------------------------

function look_for_armor(sobj,vis)
	if vis then
		if sobj:health()<0.3 then return false end
		netpk:modify( sobj, { visual_name = vis }, netpk.fState + netpk.fConvert )
		return true
	end
	return false
end

local xrs_armor_time = -1
function update()
	--armor upgrade part
	if auto_upgrades==true then
	    local _time = amk.game_minutes()
		if xrs_armor_time < 0 then	-- if first run
			xrs_armor_time = xr_logic.pstor_retrieve(Actor,"xrs_armor_t",nil)
			if xrs_armor_time == nil then
				xrs_armor_time = _time+upgrade_delta
				xr_logic.pstor_store(Actor,"xrs_armor_t", xrs_armor_time)
			end
		elseif _time > xrs_armor_time then
			stalkers={}
			local sobj, npc_sec, map, lvl
			for a=1,65534 do
				sobj = AI:object(a)
				if sobj and (not sobj.online)
					and IAmAStalker[sobj:clsid()] and sobj:alive()
					and (not sobj.wounded)
				then
					npc_sec = protected_items.get_obj_name(sobj)
					if excluded_npcs[npc_sec] == nil then
						if sobj.m_game_vertex_id and GGraph:valid_vertex_id(sobj.m_game_vertex_id) then
							map = object_level_name(sobj)
							if map and upgrade_top_lvl[map]~=nil then
								lvl = get_npc_level(a)
								if lvl<upgrade_top_lvl[map] or math_random()<upgrade_over_top_chance then
									if not stalkers[lvl] then 
										stalkers[lvl]={}
									end
									table.insert(stalkers[lvl],a)
								end
							end
						end
					end
				end
			end
			local max_lvl = #upgrade_steps-1
			if max_lvl>0 then
				for a=0,max_lvl do
					if upgrade_steps[a]~=nil and upgrade_steps[a].npc_num~=nil and upgrade_steps[a].prb~=nil then
						for b = 1,upgrade_steps[a].npc_num do
							local cnt = #stalkers[a]
							if cnt>0 then
								local idx=math_random(cnt)
								local npc_id=stalkers[a][idx]
								if math_random()<upgrade_steps[a].prb then
									if select_next_visual(npc_id,visible_auto_upgrades)==true then
										if not stalkers[a+1] then 
											stalkers[a+1]={}
										end
										table.insert(stalkers[a+1],npc_id)
									end
									table_remove(stalkers[a],idx)
								end
							end
						end
					end
				end
			end
			xrs_armor_time = _time+upgrade_delta
			xr_logic.pstor_store(Actor, "xrs_armor_t", xrs_armor_time)
		end
	end	
end

function select_next_visual(id,now)
	local sobj=AI:object(id)
	if sobj then
		local level = get_npc_level(id)
		local com = sobj:community()
		if com and armors_by_community[com] and #armors_by_community[com] > 0 then
			local new_vis=""
			local nl=100
			for vname,allowed_armors in pairs(armors_by_community[com]) do
				if armors_by_visuals[allowed_armors] then
					for k,v in pairs(armors_by_visuals[allowed_armors]) do
						if v>level and v<=nl then
							if v<nl then
								new_vis = allowed_armors.."\\"..k
							elseif v==nl and math_random()>0.5 then
								new_vis = allowed_armors.."\\"..k
							end
							nl=v
						end
					end
				end
			end
			
			if new_vis~="" then
				change_vis(id,"actors\\"..new_vis,nl,now)
				return true
			end
		end
	end
	return false
end


-- Квестовики, заспавненные скриптом, почему-то все равно переодеваются. Принудительно переодеваем их в оригинальный визуал при лоаде
-- Потому что функция protected_items.get_obj_name возвращала неведомую хренотень
local redress_nps = {
	-- {story_id = 19901, visual = "snp\\kotobegemot"},	-- kotobegemot_bar
	-- {story_id = 19902, visual = "snp\\fenrir"},			-- fenrir_zaton
	-- {story_id = 19903, visual = "snp\\resident_evil"},	-- resident_evil_zaton
	-- {story_id = 19904, visual = "snp\\anna"},			-- anna_zaton
	-- {story_id = 19905, visual = "snp\\bubulyka"},		-- bubulyka_zaton
	-- {story_id = 19906, visual = "snp\\lobsang"},		-- lobsang_zaton
	-- {story_id = 19907, visual = "snp\\proper70"},		-- proper70_jupiter
	-- {story_id = 19908, visual = "snp\\resident_evil"},	-- resident_evil_jupiter
	-- {story_id = 19909, visual = "snp\\anna"},			-- anna_jupiter
	-- {story_id = 19911, visual = "snp\\fenrir"},			-- fenrir_jupiter
	-- {story_id = 19914, visual = "snp\\brodaga"},		-- brodaga_zaton
	-- {story_id = 19915, visual = "snp\\boroda"},			-- boroda_zaton
	-- {story_id = 19916, visual = "snp\\ludmila"},		-- ludmila_zaton
	-- {story_id = 19917, visual = "actors\\woman\\ariadna"},	-- ariadna_bar
	-- {story_id = 19920, visual = "snp\\kotobegemot"},	-- kotobegemot_zaton
	-- {story_id = 19921, visual = "actors\\woman\\ariadna"},	-- ariadna_zaton
	-- {story_id = 19922, visual = "snp\\proper70"},		-- proper70_zaton
	-- {story_id = 19923, visual = "snp\\anna"},			-- anna_zaton2
	-- {story_id = 19924, visual = "new\\supernevidimka"},	-- wolffrend_talk_zaton2
	-- {story_id = 19925, visual = "new\\supernevidimka"},	-- wolffrend_talk_zaton
	-- {story_id = 19926, visual = "new\\supernevidimka"},	-- bibliofrend_talk_zaton
	-- {story_id = 19927, visual = "new\\supernevidimka"},	-- bibliofrend_talk_black_zaton
	-- {story_id = 19928, visual = "snp\\maria"},			-- maria_kordon
	-- {story_id = 19929, visual = "snp\\snegir"},			-- snegir_2chaes
	-- {story_id = 19930, visual = "snp\\snegir"},			-- snegir_kordon
	-- {story_id = 19931, visual = "actors\\woman\\missis_saharova"},	-- elsa_yantar
	-- {story_id = 19932, visual = "actors\\ucheniy\\ucheniy_1_strong"},	-- gena_oso
	-- {story_id = 19933, visual = "snp\\vesker"},			-- vesker_zaton
	-- {story_id = 19934, visual = "actors\\nano\\stalker_nano"},	-- volazar
	-- {story_id = 19935, visual = "actors\\ucheniy\\ucheniy"},	-- volazar_new
	-- {story_id = 19936, visual = "actors\\ucheniy\\ucheniy_golo"},	-- ozersky
	-- {story_id = 21003, visual = "actors\\neytral\\stalker_2_gas"},	-- dragunof_npc
	-- {story_id = 21004, visual = "actors\\green_shapka"},	-- fotograf_npc
	-- {story_id = 21005, visual = "actors\\akill"},			-- akill_npc
	-- {story_id = 21006, visual = "actors\\neytral\\stalker_3_gas"},	-- klesh_npc
	-- {story_id = 21008, visual = "actors\\dolg\\stalker_do_balon_1"},	-- grom_npc
	-- {story_id = 21009, visual = "new\\zlobnuy"},					-- noi_npc
	-- {story_id = 21010, visual = "actors\\woman\\sky_blonda_1"},		-- zaton_masha
	-- {story_id = 21011, visual = "actors\\woman\\sky_redhead_1"},	-- zaton_dasha
	-- {story_id = 21012, visual = "actors\\woman\\sky_blonda_1"},		-- masha_npc
	-- {story_id = 21013, visual = "actors\\woman\\sky_redhead_1"},	-- dasha_npc
	-- {story_id = 21014, visual = "actors\\neytral\\nazar"},			-- nazar_npc
	-- {story_id = 21015, visual = "actors\\stalker_snork\\snorkzombie"},	-- chudak_npc
	-- {story_id = 21016, visual = "actors\\armor_voshod"},			-- grif_volna
	-- {story_id = 21017, visual = "actors\\neytral\\nazar"},			-- nazar_volna
	-- {story_id = 21018, visual = "actors\\hunters\\hunter2"},		-- kogot_volna
	-- {story_id = 21019, visual = "actors\\armor_voshod"},			-- fenix_volna
	-- {story_id = 21020, visual = "actors\\armor_voshod"},			-- elbrus_volna
	-- {story_id = 21021, visual = "actors\\armor_voshod"},			-- locman_volna
	-- {story_id = 21022, visual = "actors\\armor_voshod"},			-- gromoboi_volna
	-- {story_id = 22006, visual = "actors\\stalker_zombi\\corp_monolit"},	-- labirint_shade_monolit1
	-- {story_id = 22007, visual = "actors\\nebo\\holodov"},			-- agr_nebo_chromov1
	-- {story_id = 22008, visual = "new\\new_kruglov"},				-- yan_ecolog_help1
	-- {story_id = 30130, visual = "actors\\inkvizitors\\inkvizitor_redeye"},	-- esc_buusty
	-- {story_id = 30131, visual = "actors\\woman\\wife_pvt_voronin"},	-- esc_kuzmat
	-- {story_id = 30132, visual = "actors\\exoskelet_black"},			-- buusty_team_1
	-- {story_id = 728,   visual = "actors\\svoboda\\stalker_sv_cook"}
}

function redress()
	local obj, params, fld
	for i, v in ipairs(redress_nps) do 
		obj = AI:story_object(v.story_id)
		if obj then
			params = netpk:get(obj,netpk.fState)
			if params.visual_name ~= v.visual then
				params.visual_name = v.visual
				netpk:set(obj,params)
			end
		end
	end
end

